### PR TITLE
[Tests] Introduce new IdeUnitTests.dll

### PR DESCRIPTION
**Pull request by Therzok**
This PR adds a new assembly that implements some TestBase functionality that can be reused by addins' test suites.

It also adds TypeForwarders for whatever users of MonoDevelop.Ide.Tests.dll just in case, so we don't break ABI.

### CODE REVIEW

**Comment by Therzok** [comment]
This allows for running tests from a non-deployed tests collection from md-addins

**Comment by Therzok** [comment]
@slluis PTAL

**Comment by slluis** [comment]
A more solid solution would be to change the logic in UnitTests.dll that assumes tests run on the MD tests directory, then that assembly can be local copied when necessary.

**Comment by Therzok** [comment]
@slluis repurposed this PR.

It seems like the way to go is for each out of tree test assembly to define its own test-projects directory to use as a test roots dir.

**Comment by slluis** [comment]
Tests failed...

**Comment by Therzok** [comment]
Had forgotten to add the test project.

**Comment by Therzok** [comment]
Looks good to go!

**Comment by Therzok** [comment]
Rebased.

**Pull request merged**
