### PR TITLE
[mdtool] Call terminate when ending

### PR DESCRIPTION
**Pull request by iainx**
Fixes VSTS #725899

### CODE REVIEW

**Comment by slluis** [comment]
Adding MonoDevelop.Ide as reference means loading a ton of unnecessary code. Can we include GtkWorkarounds by referencing the source file?

**Comment by sevoku** [comment]
Including GtkWorkarounds.cs would pull other dependencies in (such as Gtk). I'd rather just add the termination code here like:

```csharp

const string LIBOBJC ="/usr/lib/libobjc.dylib";

[DllImport (LIBOBJC, EntryPoint = "objc_msgSend")]
static extern void objc_msgSend_NSInt64_NSInt32 (IntPtr klass, IntPtr selector, int arg);

static void MacTerminate ()
{
	objc_msgSend_NSInt64_NSInt32 (sharedApp, sel_terminate, 0);
}

static void Shutdown (bool terminate)
{
	Runtime.Shutdown ();

	if (terminate && Runtime.IsMac) {
		MacTerminate ();
	}
}
```

**Comment by sevoku** [comment]
@iainx the build failed, no sure if that's related to the change or just needs a rebase.

**Comment by iainx** [comment]
@sevoku yeah, the code wasn't falling through correctly anymore, fixed and rebased.

**Pull request merged**
