### PR TITLE
[Shell] Language selection show each language in its own locale

### PR DESCRIPTION
**Pull request by jsuarezruiz**
With this change, each language name under language selection shows in its native translation.

Now, we have situations like this.
korean-problem

Languages are impossible to select for a non-Korean speaker. Changed to:
Screenshot 2019-03-19 at 13 47 52

_NOTE: Native translation from every language po file used in MonoDevelop._

Fixes VSTS #679609

### CODE REVIEW

**Comment by jsuarezruiz** [comment]
With this change, we will have the same behaviour as Visual Studio for Windows.
Screenshot 2019-03-19 at 12 51 14

**Comment by jsuarezruiz** [comment]
Good question @sevoku. @slluis What do you think?

**Comment by slluis** [comment]
Yeah, we can sort.

**Comment by jsuarezruiz** [comment]
Applied the sort. cc @sevoku

**Comment by netonjm** [comment]
If we are translating the titles, Catalan should be **Català**? cc @slluis  💃

**Pull request closed without merging**
