### PR TITLE
Fixes VSTS 558577: Setting Place System directives first cannot be tu…

### PR DESCRIPTION
**Pull request by mkrueger**
…rned off

https://devdiv.visualstudio.com/DevDiv/_workitems/edit/617333

This option is not supported anymore.

### CODE REVIEW

**Comment by mrward** [comment]
VS 2017 supports this. Just wondering why VS Mac cannot support it?

In VS 2017 you can go to options - Text Editor - C# - Advanced and there is a `Place 'System' directives first when sorting usings` check box. It is off by default.

**Comment by mhutch** [comment]
This can be controlled from editorconfig, so there's definitely a Roslyn option we can map to

**Comment by mkrueger** [comment]
In any case it is >not< a formatting option.

**Comment by Therzok** [comment]
This looks better.

**Pull request merged**
