### PR TITLE
Fix VSTS 585147: Code in indented @{} block jumps up a line when committed

### PR DESCRIPTION
**Pull request by KirillOsenkov**
Fix VSTS 585147
Code in TryGetWhitespaceGroup() didn't take tab characters `\t` into account.

### CODE REVIEW

**Comment by KirillOsenkov** [comment]
FYI @heejaechang @jasonmalinowski

**Comment by KirillOsenkov** [comment]
@monojenkins backport release-7.6

**Comment by KirillOsenkov** [comment]
@slluis if the build is green, it would be super nice to have this in release-7.6, this fixes a lot of smart indent and formatting issues.

**Comment by slluis** [comment]
@mkrueger can you please review?

**Pull request merged**
