### PR TITLE
Fixed '530391 - Placing caret in global:: qualifier highlights whole …

### PR DESCRIPTION
**Pull request by mkrueger**
…document'

This fix switches over to the roslyn highlighting engine.

### CODE REVIEW

**Comment by mkrueger** [comment]
Keywords are no longer highlighted but I suppose that is the right engine in roslyn to use ? 

Keyword highlighting is not really important - more important is the read/write coloring - is the highighting engine still a work in progress in roslyn ? 

btw. I think it's usable that way. And a good first step to get more roslyn provided features just working.

**Comment by Therzok** [comment]
Yes, it seems like the roslyn engine only highlights symbols.

**Comment by KirillOsenkov** [comment]
Roslyn also highlights many things, such as certain keywords:
http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Extensibility/Highlighting/IHighlighter.cs,dd45304f10610aad,references

**Comment by mkrueger** [comment]
This is the old basic highlighting engine - there is a new one that is more sophisticated. 

IDocumentHighlighter - this moved out of editior features and is more complex but it's missing keyword highlighting so far.

**Pull request merged**
