### PR TITLE
Fixes VSTS Bug 972866: [Feedback] Preferences are not saved when I

### PR DESCRIPTION
**Pull request by mkrueger**
click OK in the Preferences menu in Visual Studio for Mac.

https://devdiv.visualstudio.com/DevDiv/_workitems/edit/972866

### CODE REVIEW

**Comment by sevoku** [comment]
@monojenkins backport release-8.3
@monojenkins backport release-8.2

**Comment by sevoku** [comment]
This fixes the issue, prefs are stored and reopen correctly, but I don't see any effect in the editor... @sandyarmstrong is that expected with the new editor?

**Comment by sandyarmstrong** [comment]
@sevoku yeah I think that's known. I don't have a bug URL handy though.

**Comment by sevoku** [comment]
@monojenkins backport release-8.2

**Pull request merged**
