### PR TITLE
Fix code completion in .xaml when code completion is triggered in mid…

### PR DESCRIPTION
**Pull request by DavidKarlas**
…dle of element name like `<Entr`

### CODE REVIEW

**Comment by mrward** [comment]
Can we create unit tests for this fix?

**Comment by slluis** [comment]
Yes please

**Comment by DavidKarlas** [comment]
There is unit test for this at https://github.com/xamarin/md-addins/blob/master/Xamarin.Forms.Addin.Tests/XamlCodeCompletion.cs#L344 but it's not enabled on wrench atm, I plan to this tomorrow...

**Comment by decriptor** [comment]
Since this affects all xml files should there be a more generic test?

**Comment by DavidKarlas** [comment]
@decriptor Unfortunately there is no unit tests in Xml addin for code completion since it would take a bit longer to set that up and since this case is already unit tested in Xamarin.Forms.Addin unit tests I opened bug so this is addressed in future https://bugzilla.xamarin.com/show_bug.cgi?id=58968

**Pull request merged**
