### PR TITLE
[Debugger] Prevent pinned watches from disappearing during scroll/etc

### PR DESCRIPTION
**Pull request by sandyarmstrong**
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/999608

### CODE REVIEW

**Comment by jstedfast** [comment]
Do the pinned watches collapse if you expand a pinned watch and then scroll? I'll give this a try in a bit once I finish the patch I'm working on atm.

**Comment by sandyarmstrong** [comment]
@jstedfast no, they do not collapse. What behavior do you want?

**Comment by jstedfast** [comment]
If they don't collapse on scroll, that is *perfecto*!

**Comment by sandyarmstrong** [comment]
Ok, cool. Fixed the other related issue I mentioned earlier, so I think this is done.

Perf can get stuttery when an expanded pinned watch scrolls back into view, but I think that can be addressed later.

Let me know if you have any other concerns!

**Comment by jstedfast** [comment]
I see what you mean by stuttering, but I agree, that can be solved later. Right now this is a huge improvement!

**Comment by sandyarmstrong** [comment]
@monojenkins backport release-8.4

**Pull request merged**
