### PR TITLE
Fixes VSTS Bug 709244: [Feedback] Cannot add .bat (Windows Batch

### PR DESCRIPTION
**Pull request by mkrueger**
files) to projects - VS Mac hangs indefinitely

https://devdiv.visualstudio.com/DevDiv/_workitems/edit/709244

### CODE REVIEW

**Comment by mrward** [comment]
Can we fix the text editor not being available to open .bat files? If I right click a .bat file in the Solution window for VS Mac 7.7 I see - Assembly Browser, Hex Editor and Visual Studio Code.app. With this fix the default editor would be the Hex Editor I guess?

**Comment by mkrueger** [comment]
It opens with source editor for me.

**Comment by mrward** [comment]
I debugged the code a bit. The mime type I get for the .bat file is `application/x-msdownload`. This does not match any mime types defined so the open with menu shows VS Code and the Hex Editor:

openwithbatfile

**Comment by slluis** [comment]
@mrward I see there is a check for application/x-msdownload. Is this fixed now?

**Comment by mkrueger** [comment]
@monojenkins backport release-7.7

**Pull request merged**
