### PR TITLE
Update Database add-in

### PR DESCRIPTION
**Pull request by inizan-yannick**
build driver with Npgsql NuGet package, and update files with new code.

### CODE REVIEW

**Comment by monoadmin** [comment]
Hello! I'm the build bot for the Mono project. I need approval from a Mono team member to build this pull request. A team member should reply with "approve" to approve a build of this pull request, "whitelist" to whitelist this and all future pull requests from this contributor, or "build" to explicitly request a build, even if one has already been done. Contributors can ignore this message.

**Comment by Therzok** [comment]
Hey! These addins now like under https://github.com/monodevelop. Can you push PRs there?

**Comment by inizan-yannick** [comment]
of course :)

**Comment by monoadmin** [comment]
Hello! I'm the build bot for the Mono project. I need approval from a Mono team member to build this pull request. A team member should reply with "approve" to approve a build of this pull request, "whitelist" to whitelist this and all future pull requests from this contributor, or "build" to explicitly request a build, even if one has already been done. Contributors can ignore this message.

**Comment by Therzok** [comment]
Yeah, Database is still here. Is the npgsql updated? I'd rather have it nugeted.
https://www.nuget.org/packages/Npgsql/

**Comment by inizan-yannick** [comment]
@Therzok it's ok, Npgsql & MySql.Data restored with NuGet

**Comment by slluis** [comment]
This PR can't be merged as is since the Vala add-in has been moved to https://github.com/monodevelop

**Comment by Therzok** [comment]
Please submit the fixes to the corresponding repositories.

**Pull request closed without merging**
