### PR TITLE
[A11y] Reset the user defaults before restarting the app

### PR DESCRIPTION
**Pull request by iainx**
NSUserDefaults seems to not want to synchronise when restarting the app, so reset it which seems to make it work.

Fixes BXC #59138

### CODE REVIEW

**Comment by Therzok** [comment]
Debug.WriteLine is NOP in release builds, lgtm!

**Comment by iainx** [comment]
Ok, think this fixes it.

**Comment by iainx** [comment]
QA have okayed this.

**Comment by slluis** [comment]
Ready to merge.

**Pull request merged**
