### PR TITLE
Bump FSharp.Core from 4.3.0 to 4.3.3

### PR DESCRIPTION
**Pull request by nosami**

### CODE REVIEW

**Comment by dsyme** [comment]
This PR looks fine

I took a glance over the templates and noticed:

* There is an NUnit template, but it is for NUnit 2.6.4.  We should modernize this

* There is a GTK template, but it is for GTK 2.0.  Should we modernize this, or delete it?

**Comment by nosami** [comment]
> There is an NUnit template, but it is for NUnit 2.6.4. We should modernize this
Will investigate. I know that we ship a custom NUnit with Mono, but not sure why

> There is a GTK template, but it is for GTK 2.0. Should we modernize this, or delete it?
Maybe !? Need to see what C# is using. MonoDevelop itself is based on 2.0 :)

**Comment by decriptor** [comment]
As far as I understand we should *not* be using the NUnit from mono.

**Comment by Therzok** [comment]
I'm seeing binding redirect failures on Windows.

```
csharp> Assembly.LoadFrom("FSharp.Core.dll")
FSharp.Core, Version=4.4.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
```

I don't think the version is 4.4.3.3?

**Pull request merged**
