### PR TITLE
Fixed 'Bug 41245 - Attribute code completion not showing all

### PR DESCRIPTION
**Pull request by mkrueger**
constructors and showing too many things'

### CODE REVIEW

**Comment by slluis** [comment]
@mkrueger hey, can you fix the conflicts?

**Comment by slluis** [comment]
@mkrueger hmm, why remove unit tests?

**Comment by mkrueger** [comment]
Because of the diff - it wasn't really readable in the editor - the unit test is in master.

**Comment by slluis** [comment]
I don't understand what you mean with the diff not being readable.

**Comment by mkrueger** [comment]
Hm, not sure that this was the case here - doesn't look like this is complex.
I had one case where the merge diff wasn't readable/junk and there it was easier to remove just the case alltogether.

The case is in master and it's not removed there - so not 100% sure about this commit here - it might be the unreadable case. But anyways the completion is case is checked in master and the engine is distinct enough so that it doesn't matter.

**Pull request merged**
