### PR TITLE
Bump vs-editor-api to 15.2.4-pre (16.0.142-g25b7188c54).

### PR DESCRIPTION
**Pull request by KirillOsenkov**

### CODE REVIEW

**Review by Therzok — APPROVED** [review]

**Comment by Therzok** [comment]
I'll build on top of this.

**Comment by KirillOsenkov** [comment]
Oh, yeah, I forgot to bump the rest of the editor nugets to the new 16.0.* version.

**Comment by KirillOsenkov** [comment]
Updated now.

**Comment by KirillOsenkov** [comment]
And made it build again.

**Comment by Therzok** [comment]
I've applied the patch-set on top of https://github.com/mono/monodevelop/tree/release-8.0-bump-roslyn

There's one new MEF error:
```
INFO [2018-12-09 18:40:56Z]: MEF composition error: Microsoft.VisualStudio.UI.Text.Commanding.Implementation.EditorCommandHandlerServiceFactory.ctor(statusBar): expected exactly 1 export of Microsoft.VisualStudio.Utilities.IStatusBarService but found 0.
```

For some reason, text does not have any highlighting applied.

**Comment by KirillOsenkov** [comment]
Should we implement and export an empty status bar provider?

**Comment by Therzok** [comment]
Not sure if that'll fix anything. #6739 has more info on what's going on in both vs and roslyn layers.

**Comment by Therzok** [comment]
Yeah, this PR is now obsolete, I integrated it into the roslyn bump branch (they need to happen in sync)

**Pull request closed without merging**
