### PR TITLE
Gtkrc a11y fixes

### PR DESCRIPTION
**Pull request by vancura**
These two commits fix color accessibility issues in these areas:

- Secondary (gray) text color now matches required 4.5:1.
- New macOS selection background which follows changes in macOS Mojave.

Fixes VSTS #612400
Fixes VSTS #754225

### CODE REVIEW

**Comment by slluis** [comment]
Can you references the bugs this fixes?

**Comment by vancura** [comment]
@slluis There is no bug. I found the problem while testing another thing.

**Comment by vancura** [comment]
Everything compiles nicely, this seems to be done.

**Comment by vancura** [comment]
@slluis Actually I just found a bug! They already filed the selection background color here: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/612400 — what should I do now so this gets propagated there?

**Pull request merged**
