### PR TITLE
Remove RefactoringEssentials

### PR DESCRIPTION
**Pull request by sandyarmstrong**
Many of these fixes are redundant with Roslyn or broken in C# 8.
Removing them increases consistency with Windows.

We can always restore any especially popular ones with an extension.

Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/893943

### CODE REVIEW

**Comment by sandyarmstrong** [comment]
Applying `do-not-merge` label because this is currently planned for 8.5 and don't want to merge it too early.

**Comment by Therzok** [comment]
:+1:

**Comment by Therzok** [comment]
Core failure seems like flakey test.

C# binding failure is integration test for old editor still having refactoringessentials diagnostics in the test code

**Comment by sandyarmstrong** [comment]
@Therzok interestingly there is a perf test failure that differs from HEAD of master branch:

```
2019-10-19T19:41:26.5503170Z Errors and Failures:
2019-10-19T19:41:26.5517680Z 1) Test Error : MonoDevelop.Ide.PerfTests.TestFileWatcherHandlers.TestHandlers
2019-10-19T19:41:26.5518270Z    System.TimeoutException : Timed out waiting for counter FileService.FilesRenamed
```

**Comment by Therzok** [comment]
That is interesting. It shouldn't happen. Lemme try a re-run

**Comment by Therzok** [comment]
Either we reduced the number of expected events or something else is screwed up. Thanks for bringing it up

**Comment by sandyarmstrong** [comment]
@Therzok looks like it's working fine now :)

**Comment by sandyarmstrong** [comment]
@monojenkins backport release-8.4

**Comment by Therzok** [comment]
There is a scenario where it could fail due to the OS dropping events, otherwise, I can't see why it would.

**Pull request merged**
