### PR TITLE
Icon updates

### PR DESCRIPTION
**Pull request by vancura**
A few changes to our current icons:

https://github.com/mono/monodevelop/commit/2a67482f9f326630b3b19f569375ba57189c9070
Here I cleaned up all the library icons.

https://github.com/mono/monodevelop/commit/df983813335e69b800774ca171e351e199ccac7a
.NET Core and .NET Standard now use the right icons and not dummy placeholders.

https://github.com/mono/monodevelop/commit/e3793f942c57e266fff6cd468841f334ebec4e6d
Some icons in Preferences didn't look right next to other icons with outline treatment (only in dark theme), this commit makes these icons outline too.

https://github.com/mono/monodevelop/commit/d3076636559843970d1274ea5037e5dfcd7c4e89
Tooltip invocation icons shouldn't use `md-information` but `md-help`, since the tooltip is a help and not static information. `md-information` should be still used on static always visible texts. This will continue in md-addins in a minute.

https://github.com/mono/monodevelop/pull/2405/commits/c0a9e0b91074fb26f875fe899aff9f74eab5ffa2
New information tooltip colors:

tmp

### CODE REVIEW

**Comment by vancura** [comment]
@slluis: Please don't merge yet, I found a bug in a tooltip color:

screen shot 2017-05-10 at 11 53 46

This should be green. I am on it.

**Comment by vancura** [comment]
@slluis @VincentDondain @mrward: Do you know who owns Xamarin.Forms templates? See the image above, that `&apos;` is not right is it :)

**Comment by mrward** [comment]
@vancura - There is a bug Vincent opened for the apos appearing in the tooltips - https://bugzilla.xamarin.com/show_bug.cgi?id=55746

**Comment by vancura** [comment]
@slluis: This PR is done.

**Comment by vancura** [comment]
@slluis Sorry, you're too fast. Could you also please merge the last commit? Sorry!

**Pull request merged**
