### PR TITLE
Icon changes

### PR DESCRIPTION
**Pull request by vancura**
As I am working on the new Property Pad, I'll have some icon changes. This PR is not done yet, please don't merge.

So far it contains these changes:

### Added icons and `md-` references:

- `md-palette`
- `md-style`
- `md-typography`
- `md-scroll`
- `md-widget`

### Minor icon updates:

- better proportions in `platform-macos` to sync with other platform icons,
- `sort-alphabetically` doesn't sport a container anymore, it's simpler now.

I'll update the PR as icons come.

### CODE REVIEW

**Comment by vancura** [comment]
@slluis: Do I need to merge master to this branch/PR or is it fine as it is?

**Comment by VincentDondain** [comment]
Build error seems unrelated:

```
Errors:
15:28:40 
15:28:40 /mnt/jenkins/workspace/test-monodevelop-pullrequest/main/Main.sln (default targets) ->
15:28:40 (Build target) ->
15:28:40 /mnt/jenkins/workspace/test-monodevelop-pullrequest/main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.Formats.MSBuild.dotnet.v14.1.csproj (default targets) ->
15:28:40 /usr/lib/mono/xbuild/14.0/bin/Microsoft.CSharp.targets (CoreCompile target) ->
15:28:40 
15:28:40 	MonoDevelop.Projects.Formats.MSBuild/BuildEngine.v4.0.cs(53,12): error CS1061: Type `Microsoft.Build.Evaluation.ProjectCollection' does not contain a definition for `SetGlobalProperty' and no extension method `SetGlobalProperty' of type `Microsoft.Build.Evaluation.ProjectCollection' could be found. Are you missing an assembly reference?
15:28:40 
15:28:40 	 101 Warning(s)
15:28:40 	 1 Error(s)
15:28:40 
15:28:40 Time Elapsed 00:00:53.8893860
```

**Comment by vancura** [comment]
@VincentDondain What's that?

**Comment by VincentDondain** [comment]
@vancura when you click on `Details` next to Linux x64.

You could have broken the builds with your icons for whatever reason but you didn't so I'm saying the error is unrelated to your changes.

aka seems good to merge.

**Comment by slluis** [comment]
It is fine.

De: Václav Vančura <notifications@github.com>
Responder a: mono/monodevelop <reply@reply.github.com>
Fecha: dijous, 9 de març de 2017 a les 17:17
Para: mono/monodevelop <monodevelop@noreply.github.com>
CC: Lluis Sanchez Gual <llsan@microsoft.com>, Mention <mention@noreply.github.com>
Asunto: Re: [mono/monodevelop] Icon changes (#1910)


@slluis<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fslluis&data=02%7C01%7Cllsan%40microsoft.com%7C86109972f5d64e4f8aaa08d46707de98%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636246730877228507&sdata=vRpE%2BuCh1R4xTVEKSaZYci%2FMuhl7dkR5OlZ%2B5zEI1XE%3D&reserved=0>: Do I need to merge master to this branch/PR or is it fine as it is?

**Pull request merged**
