### PR TITLE
T4 - use lowercased template directive names

### PR DESCRIPTION
**Pull request by mnaoumov**
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=28767

Recreated #847 to pull request on top of master

### CODE REVIEW

**Comment by mhutch** [comment]
IMO this would be cleaner to do where we resolve the directive names? That way the parsed document would still reflect the literal values of the document.

i.e. `switch (dt.Name.ToLowerInvariant ()) {`

https://github.com/mono/monodevelop/blob/master/main/src/addins/TextTemplating/Mono.TextTemplating/Mono.TextTemplating/TemplatingEngine.cs#L200

**Comment by mnaoumov** [comment]
@mhutch, if we follow the approach you suggested we'll have to modify in many other places where **Directive.Name** are used, e.g. https://github.com/mono/monodevelop/blob/master/main/src/addins/TextTemplating/Mono.TextTemplating/Mono.TextTemplating/ParsedTemplate.cs#L135, https://github.com/mono/monodevelop/blob/master/main/src/addins/TextTemplating/Mono.TextTemplating/Mono.TextTemplating/ParsedTemplate.cs#L156, https://github.com/mono/monodevelop/blob/master/main/src/addins/TextTemplating/Mono.TextTemplating/Mono.TextTemplating/TemplatingEngine.cs#L401 etc,  So the implementation I suggested seems to be the easiest one.

**Comment by mhutch** [comment]
I just don't like the idea that the AST won't match the actual text. This mean e.g. if we show a tooltip, the case will be wrong.

**Comment by mhutch** [comment]
I've implemented my version in https://github.com/mono/monodevelop/commit/3f673215d714d480084a971957e3c60bdb07f339

**Pull request closed without merging**
