### PR TITLE
Bump Roslyn and VSEditor

### PR DESCRIPTION
**Pull request by Therzok**
Roslyn is included for an IVT fix
Roslyn also bumped VSEditor

### CODE REVIEW

**Comment by Therzok** [comment]
Halt on this, we need a newer version of roslyn, as foreground affinized objects are discarding tasks on non-Windows.

**Comment by Therzok** [comment]
cc @KirillOsenkov

**Comment by KirillOsenkov** [comment]
Let's first merge this PR to bump WebTools: https://github.com/xamarin/md-addins/pull/3043

**Comment by KirillOsenkov** [comment]
We have two options that I can see: 
1. merge https://github.com/xamarin/md-addins/pull/3043
2. bump this PR to that commit of md-addins master
3. Wait for this build to go green and merge this PR

or:

1. update this PR to point to the bump-roslyn-ivt branch of md-addins
2. get a green build and merge this PR
3. merge the https://github.com/xamarin/md-addins/pull/3043
4. make another PR to switch monodevelop master back to md-addins master
5. wait for it to go green and merge

**Comment by KirillOsenkov** [comment]
@ToddGrun FYI

**Comment by KirillOsenkov** [comment]
@mrward Matt could you help with approving this?

**Pull request merged**
