### PR TITLE
Fixes VSTS Bug 960629: CommandSearchCategory potentially works on inv…

### PR DESCRIPTION
**Pull request by mkrueger**
…alid data

https://devdiv.visualstudio.com/DevDiv/_workitems/edit/960629

Removed the cache - that should now run on the main thread. But there are too few commands to justify a task there in any case.

### CODE REVIEW

**Comment by Therzok** [comment]
What I'm asking for is [change the replace call from get to set](http://source.monodevelop.com/#MonoDevelop.Ide/MonoDevelop.Components.Commands/Command.cs,138)

**Comment by mkrueger** [comment]
Commands should cache DisplayName if it's a problem. But in any case - how many commands we've ? Creating ~100 strings is in no way a problem for a computer program.

**Comment by Therzok** [comment]
@mkrueger we don't need both displayName and cachedDisplayName.

**Comment by Therzok** [comment]
using `mdtool extension-tool` and going to `/MonoDevelop/Ide/Commands`, I see 503 commands.

**Comment by sevoku** [comment]
@monojenkins backport release-8.3

**Pull request merged**
