### PR TITLE
Bump roslyn in 8.0

### PR DESCRIPTION
**Pull request by Therzok**
Still not working:
* Assembly browser links - they used to use cecil doc ids, we might some replacement, as SRM does not support getting docids out of the box
* Editor highlighting at all

Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/708415

### CODE REVIEW

**Comment by Therzok** [comment]
[This](https://github.com/mono/monodevelop/blob/fc57196ac640a33f8addbaf71f943b5434893e5a/main/src/addins/MonoDevelop.SourceEditor2/VSEditor/TagBasedSyntaxHighlighting.cs#L80) is always returning an empty list.

**Comment by Therzok** [comment]
Also, @KirillOsenkov it seems like multi-caret support is giving out of date snapshot issues.

**Comment by Therzok** [comment]
```
INFO [2018-12-09 20:27:32Z]: MEF composition error: Microsoft.VisualStudio.UI.Text.Commanding.Implementation.EditorCommandHandlerServiceFactory.ctor(statusBar): expected exactly 1 export of Microsoft.VisualStudio.Utilities.IStatusBarService but found 0.
INFO [2018-12-09 20:27:32Z]: MEF composition error: Microsoft.CodeAnalysis.Editor.Implementation.Peek.PeekableItemSourceProvider.ctor(peekResultFactory): expected exactly 1 export of Microsoft.VisualStudio.Language.Intellisense.IPeekResultFactory but found 0.
```

**Review by mkrueger — APPROVED** [review]

**Comment by Therzok** [comment]
```
2018-12-10T10:38:58.9168000Z [["Visual Studio (Preview).app/Contents/Resources/lib/monodevelop/AddIns/AspNet/System.Data.Common.dll",
2018-12-10T10:38:58.9168530Z   "Visual Studio (Preview).app/Contents/Resources/lib/monodevelop/AddIns/BackendBindings/System.Data.Common.dll",
2018-12-10T10:38:58.9169270Z   "Visual Studio (Preview).app/Contents/Resources/lib/monodevelop/AddIns/CSharpBinding/System.Data.Common.dll",
2018-12-10T10:38:58.9169540Z   "Visual Studio (Preview).app/Contents/Resources/lib/monodevelop/AddIns/DisplayBindings/AssemblyBrowser/System.Data.Common.dll",
2018-12-10T10:38:58.9169840Z   "Visual Studio (Preview).app/Contents/Resources/lib/monodevelop/AddIns/DisplayBindings/Gettext/System.Data.Common.dll",
2018-12-10T10:38:58.9170210Z   "Visual Studio (Preview).app/Contents/Resources/lib/monodevelop/AddIns/DisplayBindings/SourceEditor/System.Data.Common.dll",
2018-12-10T10:38:58.9170470Z   "Visual Studio (Preview).app/Contents/Resources/lib/monodevelop/AddIns/FSharpBinding/System.Data.Common.dll",
2018-12-10T10:38:58.9170670Z   "Visual Studio (Preview).app/Contents/Resources/lib/monodevelop/AddIns/MonoDevelop.ConnectedServices/System.Data.Common.dll",
2018-12-10T10:38:58.9170870Z   "Visual Studio (Preview).app/Contents/Resources/lib/monodevelop/AddIns/MonoDevelop.Debugger/System.Data.Common.dll",
2018-12-10T10:38:58.9171120Z   "Visual Studio (Preview).app/Contents/Resources/lib/monodevelop/AddIns/MonoDevelop.DesignerSupport/System.Data.Common.dll",
2018-12-10T10:38:58.9171330Z   "Visual Studio (Preview).app/Contents/Resources/lib/monodevelop/AddIns/MonoDevelop.GtkCore/System.Data.Common.dll",
2018-12-10T10:38:58.9171510Z   "Visual Studio (Preview).app/Contents/Resources/lib/monodevelop/AddIns/MonoDevelop.IPhone/System.Data.Common.dll",
2018-12-10T10:38:58.9171710Z   "Visual Studio (Preview).app/Contents/Resources/lib/monodevelop/AddIns/MonoDevelop.MacDev/System.Data.Common.dll",
2018-12-10T10:38:58.9171900Z   "Visual Studio (Preview).app/Contents/Resources/lib/monodevelop/AddIns/MonoDevelop.MonoDroid/System.Data.Common.dll",
2018-12-10T10:38:58.9172100Z   "Visual Studio (Preview).app/Contents/Resources/lib/monodevelop/AddIns/MonoDevelop.MonoMac/System.Data.Common.dll",
2018-12-10T10:38:58.9172290Z   "Visual Studio (Preview).app/Contents/Resources/lib/monodevelop/AddIns/MonoDevelop.Refactoring/System.Data.Common.dll",
2018-12-10T10:38:58.9172480Z   "Visual Studio (Preview).app/Contents/Resources/lib/monodevelop/AddIns/MonoDevelop.RegexToolkit/System.Data.Common.dll",
2018-12-10T10:38:58.9172690Z   "Visual Studio (Preview).app/Contents/Resources/lib/monodevelop/AddIns/MonoDevelop.TextTemplating/System.Data.Common.dll",
2018-12-10T10:38:58.9172880Z   "Visual Studio (Preview).app/Contents/Resources/lib/monodevelop/AddIns/VBNetBinding/System.Data.Common.dll",
2018-12-10T10:38:58.9173090Z   "Visual Studio (Preview).app/Contents/Resources/lib/monodevelop/AddIns/VersionControl/System.Data.Common.dll",
2018-12-10T10:38:58.9173290Z   "Visual Studio (Preview).app/Contents/Resources/lib/monodevelop/AddIns/Xamarin.Forms.Addin/System.Data.Common.dll",
2018-12-10T10:38:58.9173480Z   "Visual Studio (Preview).app/Contents/Resources/lib/monodevelop/AddIns/Xamarin.Ide/System.Data.Common.dll",
2018-12-10T10:38:58.9173650Z   "Visual Studio (Preview).app/Contents/Resources/lib/monodevelop/AddIns/Xml/System.Data.Common.dll",
2018-12-10T10:38:58.9173830Z   "Visual Studio (Preview).app/Contents/Resources/lib/monodevelop/bin/System.Data.Common.dll"],
```

I don't know what's going on.

**Comment by decriptor** [comment]
@Therzok I believe that multi targeting doesn't work in VSmac. It will build the first item in the list and that is it.

**Comment by Therzok** [comment]
Giving one more try with PrivateAssets set to true in RE.

**Comment by sandyarmstrong** [comment]
Looks like 2.11 is no longer a thing, and we need to go to 3.0 https://github.com/dotnet/versions/blob/master/build-info/dotnet/roslyn/dev16.0p2/Latest_Packages.txt.

**Pull request closed without merging**
