### PR TITLE
Remove old MEF and switch everything to VSMEF.

### PR DESCRIPTION
**Pull request by KirillOsenkov**

### CODE REVIEW

**Comment by KirillOsenkov** [comment]
We can't check this in until we have the new Mono with the latest runtime fixes. But I want to see if we can discover more issues that I haven't seen before.

**Comment by KirillOsenkov** [comment]
This is now ready to go in, please review.

**Comment by slluis** [comment]
I feel the basic MEF infrastructure be part of MD.Core, not MD.Ide

**Comment by Therzok** [comment]
I also agree with @slluis . This would allow for testing most of roslyn services under MD.Core.

**Comment by KirillOsenkov** [comment]
I agree, but I'd like to do it step by step. First, remove the old catalogs and plug in the new one. I'd like for this to go in and spend a few days dogfooding it.

Then, as a separate PR, I will move them from Ide to Core. Sounds good?

**Comment by Therzok** [comment]
Sounds good to me!

**Comment by KirillOsenkov** [comment]
Rebased on latest master.

**Pull request merged**
