### PR TITLE
[release-8.4] [VsCodeDebugger] various fixes

### PR DESCRIPTION
**Pull request by jstedfast**
Needed for https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1042237/
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1023874/
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1032065/
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1042217/
FIxes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1016662

Backport of https://github.com/mono/monodevelop/pull/9513

### CODE REVIEW

**Comment by sgmunn** [comment]
@monojenkins rebase

**Comment by sgmunn** [comment]
@monojenkins rebase

**Comment by sgmunn** [comment]
relevant test case - https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1049919

**Comment by therealjohn** [comment]
I've verified this with 8.4.1.6

**Pull request merged**
