### PR TITLE
Added initial gnome-terminal-server support for gnome 3

### PR DESCRIPTION
**Pull request by gliwka**
Fix for bug 16804
https://bugzilla.xamarin.com/show_bug.cgi?id=16804

### CODE REVIEW

**Comment by slluis** [comment]
approve

**Comment by ircecho** [comment]
I tested this and it is not working. Reason is, that the gnome-terminal-server is located at "/usr/libexec/gnome-terminal-server" instead of the path you used. I am using GNOME Terminal 3.14.2 on Fedora 20, but this does not seem to be specific to Fedora (see https://wiki.gnome.org/Apps/Terminal/Debugging#Running_a_separate_instance).

Other than that, the patch is working. I fixed the path and now running in gnome-terminal is working perfectly.

**Comment by Therzok** [comment]
I'm up for merging this.

**Comment by slluis** [comment]
But what's then the correct location of gnome-terminal-server?

**Comment by Therzok** [comment]
Looking at the Gnome docs, it seems to be

`/usr/libexec/gnome-terminal-server`

https://wiki.gnome.org/Apps/Terminal/Debugging

**Comment by gliwka** [comment]
I've looked into it and have found two possible paths:
/usr/lib/gnome-terminal/gnome-terminal-server (found in Arch Linux, Debian, OpenSUSE and most other distributions)
/usr/libexec/gnome-terminal-server (found in Fedora and derivates)

**Comment by slluis** [comment]
@Therzok can you verify this works?

**Comment by mkrueger** [comment]
Couldn't merge the pull request - manually ported it over.

@gliwka thanks - y you're right that's the only way it can now work with the gnome terminal.

new PR:

https://github.com/mono/monodevelop/pull/2574

**Pull request closed without merging**
