### PR TITLE
Removing obsolete solution pad tree popup button

### PR DESCRIPTION
**Pull request by vancura**
After a discussion in Boston last month we decided to remove the solution pad tree popup button, as it's not needed anymore. Here's the removal.

### CODE REVIEW

**Comment by DavidKarlas** [comment]
Out of curiosity... What changed to go from useful to obsolete?

**Comment by vancura** [comment]
It duplicated right click behavior and it was very non-standard (I don't recall any other case if a similar button in any application I've ever seen except MS DOS 3D Studio, do you know about any?)

**Comment by vancura** [comment]
Also, did you use it? How often?

**Comment by DavidKarlas** [comment]
Sometimes, not sure why... I guess my question is, why it was added/useful? :)

**Comment by vancura** [comment]
It was in md since ever. No idea who has designed it.

**Comment by vancura** [comment]
I guess it made much more sense when Macs had only one mouse button:)

**Comment by vancura** [comment]
@sevoku is right, this shouldn't be based on dark skin. Once @slluis approves the PR (if he approves), I'll cherry pick it to master.

**Comment by slluis** [comment]
Let's do this in dark-skin only for now

**Comment by vancura** [comment]
OK.

**Comment by Therzok** [comment]
:+1:

**Pull request merged**
