### PR TITLE
Attempt to fix flakey leak test that happens due to not waiting for t…

### PR DESCRIPTION
**Pull request by Therzok**
…he save and close operations to finish

Fixes VSTS #1006925 - Leak test random failure due to flakey test

### CODE REVIEW

**Comment by Therzok** [comment]
@monojenkins backport release-8.4

**Comment by Therzok** [comment]
@monojenkins rebase

**Comment by Therzok** [comment]
@monojenkins backport release-8.4

**Comment by Therzok** [comment]
@monojenkins backport release-8.4

**Comment by Therzok** [comment]
@monojenkins backport release-8.4

**Comment by jtorres** [comment]
@monojenkins backport release-8.4-preview1

**Pull request merged**
