### PR TITLE
[CSharpBinding] Allow choosing C# 8

### PR DESCRIPTION
**Pull request by sandyarmstrong**
Remove `CSharp8` and `LatestMajor` from unsupported list.

Fixes https://devdiv.visualstudio.com/DevDiv/_workItems/edit/916849

### CODE REVIEW

**Comment by sandyarmstrong** [comment]
@monojenkins backport release-8.2

**Comment by abock** [comment]
Opened the explicit backport because `master` seems to be too much in flux and we want a CI build that works to verify.

**Comment by mrward** [comment]
I guess we have no plans to support this conditionally based on the Mono version?

**Comment by Therzok** [comment]
_is comtemplating bumping minimum mono version to 6.x_

**Comment by slluis** [comment]
@monojenkins backport release-8.2-preview1

**Comment by sandyarmstrong** [comment]
@mrward I think that's a lovely idea, but probably requires more discussion. One concern is adding support for a Mono version that we will never dogfood with.

**Pull request merged**
