### PR TITLE
[WelcomePage] Show it when the app goes idle

### PR DESCRIPTION
**Pull request by Therzok**
Do not trigger showing the welcome page until the app is idle,
so as to not load the welcome page when a solution is passed to the app.

This improves startup time for solutions/documents loaded from finder

Fixes VSTS #652347 - Welcome page should not show when loading a solution from finder

### CODE REVIEW

**Comment by Therzok** [comment]
There is a really small flicker of the workbench until the welcome page shows now. I'm wondering if we should show nothing until the app is idle.

**Comment by slluis** [comment]
We should avoid this flicker. Can you try delaying the show of the window?

**Comment by Therzok** [comment]
I'll look into it.

**Comment by slluis** [comment]
What I see now is that the app icon stops bouncing, stays idle for 2 or 3 seconds and then the window shows up. It should be bouncing until the window is shown.

**Comment by Therzok** [comment]
Hmmm, need to figure out how to eliminate that, it might be the DispatchPendingEvents.

**Comment by Therzok** [comment]
Fixed.

**Comment by Therzok** [comment]
Fixed whitespace damage

**Comment by slluis** [comment]
I don't see that bouncing pause any more. However, the original issue is not fixed. If I open a solution from finder the Welcome Page is still loaded.

**Comment by Therzok** [comment]
Yes, it is, but it is loaded after the project starts loading. So that means we don't delay project load by showing the welcome page, we show it _after_ the project load started.

**Pull request merged**
