### PR TITLE
Fixed 'Bug 57392 - ctor code snippet is producing an nameless

### PR DESCRIPTION
**Pull request by mkrueger**
constructor'

We should consider replacing our code template system with the VS.NET
one or rework the system.

### CODE REVIEW

**Comment by DavidKarlas** [comment]
Shouldn't `.WaitAndGetResult (default (CancellationToken));` just be `.Result;`?

We should consider removing(marking obsolete) `DocumentContext.ParsedDocument` if it's not reliable and move code to `await GetSemanticModelAsync`...

Afaik `GetSemanticModelAsync` never accesses UI thread and always call `.ConfigureAwait(false);`, so this `.Result;` should harmless.

If Roslyn has counterpart for this code and we really have plan to replace this with Roslyn logic, I guess `.Result;` is OK for now...

/cc: @slluis can you approve this?

**Comment by mkrueger** [comment]
.Result is harmless here - right. The WaitAndGetResult () is a pattern from roslyn which I took - they're using it this way.

**Comment by DavidKarlas** [comment]
Is this called from UI thread? In that case it can be multiple seconds beachball... I guess still better then current bug...

**Comment by mkrueger** [comment]
multiple seconds is only possible before the project is loaded - the get semantic call is usually way faster than 'seconds'. But y better than the current bug and for template expansion there is no other way than delay atm :/

**Comment by Therzok** [comment]
Yes, GetSemanticModelAsync is instant in most cases.

**Pull request merged**
