### PR TITLE
[Core] Fix NRE in writing ProjectReference of SharedAssetProject

### PR DESCRIPTION
**Pull request by Therzok**
Fixes VSTS #656296 - [Feedback] VSfM Version 7.6 Preview (7.6 build 2003) crashes while building solution

### CODE REVIEW

**Comment by mrward** [comment]
This fixes the null reference exception in the IDE log. The bug itself seems to be the remote msbuild host crash that is fixed here - https://github.com/mono/monodevelop/pull/5780 - so this is to fix the null ref exception but not the remote host crash? Was confused since I could not see how this could fix the msbuild remote host crash. Just wondering if a comment on the bug report is needed?

**Comment by Therzok** [comment]
Yeah, it does not fix the builder crash, but we should be able to recover here in case of a crash (null owner project). The other code surrounding this does do a null check for owner project.

**Review by mrward — APPROVED** [review]
OK. 👍 

I think this was confusing QA since they were expecting it to fix the remote msbuild host crash since it links to that bug.

**Comment by Therzok** [comment]
I'm wondering whether this would mask bugs though.

**Comment by Therzok** [comment]
Closing. Seems to be caused by builder carsh.

**Pull request closed without merging**
