### PR TITLE
[release-8.4] Update translations

### PR DESCRIPTION
**Pull request by rodrmoya**

### CODE REVIEW

**Comment by rodrmoya** [comment]
@monojenkins backport master

**Comment by rodrmoya** [comment]
> @rodrmoya : There are #fuzzy entries. Shouldn't that be removed for translation to work.

where? I only see them on the strings that didn't have a translation

**Comment by GouriKumari** [comment]
https://github.com/mono/monodevelop/pull/9383/commits/45e623398fd0f289a2ec92fbfcb8f2bc1ebaebd6#diff-1323adf7e0c2f648e685a4671834b3ffR1645.  Many with translations also have the fuzzy string.

**Comment by rodrmoya** [comment]
> [45e6233#diff-1323adf7e0c2f648e685a4671834b3ffR1645](https://github.com/mono/monodevelop/commit/45e623398fd0f289a2ec92fbfcb8f2bc1ebaebd6#diff-1323adf7e0c2f648e685a4671834b3ffR1645). Many with translations also have the fuzzy string. Translators add it if they are not sure about the translation.

Yeah, in that ca.po there are a few of them, because we don't get translations for that language, so should be ok

**Pull request merged**
