### PR TITLE
Fixed 'Bug 57594 - Numbers syntax highlighted in namespace names,

### PR DESCRIPTION
**Pull request by mkrueger**
method names and property names'

### CODE REVIEW

**Comment by slluis** [comment]
Shouldn't this be fixed upstream?

**Comment by mkrueger** [comment]
Which upstream ? We >are< upstream :)

**Comment by slluis** [comment]
I thought we get this from somewhere else, I guess I got confused.

**Comment by mkrueger** [comment]
Ah we're not using the 'official' textmate grammar. It's too slow for us atm - it's replicating the c# grammar to get syntax info out of the text mate engine. We're already have roslyn for that.

**Pull request merged**
