### PR TITLE
xUnit.net support

### PR DESCRIPTION
**Pull request by x2bool**

### CODE REVIEW

**Comment by jchannon** [comment]
not merged?

**Comment by bratsche** [comment]
It looks like he deleted his repository for some reason.

**Comment by decriptor** [comment]
I'm not sure what's going on, but he posted to the ML just two days ago.
http://lists.ximian.com/pipermail/mono-list/2015-January/051503.html

**Comment by akoeplinger** [comment]
Seems there's now a repository at https://github.com/xunit/xamarinstudio.xunit to which @x2bool pushed lately. I'm curious what's going on here? :smile:

**Comment by jchannon** [comment]
I think he got fed up to be honest

**Comment by akoeplinger** [comment]
Ah, looks like that is the reason: https://github.com/xunit/xunit/issues/258#issuecomment-72827558

> The thing is that after few months of trying to push my changes to the official MonoDevelop repository, I had to give up on this. I don't know why the maintainers didn't want to merge my pull request (They are either too busy or not interested anymore). I had some people emailing me about bugs, improvement requests, etc. And I couldn't do anything about bugs until the PR is merged, so I decided to close it.

**Pull request closed without merging**
