### PR TITLE
Master optimize drawing

### PR DESCRIPTION
**Pull request by mkrueger**
Found 2 problems:

+ Tag based syntax highlighting always updates on text change 
+ Analysis Markers don't reuse objects and creates a lot of allocations and markers. Reusing markers helps a lot every add/remove causes redrawing.  

This PR only reuses the markers before the text change - however markers beyond the text change could be reused as well but I need more time implementing that - I'll update on this PR.

### CODE REVIEW

**Comment by mkrueger** [comment]
Ok should work now. That'll help improving typing speed a lot.

**Comment by mkrueger** [comment]
@monojenkins backport release-7.7

**Comment by Therzok** [comment]
Tested it, looks more fluid to me.

**Comment by Therzok** [comment]
Removing verified.

```
Parameter name: index
  at System.Collections.Generic.List`1[T].get_Item (System.Int32 index) [0x00009] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-08/external/bockbuild/builds/mono-x64/external/corefx/src/Common/src/CoreLib/System/Collections/Generic/List.cs:161 
  at MonoDevelop.AnalysisCore.Gui.ResultsEditorExtension+ResultsUpdater.IdleHandler () [0x00189] in /Users/therzok/Work/md/monodevelop/main/src/addins/MonoDevelop.Refactoring/MonoDevelop.AnalysisCore/Gui/ResultsEditorExtension.cs:372 
  at GLib.Idle+IdleProxy.Invoke () [0x00007] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-08/external/bockbuild/builds/gtk-sharp-None/glib/Idle.cs:49 
  at GLib.SourceProxy.HandlerInternal (System.IntPtr data) [0x00017] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-08/external/bockbuild/builds/gtk-sharp-None/glib/Source.cs:48 
```

Not sure how to get into this state.

**Comment by Therzok** [comment]
Works for me!

**Pull request merged**
