### PR TITLE
Kill warnings

### PR DESCRIPTION
**Pull request by knocte**

### CODE REVIEW

**Comment by DavidKarlas** [comment]
I would prefer if this was done/merged after Roslyn branch merge into master. Because it can be pain to merge this changes when so many files moved, deleted and changed.

**Comment by knocte** [comment]
> I would prefer if this was done/merged after Roslyn branch merge into master.

Sure. Is that going to happen soon?

**Comment by DavidKarlas** [comment]
My guess is somewhere in April.

**Comment by knocte** [comment]
Cool thanks.

**Comment by Therzok** [comment]
@knocte another quick solution would be to rebase this on top of roslyn and merge it there directly.

**Comment by slluis** [comment]
This needs to be rebased on the roslyn branch.

**Pull request closed without merging**
