### PR TITLE
Fix 822175: Exception adornment scrolled outside of view

### PR DESCRIPTION
**Pull request by DavidKarlas**
Only reasonable fix is to follow VS Windows way of displaying it as window because things get tricky with wrapped view where you can't just expand text view scrollable width...

Fixes VSTS #822175
Fixes VSTS #1025880

### CODE REVIEW

**Comment by abock** [comment]
@DavidKarlas can you provide a screenshot of the window now?

**Comment by DavidKarlas** [comment]
image

**Comment by abock** [comment]
I'd like to play around with the new window styling next week; this isn't urgent to land for 8.1 so we will just take it in 8.2 with window styling that is consistent with the other popovers in the editor.

**Comment by Therzok** [comment]
Do we still want to merge this PR?

**Comment by netonjm** [comment]
gPdciYqRSz

LGTM!

**Comment by netonjm** [comment]
@monojenkins backport release-8.5

**Comment by sevoku** [comment]
@monojenkins backport release-8.4-a11y

**Comment by sevoku** [comment]
@monojenkins backport release-8.4-a11y

**Pull request merged**
