### PR TITLE
Fix 1002331: Support "Focus Document" commands in new editor

### PR DESCRIPTION
**Pull request by DavidKarlas**

### CODE REVIEW

**Comment by DavidKarlas** [comment]
@monojenkins backport release-8.4

**Comment by mrward** [comment]
Leak test failure is unrelated.

**Comment by sandyarmstrong** [comment]
@mrward new editor doesn't have pulse yet. When I tested earlier, I saw pulsing still works in old editor.

**Comment by mrward** [comment]
Yeah, could not get the pulse to work in the old editor. Not sure why.

**Comment by sandyarmstrong** [comment]
@mrward do you have animations disabled? (Text Editor -> Markers and Rulers -> Enable animations)

**Comment by mrward** [comment]
Animations are enabled for me.

**Pull request merged**
