### PR TITLE
LibGit2 as the git backend

### PR DESCRIPTION
**Pull request by Therzok**

### CODE REVIEW

**Comment by Therzok** [comment]
build

**Comment by Therzok** [comment]
build

**Comment by Therzok** [comment]
build

**Comment by Therzok** [comment]
build

**Comment by directhex** [comment]
build

**Comment by directhex** [comment]
build

**Comment by directhex** [comment]
build

**Comment by directhex** [comment]
build

**Comment by directhex** [comment]
build

**Comment by directhex** [comment]
build

**Comment by directhex** [comment]
build

**Comment by Therzok** [comment]
build

**Comment by Therzok** [comment]
;_; commit not found.

**Comment by Therzok** [comment]
build

**Comment by directhex** [comment]
build

**Comment by directhex** [comment]
build

**Comment by Therzok** [comment]
build

**Comment by Therzok** [comment]
build

**Comment by Therzok** [comment]
@directhex ok, the build seems to succeed, it's just failing at setting the status.

**Comment by Therzok** [comment]
build

**Comment by Therzok** [comment]
How can I force it to run on i386 bot?

**Comment by Therzok** [comment]
build

**Comment by Therzok** [comment]
build

**Comment by Therzok** [comment]
mergey mergey!

**Pull request merged**
