### PR TITLE
[Ide][Mac] Use system font.

### PR DESCRIPTION
**Pull request by bratsche**

### CODE REVIEW

**Comment by slluis** [comment]
What will happen if the installed GTK doesn't have your patches?

**Comment by sevoku** [comment]
It will run with the default Sans font then (instead of Helvetica Neue or the new SF fonts)

**Comment by bratsche** [comment]
Yes, that's right. It will fall back to Sans in that case.

**Comment by slluis** [comment]
Ok, let's wait for the Mono patch to be merged, and bump the Mono dependency.

**Comment by bratsche** [comment]
bockbuild branch has been merged

**Pull request merged**
