### PR TITLE
Icons: Map md-reference to KnownImageIds.Reference

### PR DESCRIPTION
**Pull request by sailro**
On Windows:
image

On Mac:
image

md-reference image:
image

KnownImageId.Reference image:
image

Id:
image

### CODE REVIEW

**Comment by sailro** [comment]
cc @jbevain

**Comment by sandyarmstrong** [comment]
@sailro do you want this for `release-8.3` too?

**Comment by sailro** [comment]
> @sailro do you want this for `release-8.3` too?

If we are still on schedule why not, else no rush.

I have no write access, so I need someone to merge this one.

**Comment by sandyarmstrong** [comment]
@monojenkins backport release-8.3

**Comment by sailro** [comment]
Thanks @sandyarmstrong !

**Pull request merged**
