### PR TITLE
[Debugger] Added “Help link” to exception dialog and navigation on click

### PR DESCRIPTION
**Pull request by DavidKarlas**
Before merging this, https://github.com/mono/debugger-libs/pull/98 needs merging and bumping

@vancura can you review this screenshots if I placed "Help link:" correctly and if colors are OK.

Inside editor popup:
image

With inner exception:
image

Without inner exception:
image

### CODE REVIEW

**Comment by DavidKarlas** [comment]
New UI screenshots:
image

image

**Comment by vancura** [comment]
"More information" link is fine (I mean text), but color is definitely wrong, the contrast between background and text color is just way too low. Could you please make the text and underline white?

**Comment by DavidKarlas** [comment]
Updated screenshot:
image

**Comment by DavidKarlas** [comment]
@slluis this looks OK now? Can we merge?

**Comment by slluis** [comment]
This branch doesn't build because it is referencing an old debugger-libs. Can you please bump the reference?

**Comment by DavidKarlas** [comment]
Since this PR has debugger-libs bump and useless commits I'm opening new PR

**Pull request closed without merging**
