### PR TITLE
[Ide]Configure 'Rename' operation

### PR DESCRIPTION
**Pull request by gitexperience**

### CODE REVIEW

**Comment by gitexperience** [comment]
Done with static variable , if this PR is looking complex, i can create a new one , if you want..

**Comment by Therzok** [comment]
Heya!

Can you:

```
git rebase -f master --whitespace=fix
git push --force <my_remote> patch-11
```

**Comment by Therzok** [comment]
Actually, lemme do that. :)

**Comment by Therzok** [comment]
I've applied a bit of a different fix in master. :)

**Comment by gitexperience** [comment]
Thanks!! looking awesome!! :)  .,

**Pull request closed without merging**
