### PR TITLE
Reorder buttons for folder delete dialog

### PR DESCRIPTION
**Pull request by PiotrZierhoffer**
The order of buttons was different to the one in file removal dialog, which was confusing.

### CODE REVIEW

**Comment by Therzok** [comment]
:+1:

**Comment by slluis** [comment]
Cancel between delete and remove? that looks weird.

**Comment by Therzok** [comment]
Oh, missed that. @slluis so we want, cancel, remove, delete?

**Comment by PiotrZierhoffer** [comment]
Well, I went with the order from the more general (in my opinion) approach, in `ProjectFileNodeBuilder`. That is where the inconsistency arises. There is "Delete -> Cancel -> Remove from project" order there... So maybe it should be fixed as well?

**Comment by Therzok** [comment]
:+1: from me

**Comment by iainx** [comment]
Surely this is the Gtk+/OS X way, the more dangerous "extra" option to the left of the dialog

[Delete]                             [Cancel] [Remove from Project]

screen shot 2015-09-08 at 22 53 19

vs 

screen shot 2015-09-08 at 22 53 52

I think the [Delete] button should be moved further out.

**Comment by Therzok** [comment]
QuestionMessage doesn't support it, sadly. We'd need it to support it.

**Pull request closed without merging**
