### PR TITLE
[Ide] display message when directory selected in "Add files from folder....

### PR DESCRIPTION
**Pull request by loganek**
....." action

This patch fixes bug: https://bugzilla.xamarin.com/show_bug.cgi?id=20291

### CODE REVIEW

**Comment by monoadmin** [comment]
Hello! I'm the build bot for the Mono project. I need approval from a Mono team member to build this pull request. A team member should reply with "approve" to approve a build of this pull request, "whitelist" to whitelist this and all future pull requests from this contributor, or "build" to explicitly request a build, even if one has already been done. Contributors can ignore this message.

**Comment by Therzok** [comment]
:+1:

**Comment by loganek** [comment]
@knocte right. Improvement here: https://github.com/mono/monodevelop/pull/779

**Comment by knocte** [comment]
But in that PR it is said that this PR is better...

BTW you don't need to close a PR in order to improve it. You can make changes to your local commits in your local branch, and push with force (-f), and the new commits will be reflected here.

**Pull request closed without merging**
