### PR TITLE
[Git] Fix FileService discarding events due to imbalanced freeze/thaw

### PR DESCRIPTION
**Pull request by Therzok**
Fixes VSTS #983894 - Switching branches doesn't respect target framework changes
Fixes VSTS #984213 - FileWatcher sometimes stops raising events, causing files to stop reloading when external changes occur

### CODE REVIEW

**Comment by Therzok** [comment]
@monojenkins backport release-8.3

**Comment by Therzok** [comment]
@monojenkins backport release-8.3

**Comment by slluis** [comment]
@monojenkins backport release-8.3-rtw

**Comment by slluis** [comment]
@monojenkins backport release-8.3

**Pull request merged**
