### PR TITLE
[Ide] Reduce concurrency on RecentFiles modifications.

### PR DESCRIPTION
**Pull request by Therzok**

### CODE REVIEW

**Comment by Therzok** [comment]
Setting as WIP as there are a few changes I want to make:
* Better docs
* Applying changes to `cachedItemList` instantly so we can return whether the list was modified or not.
* Fix the saving to _not_ happen on the UI thread.
* Slightly optimize the `localModifyList` construction to ref-change + new empty list.

**Comment by alanmcgovern** [comment]
We should try not to leak exceptions too.  There are a couple of places where we don't await tasks in the new impl and those tasks may end up holding an exception, for example if `AcquireFileExclusive` the continuation in the constructor will error out and show up as unhandled in the logs.

**Comment by Therzok** [comment]
@alanmcgovern Can you take a look at this version?

**Comment by Therzok** [comment]
Signed off by @alanmcgovern , merging!

**Pull request merged**
