### PR TITLE
MSBuild uses better GC configuration.

### PR DESCRIPTION
**Pull request by Therzok**

### CODE REVIEW

**Comment by Therzok** [comment]
Results are inconclusive. Not sure if there's any big gain - but test applications might be small enough to not be affected by this change.

**Comment by Therzok** [comment]
Maybe this is why?
https://github.com/mono/mono/blob/c5b88ec4f323f2bdb7c7d0a595ece28dae66579c/scripts/xbuild.in#L2

**Comment by Therzok** [comment]
```
➜  main git:(sample-profiler) cat /Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild
#!/bin/sh
MONO_GC_PARAMS="nursery-size=64m,$MONO_GC_PARAMS" exec /Library/Frameworks/Mono.framework/Versions/5.18.1/bin/mono $MONO_OPTIONS /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin/MSBuild.dll "$@"
```

YEP. Only the msbuild builder should be affected.

**Comment by Therzok** [comment]
Gains of a few seconds across test runs, it should be good to go.

**Comment by Therzok** [comment]
DotNetCore tests are behaving differently, but not sure what's causing that.

**Comment by Therzok** [comment]
Overall, actual test times improved - downloading the drop is taking longer in this branch than master.

**Review by slluis — APPROVED** [review]

**Review by mrward — APPROVED** [review]

**Pull request merged**
