### PR TITLE
[Git] Fix monitor writes not being done on the UI thread

### PR DESCRIPTION
**Pull request by Therzok**
Fixes VSTS #611145 - Git apply stash - Gtk warning - operation done on background thread

### CODE REVIEW

**Comment by slluis** [comment]
In general progress monitors should be thread safe.

**Comment by Therzok** [comment]
Pushed another attempt, that also fixes #4734

**Comment by Therzok** [comment]
Hmmm, I can unit test this, give me a bit

**Comment by Therzok** [comment]
Added unit tests and also made overrides for all the methods that `TextWriter` routes into:
https://github.com/mono/mono/blob/master/mcs/class/referencesource/mscorlib/system/io/textwriter.cs#L49-L94

The current problem is that `Dispose` is not called on the right context.

`public virtual void Dispose` does not allow for this.

Consider breaking API when possible to make it `protected virtual void OnDisposed`, so we can call it on the right sync context.

**Comment by Therzok** [comment]
Added unit tests. @slluis please take another look

**Pull request merged**
