### PR TITLE
Switch AssemblyBrowser to use latest ICSharpCode.Decompiler

### PR DESCRIPTION
**Pull request by KirillOsenkov**
This change is needed because Roslyn that we use in d15-6 and master has a dependency on ICSharpCode.Decompiler 3.0.0.3403-beta4. Since we have our own older fork of ICSharpCode.Decompiler, Roslyn was not binary compatible with our version.

This change removes our copy of ICSharpCode.Decompiler from the solution and switches to use the version from NuGet. Since there have been significant changes to the public API I've had to accommodate for them.

We lose the ability to decompile into Summary mode (no method bodies). Issue https://github.com/icsharpcode/ILSpy/issues/1032 is tracking adding that back.

We have to use Reflection in one place to get the Cecil object from an unresolved Type System object. Bug https://github.com/icsharpcode/ILSpy/issues/1028 has added a public API and when we update to a newer version of ILSpy we'll remove reflection usage in favor of that new public API.

I've tried to keep the changes minimal so that we can port this to d15-6.

We can remove our copy of ICSharpCode.Decompiler source, as well as NRefactory, in subsequent checkins in master branch. I want to minimize changes that will go to d15-6, and it's non-essential to remove the code from the repo to ship. Additionally, it's nice to keep the old code for a little while, in case I've introduced regressions, so we can verify and fix.

### CODE REVIEW

**Comment by KirillOsenkov** [comment]
BinaryCompatChecker confirms that this fixes the issues:

```
https://wrench.internalx.com/Wrench/WebServices/Download.aspx?workfile_id=19869347

  These expected lines are missing:
  In assembly 'Microsoft.CodeAnalysis.EditorFeatures, Version=2.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35': Unable to resolve member reference 'System.String ICSharpCode.Decompiler.CSharp.CSharpDecompiler::DecompileTypeAsString(ICSharpCode.Decompiler.TypeSystem.FullTypeName)' from assembly 'ICSharpCode.Decompiler, Version=3.0.0.3403, Culture=neutral, PublicKeyToken=d4bfe873e7598c49'
  In assembly 'Microsoft.CodeAnalysis.EditorFeatures, Version=2.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35': Unable to resolve member reference 'System.Void ICSharpCode.Decompiler.CSharp.CSharpDecompiler::.ctor(Mono.Cecil.ModuleDefinition,ICSharpCode.Decompiler.DecompilerSettings)' from assembly 'ICSharpCode.Decompiler, Version=3.0.0.3403, Culture=neutral, PublicKeyToken=d4bfe873e7598c49'
  In assembly 'Microsoft.CodeAnalysis.EditorFeatures, Version=2.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35': Unable to resolve member reference 'System.Void ICSharpCode.Decompiler.TypeSystem.FullTypeName::.ctor(System.String)' from assembly 'ICSharpCode.Decompiler, Version=3.0.0.3403, Culture=neutral, PublicKeyToken=d4bfe873e7598c49'
  In assembly 'Microsoft.CodeAnalysis.EditorFeatures, Version=2.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35': Unable to resolve type reference 'ICSharpCode.Decompiler.CSharp.CSharpDecompiler' in 'ICSharpCode.Decompiler, Version=0.0.0.0, Culture=neutral, PublicKeyToken=d4bfe873e7598c49'
  In assembly 'Microsoft.CodeAnalysis.EditorFeatures, Version=2.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35': Unable to resolve type reference 'ICSharpCode.Decompiler.TypeSystem.FullTypeName' in 'ICSharpCode.Decompiler, Version=0.0.0.0, Culture=neutral, PublicKeyToken=d4bfe873e7598c49'
```

**Comment by slluis** [comment]
I'm wondering, is this a real compatibility problem if the assembly is strong named?

**Comment by mkrueger** [comment]
Assembly browser contains no API so it shouldn't be a problem.

**Comment by KirillOsenkov** [comment]
I've found an easy way to remove method bodies in Summary mode by using a Visitor. How's it looking now?

**Comment by KirillOsenkov** [comment]
@slluis I've opened a different PR against d15-6: https://github.com/mono/monodevelop/pull/3692
It still preserves the current implementation, but makes sure it can load side-by-side with the new one. The new one goes to `build\bin`, the current one goes to `build\AddIns\DisplayBindings\AssemblyBrowser`.

Is this PR OK to be merged to master? Just wanted to confirm just in case.

**Comment by Therzok** [comment]
This should be QA'd before going in.

**Comment by KirillOsenkov** [comment]
@manish how do we get this QA'ed? Anything I can do to help?

**Comment by parasAmbhore** [comment]
Hello Team,

We have tested this feature, kindly find below updates on this

Test build :
https://devdiv.visualstudio.com/_apis/resources/Containers/1667335?itemPath=drop%2FVisualStudioForMac-Preview-7.5.0.192.dmg

build info :
=== Visual Studio Enterprise 2017 for Mac (Preview) ===
Version 7.5 Preview (7.5 build 192)

Mono 5.8.0.129 (2017-10/835a98d8559) (64-bit)
=== Apple Developer Tools ===

Xcode 9.2 (13772)
Build 9C40b
=== Xamarin.Mac ===
Version: 4.2.0.20 (Visual Studio Enterprise)
=== Xamarin.iOS ===
Version: 11.8.0.20 (Visual Studio Enterprise)
=== Xamarin.Android ===
Version: 8.2.0.15 (Visual Studio Enterprise)
Operating System 
Mac OS X 10.12.6
Complete info : https://gist.github.com/parasAmbhore/a97f3d6c04e5fdaff6d8a56a9748a1a2
The updated version of ”ICSharpCode.Decompiler " was shown , screen-cast 
“ : https://www.screencast.com/t/r8eDwexfHa

We have tested the basic functionality of Assembly browser too, 
Test plan : 
https://xqa-testrail.eastus.cloudapp.azure.com/index.php?/plans/view/54741

As no feature blocking issues are observed, marking this card as “QA-Approved”

**Comment by KirillOsenkov** [comment]
Rebased to latest master.

**Comment by KirillOsenkov** [comment]
The builds are clean, and the `compatibility-check` step will need to be updated after the PR is merged.

@slluis @mrward

**Comment by KirillOsenkov** [comment]
Just wanted to say that maybe merge when I'm awake, so I can quickly fix the compat baseline right afterwards.

**Comment by mrward** [comment]
Looks good to me. @Therzok any comments?

The wrench failure is unrelated - an F# test failing.

Also had a discussion with Paras about how to test this yesterday and QA have approved this.

**Comment by KirillOsenkov** [comment]
When you approve, I'll merge this and will fix the md-addins bump, maybe I'll do it later in my day when it's quieter.

**Comment by slluis** [comment]
@KirillOsenkov is there a PR for 15.7?

**Comment by slluis** [comment]
@monojenkins backport d15-7

**Pull request merged**
