### PR TITLE
Fixes issue #4346 Text editor - curly brace problems

### PR DESCRIPTION
**Pull request by mkrueger**
https://github.com/mono/monodevelop/issues/4346

### CODE REVIEW

**Comment by mkrueger** [comment]
Builds: https://code.internalx.com/Wrench/BuildDetails?buildId=d929c556373ea219edef40fd277879
Test instructions: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/591002

**Comment by mkrueger** [comment]
Added https://devdiv.visualstudio.com/DevDiv/_workitems/edit/592988 as well the fix is almost the same area.

**Comment by sgmunn** [comment]
using this build above, for the repro step I have it appears to work.

**Comment by neerajdeshmukh** [comment]
Verified on 15.6 > Visual Studio Enterprise 2017 for Mac Version 7.4.2 (build 14).
It is working fine with following steps. Issue is not reproducible.

Build Gist:
https://gist.github.com/neerajdeshmukh/3938a3e287100e85a2180b4379ce6053

Build Taken from:
https://code.internalx.com/Wrench/BuildDetails?buildId=d929c556373ea219edef40fd277879

Steps Followed:
1. Create new C# console project
2. Under Visual Studio preferences, set Source Code > Code Formatting > Policy to "Default". I used default for all file types.
3. Set all policies to default in Project Options > Source Code > Code Formatting
4. Add a new method and press return to add a line between curly braces. 
5. Uncheck "Convert tabs to space" under Project Options > Source Code > Code Formatting > C# source code
6. Add a new method, press return to add a new line after the opening curly brace.

—————————————————————————————————————————————————————
Also verified issue with 15.7 > Visual Studio Enterprise 2017 for Mac (Preview) 7.5 Preview (7.5 build 1048)
It is working fine with following steps.

Build Gist:
https://gist.github.com/mohakbarokar/520cf8f9ba1943706365761493ddfc01

#Scenario 1:
1. Under Visual Studio Preferences, set all policies to "Default"
2. Uncheck "Convert tabs to space" under Project Options > Source Code > Code Formatting > Text file and set C# source code policy to "Default"
3. Add a new method, press return to add a new line after the opening curly brace. 

#Scenario 2:
1.  Under Visual Studio Preferences, set all policies to "Default"
2. Set all code formatting preferences and project options to default
3. Add a new method, press return to add a new line after the opening curly brace
4. Press delete to remove the new line. Do not click or type anything else.

But observed one issue where error is not displayed even after deleting braces.

Bug ID: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/594665

Kindly review comment and approved if we are targeting 594665 issue in different PR.

**Pull request merged**
