### PR TITLE
Upgrade csproj files to TargetFramework net4.5 and ToolsVersion 4.0

### PR DESCRIPTION
**Pull request by tpokorra**
this is another step to make Monodevelop compile with mono from git master

### CODE REVIEW

**Comment by mhutch** [comment]
All of those addins are abandoned, you should not be building them (except the win32 debugger, but that doesn't need to compile with Mono).

**Comment by Therzok** [comment]
How is the Gtk support addin abandoned?

**Comment by mhutch** [comment]
GtkCore != GtkCore2

GtkCore2 was a SoC project a few years back that was a major overhaul of the GTK# designer, but unfortunately Lluis did not want to review/merge it, and now it's bitrotted.

**Comment by Therzok** [comment]
Oh, I just noticed it's not in the solution file. o.O

**Pull request closed without merging**
