### PR TITLE
Breakpoints.Clear() deactivates all the breakpoints

### PR DESCRIPTION
**Pull request by nerzhulart**
Breakpoints.Clear() deactivates all the breakpoints. Otherwise COM exception may be thrown on Detach() or Terminate()

### CODE REVIEW

**Comment by slluis** [comment]
Do we really want to remove all breakpoints when the session ends? That doesn't sound like a good idea.

**Comment by nerzhulart** [comment]
@slluis I've got what you're talking about. Will fix ASAP

**Comment by nerzhulart** [comment]
@slluis Fixed https://github.com/mono/monodevelop/pull/1789

**Comment by slluis** [comment]
Thanks!

**Pull request merged**
