### PR TITLE
Removed the Lua bindings

### PR DESCRIPTION
**Pull request by Mailaender**
~~Also added some project and file templates from https://github.com/KateAdams/LuaBinding and https://github.com/OpenRA/OpenRA.~~

### CODE REVIEW

**Comment by Therzok** [comment]
Going to take a while to review fully, but so far, lgtm.

**Comment by Therzok** [comment]
Heya, the `extras` folder isn't quite supported anymore inside `MonoDevelop`. The extras addins now reside [here](https://github.com/monodevelop), specifically, for the [LuaBinding](https://github.com/monodevelop/LuaBinding). Can you open a Pull Request against that repository? I'll gladly merge it afterwards.

**Comment by Mailaender** [comment]
Filed it at https://github.com/monodevelop/LuaBinding/pull/1 and removed them here to avoid future confusion.

**Comment by Therzok** [comment]
I'm not sure about what will happen to these addins yet. They will probably be removed at the next repository reorganization. Until then, on standby until LuaBinding PR is merged.
selfie-0

**Comment by slluis** [comment]
Thanks!

**Pull request merged**
