### PR TITLE
D15 7 vsts612435

### PR DESCRIPTION
**Pull request by mkrueger**
Fixes VSTS #612435

### CODE REVIEW

**Comment by GLjackyvaswani** [comment]
Hello,

The assembly browser is still not working.I created a blank forms application and tried searching for ContentPage in assembly browser, the search was not successful. 
The bug https://devdiv.visualstudio.com/DevDiv/_workitems/edit/612435 is reproducible.
Hence this cannot be merged.

Build info:
Version 7.5.1 (build 7)

Build gist:
https://gist.github.com/p-lad/94c9f0fa5a18744c5720feacdd27f668

Build taken from:
https://github.com/mono/monodevelop/pull/4764

Screencast link:
https://www.screencast.com/t/2EVozLZXi0E

Logs: 
[15.7logs.zip](https://github.com/mono/monodevelop/files/1995342/15.7logs.zip)

Note: On closing the solution and then when I tried to create a new blank forms application, it was not created. Only after relaunching VSfM I was able to create a new blank forms application. 
Screencast link: https://www.screencast.com/t/YDxK1uB4hdy

Thanks

**Comment by mkrueger** [comment]
You've to wat a bit until everything is loaded…

**Comment by slluis** [comment]
@GLjackyvaswani can you test again?

**Comment by mohakbarokar** [comment]
Hello,

As discussed with @mrward  on slack, assembly browser is now working fine. Created a blank forms application and searched for content page in the assembly browser. Related results were observed. Tried it for android and iOS application.
I can confirm that the bug: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/612435 is not reproducible when tested on:

Build info:
Visual Studio Enterprise 2017 for Mac
Version 7.5.1 (build 11)

Build gist:
https://gist.github.com/mohakbarokar/bcdd0a0293bf76737d6ccde297b4ed1c

Screencast link:
https://www.screencast.com/t/Wswf2O606

As the issue is not reproduced, it can be merged.
Thanks

**Comment by slluis** [comment]
Not merging yet. Let's wait for a bit of dogfooding in master.

**Comment by mkrueger** [comment]
The question is who is using the assembly browser in master ? I don't - otherwise I would've fixed that thing earlier. The switch to the newer ic#code decompiler required an overwork :/.

On the plus side we can now get some compatiblity with ILSpy if we want to.

**Comment by mkrueger** [comment]
closing / outdated.

**Pull request closed without merging**
