### PR TITLE
Fixes issue #4007 UI accessed from non-UI thread

### PR DESCRIPTION
**Pull request by mkrueger**
https://github.com/mono/monodevelop/issues/4007

### CODE REVIEW

**Comment by DavidKarlas** [comment]
Imo, it would be nicer fix to remove `.ConfigureAwait(false);` from line 747

**Comment by slluis** [comment]
ConfigureAwait can be removed, but that won't fix the bug, because the await is done from a background thread, so it will continue on a background thread.

**Comment by DavidKarlas** [comment]
I did check both calls to Update, from what I understand both come from UI thread, hence my comment

**Comment by slluis** [comment]
We need a PR for d15.7 too.

**Comment by DavidKarlas** [comment]
Whops, I just saw this is wrapped in Task.Run, nvm my comment

**Pull request merged**
