### PR TITLE
[Ide.Tests] Retry writing to file in multi-target test

### PR DESCRIPTION
**Pull request by mrward**
Try to fix the sharing violation that may happen on the build server
when the MultiTargetFramework_ReloadProject_TargetFrameworksChanged
test tries to write the project file to disk directly using
File.WriteAllText.

Fixes VSTS #1050360 - MultiTargetFramework_ReloadProject_TargetFrameworksChanged
test reliability

### CODE REVIEW

**Comment by radical** [comment]
Maybe add a CWL to see if we got any sharing violation exception, because when I was trying a new branch, with no changes - it wasn't failing! So, I'm not sure if it failed here at all.

**Comment by mrward** [comment]
Not expecting it to fail here. The md-addins build would be the one failing since that uses Mono 6.10.

I can add some Console.WriteLines here to see if it is happening with the md-addins build.

**Comment by radical** [comment]
Hm so, the file seems to get "locked" after `using (var sol = (Solution)await Services.ProjectService.ReadWorkspaceItem (Util.GetMonitor (), solFile)) {`.
Trying to follow the code paths, IIUC, it gets read here - https://github.com/mono/monodevelop/blob/master/main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProject.cs#L232 .

I'm trying to find other places where the file might be getting opened and not disposed.

**Comment by radical** [comment]
hm that seems to have fixed the test. But the question is - how does this test pass on master with 6.8.0? @mrward this does test run, as is, on master, correct?

**Comment by radical** [comment]
err.. my mistake. This PR is against master!

**Comment by radical** [comment]
@mrward Was this test failing only sometimes on master+mono-6.8.0?

**Comment by radical** [comment]
@Therzok thanks for the review. I have opened a fresh PR for this though - https://github.com/mono/monodevelop/pull/9554 .

**Comment by mrward** [comment]
Replaced with #9554

**Pull request closed without merging**
