### PR TITLE
[Mac] Fix build with Xamarin.Mac 2.0

### PR DESCRIPTION
**Pull request by mhutch**

### CODE REVIEW

**Comment by alanmcgovern** [comment]
I presume our bots will have to be updated to xammac 2.x before this can be merged, which means md-addins will need porting and XamarinVS will have to test all their stuff to make sure it still works with the newer xammac?

**Comment by jstedfast** [comment]
I think it would actually be fine, because the APIs that take CGRect exist in Xamarin.Mac 1.12 afaik, it's just that 1.12 *also* has compatibility APIs to massage RectangleF into CGRect.

I could be wrong though... @chamons ?

**Comment by mhutch** [comment]
The buildbot seems happy with it.

**Comment by mhutch** [comment]
Though I guess it's only building Windows?

**Comment by alanmcgovern** [comment]
Yeah, it only builds linux afaik

**Comment by chamons** [comment]
:+1:

**Pull request closed without merging**
