### PR TITLE
Fixes VSTS 564610: code completion is broken

### PR DESCRIPTION
**Pull request by mkrueger**
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/564610

Work around for injecting protocol completion into the override
context.

### CODE REVIEW

**Comment by slluis** [comment]
Can we have unit tests for this?

**Comment by mkrueger** [comment]
Hard for that layer - it's a hack :/

**Comment by slluis** [comment]
Then maybe it can be tested at a higher layer?

**Comment by mkrueger** [comment]
fortunately there were some old c# completion text editor extension tests.

**Pull request merged**
