### PR TITLE
Add more file extensions to msbuild mimetype

### PR DESCRIPTION
**Pull request by sandyarmstrong**
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/999409

### CODE REVIEW

**Comment by sandyarmstrong** [comment]
@monojenkins backport release-8.4

**Comment by mhutch** [comment]
FWIW the MSBuild editor extension redefines the mimetype so this is redundant for folks who use it. And I would suggest that anyone who wants to edit MSBuild files should have it installed.

**Comment by mhutch** [comment]
FYI https://github.com/mhutch/MonoDevelop.MSBuildEditor/blob/master/MonoDevelop.MSBuildEditor/Properties/Manifest.addin.xml#L16

**Comment by decriptor** [comment]
FTW, Not sure of the current state, but I've had to disable or uninstall the MSBuildEditor extension because it was causing VSmac to hardcrash. I think there was probably some assembly ref mismatch.

**Comment by knocte** [comment]
> I would suggest that anyone who wants to edit MSBuild files should have it installed.

Why not having this extention installed by default in VS4Mac. I would think at some point all .NET devs are going to edit msbuild files.

**Comment by sandyarmstrong** [comment]
@knocte yes, that would be ideal. There are some blockers that need to be fixed first (like proper textmate bundle support in new editor).

**Pull request merged**
