### PR TITLE
Create ar.po (Arabic lang)

### PR DESCRIPTION
**Pull request by Omaranwa**
i donot know if it support it but i will add it any way.

### CODE REVIEW

**Comment by Therzok** [comment]
Can you also add it to the po.mdproj project?

**Comment by Omaranwa** [comment]
ok i will add it

**Comment by Omaranwa** [comment]
also how i can get the lastest build for win (or how can i build it for win on my own).

**Comment by Therzok** [comment]
@Omaranwa Documentation here should help: http://www.monodevelop.com/developers/building-monodevelop/

**Pull request merged**
