### PR TITLE
Bump to md-addins/mono-2018-04

### PR DESCRIPTION
**Pull request by luhenry**

### CODE REVIEW

**Comment by lambdageek** [comment]
VSTS: VS for Mac - Unit Tests fails `MonoDevelop.Core.LoggingServiceTests.TestSimpleLogging(Fatal,"LogFatalError")` with:
```
Expected string length 21 but was 93. Strings differ at index 0.
Expected: "This is a log message"
But was: "[2843 (+1)] Registering assemblies for framework .NETPortable..."
-----------^
```

> it’s an unit test glitch, you can ignore it, it should be fixed in latest monodevelop master

So looks like I need to merge a more recent master into the `mono-2018-04` branch

**Comment by lambdageek** [comment]
@slluis @alanmcgovern So `mono-2018-04` is passing all the VSTS tests but the wrench lane is timing out on `test-md-ide`:
```
Tests run: 639, Passed: 626, Errors: 0, Failures: 0, Inconclusive: 0
  Not run: 13, Invalid: 0, Ignored: 13, Skipped: 0
Elapsed time: 00:00:40.1720000

Tests Not Run:

1) ReadonlyTextDocumentTestBase.TestLocationToOffset (MonoDevelop.Ide.Editor.MonoTextEditorImplementationTests.ReadonlyTextDocumentTestBase.TestLocationToOffset)
   Broken Bug #54245

2) ReadonlyTextDocumentTestBase.TestLocationToOffset (MonoDevelop.Ide.Editor.MonoTextEditorSnapshotImplementationTests.ReadonlyTextDocumentTestBase.TestLocationToOffset)
   Broken Bug #54245

3) ReadonlyTextDocumentTestBase.TestLocationToOffset (MonoDevelop.Ide.Editor.SimpleReadonlyDocument_Tests.ReadonlyTextDocumentTestBase.TestLocationToOffset)
   Broken Bug #54245

4) TestLookbehindBug (MonoDevelop.Ide.Editor.SyntaxHighlightingTest.TestLookbehindBug)
   Fixme

5) TestYamlHighlighting (MonoDevelop.Ide.Editor.TestYamlHighlighting)
   Fixme

6) TestBug30591 (MonoDevelop.Ide.Gui.CompletionListWindowTests.TestBug30591)
   See Bug #41922

7) TestBug41922 (MonoDevelop.Ide.Gui.CompletionListWindowTests.TestBug41922)
   See Bug #41922

8) TestMatchPunctuationCase3 (MonoDevelop.Ide.Gui.CompletionListWindowTests.TestMatchPunctuationCase3)

9) TestMatchPunctuationCommitOnSpaceAndPunctuation2 (MonoDevelop.Ide.Gui.CompletionListWindowTests.TestMatchPunctuationCommitOnSpaceAndPunctuation2)

10) TestMatchPunctuationCommitOnSpaceAndPunctuation3 (MonoDevelop.Ide.Gui.CompletionListWindowTests.TestMatchPunctuationCommitOnSpaceAndPunctuation3)

11) TestMatchPunctuationCommitOnSpaceAndPunctuation5 (MonoDevelop.Ide.Gui.CompletionListWindowTests.TestMatchPunctuationCommitOnSpaceAndPunctuation5)

12) TestReturnCompletionWithAutoSelectOff (MonoDevelop.Ide.Gui.CompletionListWindowTests.TestReturnCompletionWithAutoSelectOff)
   
 now always commits

13) RunAnimation (MonoDevelop.Ide.Gui.LogViewTests.RunAnimation)
   This test is *far* too strict to reliably pass on different machines. A 20ms window is not enough
  at MonoDevelop.Ide.Gui.LogViewTests+<RunAnimation>d__4.MoveNext () [0x00018] in /Users/builder/data/lanes/6027/b35b5e0c/source/monodevelop/main/tests/Ide.Tests/MonoDevelop.Ide.Gui/LogViewTests.cs:91 



Results saved as /Users/builder/data/lanes/6027/b35b5e0c/source/monodevelop/main/tests/TestResult_MonoDevelop.Ide.Tests.dll.xml.

*** Timed out. Proceeding to get stack traces for all child processes. (2018-04-18T21:25:13)***

*** The build step 'test-md-ide' didn't finish in 10 minute(s). *** 
```

Not sure what's next.

**Comment by alanmcgovern** [comment]
Assuming we started from a green commit and that hangs/deadlocks are not currently happening in master, then it seems likely that mono has a deadlock-on-shutdown type bug in this build.

How frequent is this hang, and can it be reproduced locally? If you push 10 empty commits and make them build on wrench, what % of them deadlock/hang?

**Comment by slluis** [comment]
The md-addins PR has been merged.

**Pull request closed without merging**
