### PR TITLE
[Tests] Initial support for benchmarking unit tests.

### PR DESCRIPTION
**Pull request by Therzok**
They don't work yet, they show up as passed, but assemblies aren't loaded because they're shadow copied.

I'll add documentation on how to write stuff, but this is an initial glance.

Each benchmark would need its own class with one `Bench` method.

### CODE REVIEW

**Comment by slluis** [comment]
Which output does this generate?

**Comment by Therzok** [comment]
Default output which is in the format of:
```
 Method |         Median |      StdDev |  Gen 0 | Gen 1 | Gen 2 | Bytes Allocated/Op |
------- |--------------- |------------ |------- |------ |------ |------------------- |
  Test1 | 20,892.8483 us | 289.0976 us | 143.00 |     - |     - |         655,768.24 |
  Test2 |    272.9095 us |   2.3111 us |      - |     - |     - |              26.89 |
```

We can configre the output to have the data in whatever format we like:
https://github.com/PerfDotNet/BenchmarkDotNet/tree/master/src/BenchmarkDotNet.Core/Exporters

**Comment by Therzok** [comment]
Also waiting on the cross platform GC stats that don't use Windows ETW.

**Comment by Therzok** [comment]
Closing for now but leaving the branch alive. Might be useful, but we now have a profiler-integrated infrastructure.

**Pull request closed without merging**
