### PR TITLE
[C7][Ide] Run command update handlers in key bindings option panel

### PR DESCRIPTION
**Pull request by sevoku**
This fixes the branding icon (and maybe some others) in the key bindings option panel.

### CODE REVIEW

**Comment by slluis** [comment]
I don't like the idea of calling GetCommandInfo on every command, it may be a slow operation. What is this trying to fix?

**Comment by sevoku** [comment]
Well command handlers can update Labels and Icons. This is definitely used for branding (About command) and without this fix we have a MD Logo instead of the Xamarin logo there. Maybe some other commands are affected too (wrong icons).

**Comment by sevoku** [comment]
An other option is to hide the command from the Key Bindings panel (which actually makes more sense in that specific case), but I'm not sure about other icons.

**Comment by mhutch** [comment]
Could we do it asynchronously?

**Comment by sevoku** [comment]
The problem is that `CommandService.GetCommandInfo` needs to run on the main ui thread. We could do something like:
```c#
var iters = new Dictionary<Command, TreeIter> ();
[... populate tree ...]
System.Threading.Tasks.Task.Run (() => {
	foreach (var cmd in iters) {
		CommandInfo info = null;
		Runtime.RunInMainThread (() => {
			info = IdeApp.CommandService.GetCommandInfo (cmd.Key.Id);
			keyStore.SetValue (cmd.Value, iconCol, info.Icon);
		});
	}
});
```
which would save us 100-150ms

**Comment by slluis** [comment]
If the problem is the icon in the About command, we can just remove it from the command definition.

**Comment by sevoku** [comment]
It looks like we could just remove the icon from the default command info in https://github.com/mono/monodevelop/blob/cycle7/main/src/core/MonoDevelop.Ide/ExtensionModel/Commands.addin.xml#L791, so it would remain in the menus only.

**Comment by sevoku** [comment]
@slluis sorry I missed your :+1: :)
This is already included in the `main-menu-redesign` (09e9871fdac14cae9e86a2f8c264206c7f5589c5) branch.

**Pull request merged**
