### PR TITLE
Bug 28856 - [Windows] Unable to open .sln file or .csproj file when we r...

### PR DESCRIPTION
**Pull request by Therzok**
...ight click on it and select open with XS

### CODE REVIEW

**Comment by knocte** [comment]
If you put a "ResolveFullPath()" method in FilePath class, I bet the overall API would look confusing because there's already a "FullPath" property in it.

**Comment by Therzok** [comment]
This will be changed. I put it up for review.

**Comment by knocte** [comment]
Even if you drop ResolveFullPath() from FileService, FilePath would still have both `FullPath` property and `ResolveFullPath()` method. What's the difference between them? (A consumer of the API would wonder...)

**Comment by Therzok** [comment]
Check the naming. It's not ResolveLinks (), so that means it'll resolve symlinks.

**Comment by knocte** [comment]
Sorry, don't quite understand your last message.

**Comment by Therzok** [comment]
`ResolveFullPath` has been renamed to `ResolveLinks`.

**Comment by knocte** [comment]
Oh I see. No concerns from now then. Thanks!

**Comment by Therzok** [comment]
Merged manually.

**Pull request closed without merging**
