### PR TITLE
Diagnostics test suite

### PR DESCRIPTION
**Pull request by Therzok**

### CODE REVIEW

**Comment by Therzok** [comment]
Ready for review now.

**Comment by Therzok** [comment]
@mrward there's a test failure in package management, could you please take a look?

**Comment by mrward** [comment]
@Therzok - No idea. I do not see how your code changes have affected it. That test has not changed for a long time. On the previous builds of this branch those tests passed.

**Comment by Therzok** [comment]
It passed now.

**Comment by Therzok** [comment]
All green :shipit:

**Pull request merged**
