### PR TITLE
[Fix] 41750 - TestCase detection broken

### PR DESCRIPTION
**Pull request by tstivers1990**

### CODE REVIEW

**Comment by slluis** [comment]
whitelist

**Comment by slluis** [comment]
Thanks!

**Comment by tstivers1990** [comment]
No problem. I'm not 100% certain if the fix actually works or not. I'll check it in a few hours when I get my new computer which will actually be capable of compiling MonoDevelop. I'll respond here to let you know whether or not the fix was successful.

I'm pretty certain this change fixes it though.

**Comment by tstivers1990** [comment]
Managed to test this fix today, and confirmed it did actually fix the bug.

**Pull request merged**
