### PR TITLE
[BuildOutput] Add basic usage telemetry

### PR DESCRIPTION
**Pull request by rodrmoya**
Backport of https://github.com/mono/monodevelop/pull/4961

### CODE REVIEW

**Comment by sgmunn** [comment]
@rodrmoya back port to release-7.7

**Comment by rodrmoya** [comment]
@monojenkins backport release-7.7

**Comment by sgmunn** [comment]
@rodrmoya did this get backported to 7.7 ?

**Comment by rodrmoya** [comment]
@sgmunn no, but because it was already in master when 7.7 was branched, so all good here

**Pull request merged**
