### PR TITLE
Fixes VSTS 611923: Unable to add declarations to an empty C# file

### PR DESCRIPTION
**Pull request by mkrueger**
which is added to existing .net console project.

https://devdiv.visualstudio.com/DevDiv/_workitems/edit/611923

### CODE REVIEW

**Comment by mkrueger** [comment]
+ Affects all projects not only core.

+ It's not a regression - that bug has been there for a long time. It looks like it's important but fortunately it's just an unimportant corner case.

+ When we do an API overhaul release we should ship with 0 obsolete members.

**Comment by Therzok** [comment]
Test failure seems unrelated. cc @mrward @luhenry @alexischr 
```
018-05-09T09:12:44.8880360Z 2018-05-09 09:12:44.886 vstool[1761:19111] error: * Assertion at mono-threads.c:1582, condition `previous_token == NULL || previous_token == INTERRUPT_STATE' not met
2018-05-09T09:12:44.8900190Z Stacktrace:
2018-05-09T09:12:44.8908810Z 
2018-05-09T09:12:44.8925430Z   at <unknown> <0xffffffff>
2018-05-09T09:12:44.8945270Z   at (wrapper managed-to-native) Interop/RunLoop.CFRunLoopRun () [0x00006] in <74ba1e8d9e9542189d25a8f815d7cc78>:0
2018-05-09T09:12:44.8970930Z   at System.IO.CoreFX.FileSystemWatcher/RunningInstance.WatchForFileSystemEventsThreadStart (object) [0x00047] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-04/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.OSX.cs:288
2018-05-09T09:12:44.8995160Z   at System.Threading.ThreadHelper.ThreadStart_Context (object) [0x00025] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-04/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/threading/thread.cs:72
2018-05-09T09:12:44.9019260Z   at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool) [0x00071] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-04/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:961
2018-05-09T09:12:44.9044160Z   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-04/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:908
2018-05-09T09:12:44.9068390Z   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object) [0x0002b] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-04/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:897
2018-05-09T09:12:44.9090100Z   at System.Threading.ThreadHelper.ThreadStart (object) [0x0000f] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-04/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/threading/thread.cs:87
2018-05-09T09:12:44.9111490Z   at (wrapper runtime-invoke) <Module>.runtime_invoke_void__this___object (object,intptr,intptr,intptr) [0x00053] in <17f5177733084096b17badd9e32426e5>:0
2018-05-09T09:12:44.9121250Z 
2018-05-09T09:12:44.9136310Z Native stacktrace:
2018-05-09T09:12:44.9143750Z 
2018-05-09T09:12:44.9219820Z 	0   libmonosgen-2.0.dylib               0x000000010c6c0618 mono_handle_native_crash + 264
2018-05-09T09:12:44.9238470Z 	1   libsystem_platform.dylib            0x00007fff61ed7f5a _sigtramp + 26
2018-05-09T09:12:44.9255510Z 	2   ???                                 0x0000700004220068 0x0 + 123145371648104
2018-05-09T09:12:44.9273010Z 	3   libsystem_c.dylib                   0x00007fff61c751ae abort + 127
2018-05-09T09:12:44.9291900Z 	4   libxammac.dylib                     0x000000010caab210 _ZL12log_callbackPKcS0_S0_iPv + 64
2018-05-09T09:12:44.9312070Z 	5   libmonosgen-2.0.dylib               0x000000010c8eab73 monoeg_g_logv + 83
2018-05-09T09:12:44.9332250Z 	6   libmonosgen-2.0.dylib               0x000000010c8ead8f monoeg_assertion_message + 143
2018-05-09T09:12:44.9354010Z 	7   libmonosgen-2.0.dylib               0x000000010c8e0f80 mono_thread_info_describe_interrupt_token + 0
2018-05-09T09:12:44.9375980Z 	8   libmonosgen-2.0.dylib               0x000000010c81f4de mono_thread_execute_interruption + 142
2018-05-09T09:12:44.9395530Z 	9   ???                                 0x000000010d2963c1 0x0 + 4515783617
2018-05-09T09:12:44.9413080Z 	10  ???                                 0x0000000116847b0b 0x0 + 4672748299
2018-05-09T09:12:44.9430410Z 	11  FSEvents                            0x00007fff3acae463 implementation_callback_rpc + 2833
2018-05-09T09:12:44.9447790Z 	12  FSEvents                            0x00007fff3acad8dd _Xcallback_rpc + 233
2018-05-09T09:12:44.9465190Z 	13  FSEvents                            0x00007fff3acad7d7 FSEventsD2F_server + 55
2018-05-09T09:12:44.9482500Z 	14  FSEvents                            0x00007fff3acaf496 FSEventsClientProcessMessageCallback + 43
2018-05-09T09:12:44.9499840Z 	15  CoreFoundation                      0x00007fff3982ec36 __CFMachPortPerform + 310
2018-05-09T09:12:44.9517220Z 	16  CoreFoundation                      0x00007fff3982eae9 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 41
2018-05-09T09:12:44.9534560Z 	17  CoreFoundation                      0x00007fff3982ea35 __CFRunLoopDoSource1 + 533
2018-05-09T09:12:44.9552570Z 	18  CoreFoundation                      0x00007fff398267c0 __CFRunLoopRun + 2848
2018-05-09T09:12:44.9569870Z 	19  CoreFoundation                      0x00007fff39825a07 CFRunLoopRunSpecific + 487
2018-05-09T09:12:44.9587080Z 	20  CoreFoundation                      0x00007fff39863e73 CFRunLoopRun + 99
2018-05-09T09:12:44.9606440Z 	21  libmonosgen-2.0.dylib               0x000000010c7ada4d ves_icall_CoreFX_Interop_RunLoop_CFRunLoopRun + 61
2018-05-09T09:12:44.9625030Z 	22  ???                                 0x000000011cde9127 0x0 + 4779315495
2018-05-09T09:12:44.9642930Z 	23  ???                                 0x000000011a258456 0x0 + 4733633622
2018-05-09T09:12:44.9659420Z 	24  ???                                 0x000000011434cebb 0x0 + 4633972411
2018-05-09T09:12:44.9678810Z 	25  libmonosgen-2.0.dylib               0x000000010c613088 mono_jit_runtime_invoke + 1416
2018-05-09T09:12:44.9699780Z 	26  libmonosgen-2.0.dylib               0x000000010c801c64 do_runtime_invoke + 84
2018-05-09T09:12:44.9720970Z 	27  libmonosgen-2.0.dylib               0x000000010c82518e start_wrapper + 750
2018-05-09T09:12:44.9739740Z 	28  libsystem_pthread.dylib             0x00007fff61ee1661 _pthread_body + 340
2018-05-09T09:12:44.9757380Z 	29  libsystem_pthread.dylib             0x00007fff61ee150d _pthread_body + 0
2018-05-09T09:12:44.9774910Z 	30  libsystem_pthread.dylib             0x00007fff61ee0bf9 thread_start + 13
2018-05-09T09:12:44.9783550Z 
2018-05-09T09:12:44.9800200Z Debug info from gdb:
2018-05-09T09:12:44.9808690Z 
2018-05-09T09:12:46.9741890Z (lldb) command source -s 0 '/tmp/mono-gdb-commands.uew0ny'
2018-05-09T09:12:46.9763240Z Executing commands in '/tmp/mono-gdb-commands.uew0ny'.
2018-05-09T09:12:46.9784180Z (lldb) process attach --pid 1761
2018-05-09T09:12:54.0529540Z warning: (x86_64) /Library/Frameworks/Mono.framework/Versions/5.14.0/lib/libgthread-2.0.0.dylib empty dSYM file detected, dSYM was created with an executable with no debug info.
2018-05-09T09:12:54.1487740Z warning: (x86_64) /Library/Frameworks/Mono.framework/Versions/5.14.0/lib/libgio-2.0.0.dylib empty dSYM file detected, dSYM was created with an executable with no debug info.
2018-05-09T09:12:54.1882980Z warning: (x86_64) /Library/Frameworks/Mono.framework/Versions/5.14.0/lib/libgmodule-2.0.0.dylib empty dSYM file detected, dSYM was created with an executable with no debug info.
2018-05-09T09:12:54.1906540Z warning: (x86_64) /Library/Frameworks/Mono.framework/Versions/5.14.0/lib/libgobject-2.0.0.dylib empty dSYM file detected, dSYM was created with an executable with no debug info.
2018-05-09T09:12:54.2018280Z warning: (x86_64) /Library/Frameworks/Mono.framework/Versions/5.14.0/lib/libglib-2.0.0.dylib empty dSYM file detected, dSYM was created with an executable with no debug info.
2018-05-09T09:12:58.3213410Z Process 1761 stopped
2018-05-09T09:12:58.3243730Z * thread #1, name = 'tid_307', queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
2018-05-09T09:12:58.3264870Z     frame #0: 0x00007fff61d19a1e libsystem_kernel.dylib`__psynch_cvwait + 10
2018-05-09T09:12:58.3281790Z libsystem_kernel.dylib`__psynch_cvwait:
2018-05-09T09:12:58.3300530Z ->  0x7fff61d19a1e <+10>: jae    0x7fff61d19a28            ; <+20>
2018-05-09T09:12:58.3319720Z     0x7fff61d19a20 <+12>: movq   %rax, %rdi
2018-05-09T09:12:58.3336290Z     0x7fff61d19a23 <+15>: jmp    0x7fff61d10b00            ; cerror_nocancel
2018-05-09T09:12:58.3357270Z     0x7fff61d19a28 <+20>: retq   
2018-05-09T09:12:58.3374280Z Target 0: (vstool) stopped.
2018-05-09T09:12:58.3382790Z 
2018-05-09T09:12:58.3399820Z Executable module set to "/Users/vsts/agent/2.133.3/work/r1/a/VS for Mac/drop/dmg/Visual Studio.app/Contents/MacOS/vstool".
2018-05-09T09:12:58.3419810Z Architecture set to: x86_64-apple-macosx.
2018-05-09T09:12:58.3438280Z (lldb) thread list
2018-05-09T09:12:58.3526100Z Process 1761 stopped
2018-05-09T09:12:58.3545980Z * thread #1: tid = 0x4a58, 0x00007fff61d19a1e libsystem_kernel.dylib`__psynch_cvwait + 10, name = 'tid_307', queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
2018-05-09T09:12:58.3565830Z   thread #2: tid = 0x4a59, 0x00007fff61d1a292 libsystem_kernel.dylib`__workq_kernreturn + 10
2018-05-09T09:12:58.3582880Z   thread #3: tid = 0x4a5a, 0x00007fff61d1a292 libsystem_kernel.dylib`__workq_kernreturn + 10
2018-05-09T09:12:58.3600200Z   thread #4: tid = 0x4a5d, 0x00007fff61d19a1e libsystem_kernel.dylib`__psynch_cvwait + 10
2018-05-09T09:12:58.3619640Z   thread #5: tid = 0x4a5e, 0x00007fff61d19a1e libsystem_kernel.dylib`__psynch_cvwait + 10, name = 'SGen worker'
2018-05-09T09:12:58.3641570Z   thread #6: tid = 0x4a5f, 0x00007fff61d10246 libsystem_kernel.dylib`semaphore_wait_trap + 10, name = 'Finalizer'
2018-05-09T09:12:58.3660510Z   thread #7: tid = 0x4a71, 0x00007fff61d1a292 libsystem_kernel.dylib`__workq_kernreturn + 10
2018-05-09T09:12:58.3677740Z   thread #8: tid = 0x4a72, 0x00007fff61d1a292 libsystem_kernel.dylib`__workq_kernreturn + 10
2018-05-09T09:12:58.3694660Z   thread #9: tid = 0x4a73, 0x00007fff61d1a292 libsystem_kernel.dylib`__workq_kernreturn + 10
2018-05-09T09:12:58.3711950Z   thread #10: tid = 0x4a74, 0x00007fff61d1a292 libsystem_kernel.dylib`__workq_kernreturn + 10
2018-05-09T09:12:58.3731600Z   thread #11: tid = 0x4a92, 0x00007fff61d1020a libsystem_kernel.dylib`mach_msg_trap + 10, name = 'com.apple.NSEventThread'
2018-05-09T09:12:58.3753910Z   thread #12: tid = 0x4aa7, 0x00007fff61d1a232 libsystem_kernel.dylib`__wait4 + 10, name = 'tid_bf03'
2018-05-09T09:12:58.3775880Z   thread #13: tid = 0x4ada, 0x00007fff61d19cfa libsystem_kernel.dylib`__select + 10, name = 'com.apple.CFSocket.private'
2018-05-09T09:12:58.3797180Z   thread #14: tid = 0x4adb, 0x00007fff61d1020a libsystem_kernel.dylib`mach_msg_trap + 10, name = 'com.apple.CFStream.LegacyThread'
2018-05-09T09:12:58.3815790Z   thread #15: tid = 0x4adc, 0x00007fff61d1a292 libsystem_kernel.dylib`__workq_kernreturn + 10
2018-05-09T09:12:58.3833220Z   thread #16: tid = 0x4add, 0x00007fff61d1a292 libsystem_kernel.dylib`__workq_kernreturn + 10
2018-05-09T09:12:58.3849960Z   thread #17: tid = 0x4ade, 0x00007fff61d1a292 libsystem_kernel.dylib`__workq_kernreturn + 10
2018-05-09T09:12:58.3867210Z   thread #18: tid = 0x4adf, 0x00007fff61d1a292 libsystem_kernel.dylib`__workq_kernreturn + 10
2018-05-09T09:12:58.3884370Z   thread #19: tid = 0x4ae0, 0x00007fff61d1a292 libsystem_kernel.dylib`__workq_kernreturn + 10
2018-05-09T09:12:58.3901260Z   thread #20: tid = 0x4ae1, 0x00007fff61d1a292 libsystem_kernel.dylib`__workq_kernreturn + 10
2018-05-09T09:12:58.3922490Z   thread #21: tid = 0x4ae2, 0x00007fff61d19a1e libsystem_kernel.dylib`__psynch_cvwait + 10, name = 'WTF::AutomaticThread'
2018-05-09T09:12:58.3946040Z   thread #22: tid = 0x4ae3, 0x00007fff61d19a1e libsystem_kernel.dylib`__psynch_cvwait + 10, name = 'WTF::AutomaticThread'
2018-05-09T09:12:58.3968970Z   thread #23: tid = 0x4ae4, 0x00007fff61d19a1e libsystem_kernel.dylib`__psynch_cvwait + 10, name = 'WTF::AutomaticThread'
2018-05-09T09:12:58.3989280Z   thread #24: tid = 0x4ae6, 0x00007fff61d19a1e libsystem_kernel.dylib`__psynch_cvwait + 10
2018-05-09T09:12:58.4006760Z (lldb) thread backtrace all
2018-05-09T09:12:59.0834860Z * thread #1, name = 'tid_307', queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
2018-05-09T09:12:59.0861320Z   * frame #0: 0x00007fff61d19a1e libsystem_kernel.dylib`__psynch_cvwait + 10
2018-05-09T09:12:59.0878790Z     frame #1: 0x00007fff61ee2589 libsystem_pthread.dylib`_pthread_cond_wait + 732
2018-05-09T09:12:59.0899000Z     frame #2: 0x000000010c8cc650 libmonosgen-2.0.dylib`mono_os_event_wait_multiple [inlined] mono_os_cond_wait(mutex=<unavailable>) at mono-os-mutex.h:173 [opt]
2018-05-09T09:12:59.0922190Z     frame #3: 0x000000010c8cc63b libmonosgen-2.0.dylib`mono_os_event_wait_multiple(events=0x00007ffee3e93060, nevents=11, waitall=1, timeout=4294967295, alertable=1) at os-event-unix.c:190 [opt]
2018-05-09T09:12:59.0946210Z     frame #4: 0x000000010c8e11b1 libmonosgen-2.0.dylib`mono_thread_info_wait_multiple_handle(thread_handles=<unavailable>, nhandles=11, background_change_event=<unavailable>, waitall=<unavailable>, timeout=<unavailable>, alertable=<unavailable>) at mono-threads.c:1646 [opt]
2018-05-09T09:12:59.0969940Z     frame #5: 0x000000010c8229e2 libmonosgen-2.0.dylib`wait_for_tids(wait=0x00007ffee3e932d0, timeout=4294967295, check_state_change=0) at threads.c:3287 [opt]
2018-05-09T09:12:59.0992180Z     frame #6: 0x000000010c822807 libmonosgen-2.0.dylib`mono_thread_manage at threads.c:3507 [opt]
2018-05-09T09:12:59.1013370Z     frame #7: 0x000000010c684a72 libmonosgen-2.0.dylib`mono_main(argc=<unavailable>, argv=<unavailable>) at driver.g.c:2428 [opt]
2018-05-09T09:12:59.1033010Z     frame #8: 0x000000010bd6c635 vstool`main + 3109
2018-05-09T09:12:59.1050700Z     frame #9: 0x00007fff61bc9015 libdyld.dylib`start + 1
2018-05-09T09:12:59.1067700Z   thread #2
2018-05-09T09:12:59.1084090Z     frame #0: 0x00007fff61d1a292 libsystem_kernel.dylib`__workq_kernreturn + 10
2018-05-09T09:12:59.1099870Z     frame #1: 0x00007fff61ee120e libsystem_pthread.dylib`_pthread_wqthread + 1552
2018-05-09T09:12:59.1116520Z     frame #2: 0x00007fff61ee0be9 libsystem_pthread.dylib`start_wqthread + 13
2018-05-09T09:12:59.1131950Z   thread #3
2018-05-09T09:12:59.1148850Z     frame #0: 0x00007fff61d1a292 libsystem_kernel.dylib`__workq_kernreturn + 10
2018-05-09T09:12:59.1165330Z     frame #1: 0x00007fff61ee120e libsystem_pthread.dylib`_pthread_wqthread + 1552
2018-05-09T09:12:59.1181840Z     frame #2: 0x00007fff61ee0be9 libsystem_pthread.dylib`start_wqthread + 13
2018-05-09T09:12:59.1198190Z   thread #4
2018-05-09T09:12:59.1213660Z     frame #0: 0x00007fff61d19a1e libsystem_kernel.dylib`__psynch_cvwait + 10
2018-05-09T09:12:59.1229600Z     frame #1: 0x00007fff61ee2589 libsystem_pthread.dylib`_pthread_cond_wait + 732
2018-05-09T09:12:59.1245670Z     frame #2: 0x00007fff5fb2ad43 libc++.1.dylib`std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >) + 93
2018-05-09T09:12:59.1263000Z     frame #3: 0x00007fff3d48f945 JavaScriptCore`std::__1::cv_status std::__1::condition_variable::wait_until<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > > const&) + 117
2018-05-09T09:12:59.1282970Z     frame #4: 0x00007fff3d48f830 JavaScriptCore`std::__1::cv_status std::__1::condition_variable_any::wait_until<std::__1::unique_lock<bmalloc::Mutex>, std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >(std::__1::unique_lock<bmalloc::Mutex>&, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > > const&) + 96
2018-05-09T09:12:59.1300270Z     frame #5: 0x00007fff3d48f459 JavaScriptCore`bmalloc::Scavenger::threadRunLoop() + 361
2018-05-09T09:12:59.1316750Z     frame #6: 0x00007fff3d48f1e9 JavaScriptCore`bmalloc::Scavenger::threadEntryPoint(bmalloc::Scavenger*) + 9
2018-05-09T09:12:59.1332740Z     frame #7: 0x00007fff3d48f528 JavaScriptCore`void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(bmalloc::Scavenger*), bmalloc::Scavenger*> >(void*) + 40
2018-05-09T09:12:59.1349450Z     frame #8: 0x00007fff61ee1661 libsystem_pthread.dylib`_pthread_body + 340
2018-05-09T09:12:59.1364850Z     frame #9: 0x00007fff61ee150d libsystem_pthread.dylib`_pthread_start + 377
2018-05-09T09:12:59.1380540Z     frame #10: 0x00007fff61ee0bf9 libsystem_pthread.dylib`thread_start + 13
2018-05-09T09:12:59.1399540Z   thread #5, name = 'SGen worker'
2018-05-09T09:12:59.1418290Z     frame #0: 0x00007fff61d19a1e libsystem_kernel.dylib`__psynch_cvwait + 10
2018-05-09T09:12:59.1435190Z     frame #1: 0x00007fff61ee2589 libsystem_pthread.dylib`_pthread_cond_wait + 732
2018-05-09T09:12:59.1467350Z     frame #2: 0x000000010c8c9ace libmonosgen-2.0.dylib`thread_func [inlined] mono_os_cond_wait(mutex=<unavailable>) at mono-os-mutex.h:173 [opt]
2018-05-09T09:12:59.1490740Z     frame #3: 0x000000010c8c9abb libmonosgen-2.0.dylib`thread_func at sgen-thread-pool.c:165 [opt]
2018-05-09T09:12:59.1513970Z     frame #4: 0x000000010c8c9aad libmonosgen-2.0.dylib`thread_func(data=0x0000000000000000) at sgen-thread-pool.c:196 [opt]
2018-05-09T09:12:59.1533930Z     frame #5: 0x00007fff61ee1661 libsystem_pthread.dylib`_pthread_body + 340
2018-05-09T09:12:59.1551540Z     frame #6: 0x00007fff61ee150d libsystem_pthread.dylib`_pthread_start + 377
2018-05-09T09:12:59.1568870Z     frame #7: 0x00007fff61ee0bf9 libsystem_pthread.dylib`thread_start + 13
2018-05-09T09:12:59.1589990Z   thread #6, name = 'Finalizer'
2018-05-09T09:12:59.1609720Z     frame #0: 0x00007fff61d10246 libsystem_kernel.dylib`semaphore_wait_trap + 10
2018-05-09T09:12:59.1630790Z     frame #1: 0x000000010c8777cc libmonosgen-2.0.dylib`finalizer_thread [inlined] mono_os_sem_wait(flags=MONO_SEM_FLAGS_ALERTABLE) at mono-os-semaphore.h:90 [opt]
2018-05-09T09:12:59.1653680Z     frame #2: 0x000000010c8777c1 libmonosgen-2.0.dylib`finalizer_thread at mono-coop-semaphore.h:43 [opt]
2018-05-09T09:12:59.1676350Z     frame #3: 0x000000010c8777b5 libmonosgen-2.0.dylib`finalizer_thread(unused=<unavailable>) at gc.c:903 [opt]
2018-05-09T09:12:59.1698870Z     frame #4: 0x000000010c825163 libmonosgen-2.0.dylib`start_wrapper [inlined] start_wrapper_internal at threads.c:1097 [opt]
2018-05-09T09:12:59.1723030Z     frame #5: 0x000000010c8250d3 libmonosgen-2.0.dylib`start_wrapper(data=0x00007f90e974e7a0) at threads.c:1157 [opt]
2018-05-09T09:12:59.1742160Z     frame #6: 0x00007fff61ee1661 libsystem_pthread.dylib`_pthread_body + 340
2018-05-09T09:12:59.1759490Z     frame #7: 0x00007fff61ee150d libsystem_pthread.dylib`_pthread_start + 377
2018-05-09T09:12:59.1777030Z     frame #8: 0x00007fff61ee0bf9 libsystem_pthread.dylib`thread_start + 13
2018-05-09T09:12:59.1794240Z   thread #7
2018-05-09T09:12:59.1811640Z     frame #0: 0x00007fff61d1a292 libsystem_kernel.dylib`__workq_kernreturn + 10
2018-05-09T09:12:59.1847920Z     frame #1: 0x00007fff61ee120e libsystem_pthread.dylib`_pthread_wqthread + 1552
2018-05-09T09:12:59.1871860Z     frame #2: 0x00007fff61ee0be9 libsystem_pthread.dylib`start_wqthread + 13
2018-05-09T09:12:59.1889170Z   thread #8
2018-05-09T09:12:59.1918650Z     frame #0: 0x00007fff61d1a292 libsystem_kernel.dylib`__workq_kernreturn + 10
2018-05-09T09:12:59.1936320Z     frame #1: 0x00007fff61ee120e libsystem_pthread.dylib`_pthread_wqthread + 1552
2018-05-09T09:12:59.1955410Z     frame #2: 0x00007fff61ee0be9 libsystem_pthread.dylib`start_wqthread + 13
2018-05-09T09:12:59.1985680Z   thread #9
2018-05-09T09:12:59.2002580Z     frame #0: 0x00007fff61d1a292 libsystem_kernel.dylib`__workq_kernreturn + 10
2018-05-09T09:12:59.2020160Z     frame #1: 0x00007fff61ee120e libsystem_pthread.dylib`_pthread_wqthread + 1552
2018-05-09T09:12:59.2037900Z     frame #2: 0x00007fff61ee0be9 libsystem_pthread.dylib`start_wqthread + 13
2018-05-09T09:12:59.2057810Z   thread #10
2018-05-09T09:12:59.2078150Z     frame #0: 0x00007fff61d1a292 libsystem_kernel.dylib`__workq_kernreturn + 10
2018-05-09T09:12:59.2097920Z     frame #1: 0x00007fff61ee120e libsystem_pthread.dylib`_pthread_wqthread + 1552
2018-05-09T09:12:59.2115700Z     frame #2: 0x00007fff61ee0be9 libsystem_pthread.dylib`start_wqthread + 13
2018-05-09T09:12:59.2135950Z   thread #11, name = 'com.apple.NSEventThread'
2018-05-09T09:12:59.2158080Z     frame #0: 0x00007fff61d1020a libsystem_kernel.dylib`mach_msg_trap + 10
2018-05-09T09:12:59.2176150Z     frame #1: 0x00007fff61d0f724 libsystem_kernel.dylib`mach_msg + 60
2018-05-09T09:12:59.2194100Z     frame #2: 0x00007fff39827045 CoreFoundation`__CFRunLoopServiceMachPort + 341
2018-05-09T09:12:59.2211670Z     frame #3: 0x00007fff39826397 CoreFoundation`__CFRunLoopRun + 1783
2018-05-09T09:12:59.2229350Z     frame #4: 0x00007fff39825a07 CoreFoundation`CFRunLoopRunSpecific + 487
2018-05-09T09:12:59.2247900Z     frame #5: 0x00007fff36ef3fc4 AppKit`_NSEventThread + 184
2018-05-09T09:12:59.2265540Z     frame #6: 0x00007fff61ee1661 libsystem_pthread.dylib`_pthread_body + 340
2018-05-09T09:12:59.2285110Z     frame #7: 0x00007fff61ee150d libsystem_pthread.dylib`_pthread_start + 377
2018-05-09T09:12:59.2303310Z     frame #8: 0x00007fff61ee0bf9 libsystem_pthread.dylib`thread_start + 13
2018-05-09T09:12:59.2322720Z   thread #12, name = 'tid_bf03'
2018-05-09T09:12:59.2341520Z     frame #0: 0x00007fff61d1a232 libsystem_kernel.dylib`__wait4 + 10
2018-05-09T09:12:59.2362080Z     frame #1: 0x000000010c6c06bf libmonosgen-2.0.dylib`mono_handle_native_crash(signal=<unavailable>, ctx=<unavailable>, info=<unavailable>) at mini-exceptions.c:2780 [opt]
2018-05-09T09:12:59.2381850Z     frame #2: 0x00007fff61ed7f5a libsystem_platform.dylib`_sigtramp + 26
2018-05-09T09:12:59.2401020Z     frame #3: 0x00007fff61d19b6f libsystem_kernel.dylib`__pthread_kill + 11
2018-05-09T09:12:59.2418500Z     frame #4: 0x00007fff61ee4080 libsystem_pthread.dylib`pthread_kill + 333
2018-05-09T09:12:59.2435640Z     frame #5: 0x00007fff61c751ae libsystem_c.dylib`abort + 127
2018-05-09T09:12:59.2453140Z     frame #6: 0x000000010caab210 libxammac.dylib`log_callback(char const*, char const*, char const*, int, void*) + 64
2018-05-09T09:12:59.2480170Z     frame #7: 0x000000010c8eab73 libmonosgen-2.0.dylib`monoeg_g_logv(log_domain=0x0000000000000000, log_level=G_LOG_LEVEL_ERROR, format=<unavailable>, args=<unProcess 1761 detached
2018-05-09T09:12:59.2500090Z (lldb) quit
2018-05-09T09:12:59.2508810Z 
2018-05-09T09:12:59.2525880Z =================================================================
2018-05-09T09:12:59.2542890Z Got a SIGABRT while executing native code. This usually indicates
2018-05-09T09:12:59.2560030Z a fatal error in the mono runtime or one of the native libraries 
2018-05-09T09:12:59.2578530Z used by your application.
2018-05-09T09:12:59.2595740Z =================================================================
2018-05-09T09:12:59.2604320Z 
```

**Comment by luhenry** [comment]
Which version of Mono is that?

**Comment by Therzok** [comment]
@luhenry it's still our local copy of the fsw.

The bot has `MonoFramework-MDK-5.14.0.54.macos10.xamarin.universal.pkg`

**Pull request merged**
