### PR TITLE
[Debugger] Fix UX glitches in the Locals & Watch pads

### PR DESCRIPTION
**Pull request by jstedfast**
1. When the row is selected, don't use colored text
2. When the row is selected, use a white "gtk-add" icon for "Add new expression"
3. Change the string "Add new expression" to "Add item to watch" to match VS

Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1000546

### CODE REVIEW

**Comment by jstedfast** [comment]
warning-text-color

**Comment by jstedfast** [comment]
So it turns out that it seems like "gtk-add" doesn't have a ~sel icon variant?

**Comment by vancura** [comment]
I am really sorry, it's truth we don't have the icon there! Could you please add it? It should be next to other `add-16.png` related files, in `monodevelop/main/src/core/MonoDevelop.Ide/icons`. Here are the files: http://vancu.link/c107ee

**Comment by jstedfast** [comment]
Okay, the add icon is now white when the row is selected. yay!

**Comment by jstedfast** [comment]
@monojenkins backport release-8.4

**Comment by ketttY** [comment]
Verified under both modes:
Screen Shot 2019-11-11 at 10 15 44 AM
Screen Shot 2019-11-11 at 10 14 05 AM

**Comment by sgmunn** [comment]
Fixed up conflicts

**Pull request merged**
