### PR TITLE
Kept panther blockselection

### PR DESCRIPTION
**Pull request by mkrueger**

### CODE REVIEW

**Comment by mkrueger** [comment]
Ok seems that there are 1-2 little issues with it need to fix that first.

**Comment by nosami** [comment]
Looking forward to this. I use block selection often from the Vim addin.

**Comment by mkrueger** [comment]
We"ve unit tests for block selection - that's purely a visual thing.

**Comment by mkrueger** [comment]
I requested some changes - it looks better when just using spaces but tab indentation completely screws it. 

I don't think it can be implemented w/o changing drawing code.

**Pull request closed without merging**
