### PR TITLE
Fixes issue #6482 Cannot rename public types This prevents that the

### PR DESCRIPTION
**Pull request by mkrueger**
same editor is added twice to the refactoring operation and balances
out undo groups.

### CODE REVIEW

**Comment by mkrueger** [comment]
@monojenkins backport release 7-7

**Comment by slluis** [comment]
@Therzok can you please verify the fix?

**Comment by Therzok** [comment]
Different error now:
```
RROR [2018-10-29 16:20:25Z]: Error while renaming symbol ViewController
System.NullReferenceException: Object reference not set to an instance of an object
  at MonoDevelop.CodeActions.CodeActionEditorExtension.Editor_EndAtomicUndoOperation (System.Object sender, System.EventArgs e) [0x00000] in /Users/vsts/agent/2.141.1/work/1/s/monodevelop/main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeActions/CodeActionEditorExtension.cs:353 
  at (wrapper delegate-invoke) <Module>.invoke_void_object_EventArgs(object,System.EventArgs)
  at MonoDevelop.SourceEditor.SourceEditorView.OnEndUndo (System.EventArgs e) [0x0000a] in /Users/vsts/agent/2.141.1/work/1/s/monodevelop/main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs:2587 
  at MonoDevelop.SourceEditor.SourceEditorView.HandleEndUndo (System.Object sender, Mono.TextEditor.TextDocument+UndoOperationEventArgs e) [0x00000] in /Users/vsts/agent/2.141.1/work/1/s/monodevelop/main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs:352 
  at (wrapper delegate-invoke) System.EventHandler`1[Mono.TextEditor.TextDocument+UndoOperationEventArgs].invoke_void_object_TEventArgs(object,Mono.TextEditor.TextDocument/UndoOperationEventArgs)
  at Mono.TextEditor.TextDocument.OnEndUndo (Mono.TextEditor.TextDocument+UndoOperationEventArgs e) [0x0000a] in /Users/vsts/agent/2.141.1/work/1/s/monodevelop/main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/TextDocument.cs:1256 
  at Mono.TextEditor.TextDocument.EndAtomicUndo () [0x0005d] in /Users/vsts/agent/2.141.1/work/1/s/monodevelop/main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/TextDocument.cs:1215 
  at Mono.TextEditor.TextDocument+UndoGroup.Dispose () [0x00008] in /Users/vsts/agent/2.141.1/work/1/s/monodevelop/main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/TextDocument.cs:1175 
  at MonoDevelop.Refactoring.TextReplaceChange+<>c.<FinishRefactoringOperation>b__22_0 (System.IDisposable grp) [0x00000] in /Users/vsts/agent/2.141.1/work/1/s/monodevelop/main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/Change.cs:92 
  at System.Collections.Generic.List`1[T].ForEach (System.Action`1[T] action) [0x0001e] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-08/external/bockbuild/builds/mono-x64/external/corefx/src/Common/src/CoreLib/System/Collections/Generic/List.cs:578 
  at MonoDevelop.Refactoring.TextReplaceChange.FinishRefactoringOperation () [0x0000a] in /Users/vsts/agent/2.141.1/work/1/s/monodevelop/main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/Change.cs:92 
  at MonoDevelop.Refactoring.RefactoringService.AcceptChanges (MonoDevelop.Core.ProgressMonitor monitor, System.Collections.Generic.IList`1[T] changes, MonoDevelop.Ide.ITextFileProvider fileProvider) [0x0024f] in /Users/vsts/agent/2.141.1/work/1/s/monodevelop/main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/RefactoringService.cs:191 
  at MonoDevelop.Refactoring.RefactoringService.AcceptChanges (MonoDevelop.Core.ProgressMonitor monitor, System.Collections.Generic.IList`1[T] changes) [0x00000] in /Users/vsts/agent/2.141.1/work/1/s/monodevelop/main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/RefactoringService.cs:125 
  at MonoDevelop.Refactoring.Rename.RenameItemDialog.OnOKClicked (System.Object sender, System.EventArgs e) [0x001b9] in /Users/vsts/agent/2.141.1/work/1/s/monodevelop/main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Rename/RenameItemDialog.cs:245 
ERROR [2018-10-29 16:20:27Z]: Error while renaming symbol ViewController
System.NullReferenceException: Object reference not set to an instance of an object
  at MonoDevelop.CodeActions.CodeActionEditorExtension.Editor_EndAtomicUndoOperation (System.Object sender, System.EventArgs e) [0x00000] in /Users/vsts/agent/2.141.1/work/1/s/monodevelop/main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeActions/CodeActionEditorExtension.cs:353 
  at (wrapper delegate-invoke) <Module>.invoke_void_object_EventArgs(object,System.EventArgs)
  at MonoDevelop.SourceEditor.SourceEditorView.OnEndUndo (System.EventArgs e) [0x0000a] in /Users/vsts/agent/2.141.1/work/1/s/monodevelop/main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs:2587 
  at MonoDevelop.SourceEditor.SourceEditorView.HandleEndUndo (System.Object sender, Mono.TextEditor.TextDocument+UndoOperationEventArgs e) [0x00000] in /Users/vsts/agent/2.141.1/work/1/s/monodevelop/main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs:352 
  at (wrapper delegate-invoke) System.EventHandler`1[Mono.TextEditor.TextDocument+UndoOperationEventArgs].invoke_void_object_TEventArgs(object,Mono.TextEditor.TextDocument/UndoOperationEventArgs)
  at Mono.TextEditor.TextDocument.OnEndUndo (Mono.TextEditor.TextDocument+UndoOperationEventArgs e) [0x0000a] in /Users/vsts/agent/2.141.1/work/1/s/monodevelop/main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/TextDocument.cs:1256 
  at Mono.TextEditor.TextDocument.EndAtomicUndo () [0x0005d] in /Users/vsts/agent/2.141.1/work/1/s/monodevelop/main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/TextDocument.cs:1215 
  at Mono.TextEditor.TextDocument+UndoGroup.Dispose () [0x00008] in /Users/vsts/agent/2.141.1/work/1/s/monodevelop/main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/TextDocument.cs:1175 
  at MonoDevelop.Refactoring.TextReplaceChange+<>c.<FinishRefactoringOperation>b__22_0 (System.IDisposable grp) [0x00000] in /Users/vsts/agent/2.141.1/work/1/s/monodevelop/main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/Change.cs:92 
  at System.Collections.Generic.List`1[T].ForEach (System.Action`1[T] action) [0x0001e] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-08/external/bockbuild/builds/mono-x64/external/corefx/src/Common/src/CoreLib/System/Collections/Generic/List.cs:578 
  at MonoDevelop.Refactoring.TextReplaceChange.FinishRefactoringOperation () [0x0000a] in /Users/vsts/agent/2.141.1/work/1/s/monodevelop/main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/Change.cs:92 
  at MonoDevelop.Refactoring.RefactoringService.AcceptChanges (MonoDevelop.Core.ProgressMonitor monitor, System.Collections.Generic.IList`1[T] changes, MonoDevelop.Ide.ITextFileProvider fileProvider) [0x0024f] in /Users/vsts/agent/2.141.1/work/1/s/monodevelop/main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/RefactoringService.cs:191 
  at MonoDevelop.Refactoring.RefactoringService.AcceptChanges (MonoDevelop.Core.ProgressMonitor monitor, System.Collections.Generic.IList`1[T] changes) [0x00000] in /Users/vsts/agent/2.141.1/work/1/s/monodevelop/main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/RefactoringService.cs:125 
  at MonoDevelop.Refactoring.Rename.RenameItemDialog.OnOKClicked (System.Object sender, System.EventArgs e) [0x001b9] in /Users/vsts/agent/2.141.1/work/1/s/monodevelop/main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Rename/RenameItemDialog.cs:245 
```

**Comment by Therzok** [comment]
Repro case:
* Create an iOS project
* Open ViewController.cs -> Rename on the type
* See error

**Comment by mkrueger** [comment]
@monojenkins backport release 7-7

**Comment by slluis** [comment]
@Therzok can you please verify again?

**Comment by slluis** [comment]
@monojenkins backport release 7-7

**Comment by slluis** [comment]
@monojenkins backport release-7.7

**Comment by Therzok** [comment]
Works for me now!

**Comment by Therzok** [comment]
@monojenkins backport release-7.7

**Pull request merged**
