### PR TITLE
AssemblySearchPaths cleanup

### PR DESCRIPTION
**Pull request by KirillOsenkov**

### CODE REVIEW

**Comment by KirillOsenkov** [comment]
I have yet to verify correctness that it still resolves from the right location and the resulting bundle has the same files, but it does give us ~5s improvement in RAR time:
image

Not great (esp. compared with almost 4 minutes of Csc), but hey.

**Comment by Therzok** [comment]
Is this on Windows or Mac?

**Comment by KirillOsenkov** [comment]
This is on Mac. Numbers on Windows are similar, also a ~5 second improvement:

image

**Comment by KirillOsenkov** [comment]
Huh, GitHub API rate limit exceeded:
https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-environment-logs&releaseId=165081&environmentId=599128

**Comment by KirillOsenkov** [comment]
OK I've verified that this change produces identical .dmg bundle contents.

**Pull request merged**
