### PR TITLE
D15 6 fix592988

### PR DESCRIPTION
**Pull request by mkrueger**
Test case:

Code should not flicker black while typing.

The /* should update next lines.

/* 
Code <- should be commented.

The old fix broke a work around that fixed the /* updating.

Fixes VSTS #594738.

### CODE REVIEW

**Comment by neerajdeshmukh** [comment]
Verified on Visual Studio Community 2017 for Mac Version 7.4.3 (build 10).
Issue is still reproducible, code lines are displayed as black.

Steps:
1. Create single view iOS application
2. Open main.cs file
3. Tap enter on line number 11 from last and Try writing some code on line number 12 (say UIApplication.ChangeOldKey )
4. Put /* before UIApplication.ChangeOldKey on line number 12 —> Observe next line is not displayed as black
5. Try to remove * from line number 12 and observe 

Actual: Code is still displayed as black on next line number 13 (when I move cursor then code color is getting changed)
Expected: Code should not be displayed as black after removing * and earlier colour base should be returned.

Build Gist: https://gist.github.com/neerajdeshmukh/248e0a0ee88ee825727cc18c51781e53
Build Taken From: https://code.internalx.com/Wrench/BuildDetails?buildId=c6b6c05ec2c912bbb19ea6e8b41ba1
Screencast: https://www.screencast.com/t/Vp4vtDqa

Note: I have checked at source code > Code formatting, all policies are set to DEFAULT

**Comment by mkrueger** [comment]
I can't repro https://screencast.com/t/P0SqU8l2DQ

**Comment by neerajdeshmukh** [comment]
I have following Text Editor Settings and still hitting issue with steps I mentioned above. Kindly let me know if I am doing something wrong.

1. https://screencast.com/t/LGIptvqIVN
2. https://www.screencast.com/t/sNgAFiLP34

**Comment by mkrueger** [comment]
I copied the settings : https://screencast.com/t/uSe5vWXtVSzD

We've a problem now :/

**Comment by mkrueger** [comment]
And with high sierra the same: https://screencast.com/t/9JjASt9jhwrN

From source code PoV it's not really understandable because that /* update is in another code part that's untouched now.

**Comment by neerajdeshmukh** [comment]
Getting the issue on sierra as well.
Screencast: https://www.screencast.com/t/LfCtQTnwhc
Logs attached to VSTS 594738

Steps:
1. Create single view iOS application
2. Open main.cs file
3. Tap enter on line number 11 from last and Try writing some code on line number 12 (say UIApplication.ChangeOldKey )
4. Put /* before UIApplication.ChangeOldKey on line number 12 —> Observe next line is not displayed as black
5. Put */ end of the line on line number 12 --> Observe only line number 12 should be commented
6. Now remove */ from line number 12 from end and from start remove * --> Observe

Actual: Code is displayed as black.
Expected: Following code should not be displayed as black

**Comment by neerajdeshmukh** [comment]
As requested, tried with mono 5.10.0.179 with gtk+ 2.24.23 as well.. still getting issue with 100% steps from following screencast on sierra as well as on High Sierra.
https://www.screencast.com/t/5FExX6cjU7b

**Comment by mkrueger** [comment]
Implemented another approach - I extracted now the logic for /* … */ and wrote unit tests for it.

Basically the old approach for the flickering update was the correct one it just killed the /* multi span update logic as side effect. 

However the multi step caching approach was always error prone - so removing it was correct - now I isolated the work around and underpinned it with tests so future updates don't break it. This approach is now a lot simpler than the one Neeraj tested. Maybe it was a machine difference after all.

**Comment by neerajdeshmukh** [comment]
Verified on Visual Studio Community 2017 for Mac Version 7.4.3 (build 9).
It is working fine now.

Build Gist: https://gist.github.com/neerajdeshmukh/916e519e5cb42eaea88d4986c4d3f00b
Screencast: https://www.screencast.com/t/55h0nO3X
Build Taken from: https://code.internalx.com/Wrench/BuildDetails?buildId=c6b6c05ec2c912bbb19ea6e8b41ba1

**Pull request merged**
