### PR TITLE
Apply simple optimizations on MSBuild glob expander

### PR DESCRIPTION
**Pull request by Therzok**
Ports parts of https://github.com/mono/monodevelop/pull/8249

### CODE REVIEW

**Comment by Therzok** [comment]
@monojenkins rebase

**Comment by Therzok** [comment]
@monojenkins rebase

**Comment by Therzok** [comment]
@monojenkins rebase

**Review by jtorres — APPROVED** [review]

**Comment by Therzok** [comment]
@monojenkins backport release-8.4

**Pull request merged**
