### PR TITLE
[Core] Save user preferences in subdirectory

### PR DESCRIPTION
**Pull request by mrward**
The solution's user preferences file (SolutionName.userprefs) is now
saved in a subdirectory. For MonoDevelop this is:

  .md/SolutionName/v7/UserPrefs.xml

For Visual Studio:

  .vs/SolutionName/mac-v7/UserPrefs.xml

### CODE REVIEW

**Comment by slluis** [comment]
I'm not sure we need .md for MonoDevelop. We could just use .vs for MD and VSMac.

**Comment by mrward** [comment]
The implementation is based on that suggested by @mhutch in the VSTS work item.

If we do not do this what should happen on Linux or Windows for the directory part that includes the version number? Presumably we do not want mac-v7 on these operating systems or do we? I am assuming `mac` was added to prevent it clashing with VS on Windows.

**Comment by slluis** [comment]
We can use the `xs` prefix instead of `mac`.

**Comment by mrward** [comment]
So same location for MonoDevelop and VS Mac: `.vs/SolutionName/xs-v7/UserPrefs.xml`

**Comment by mrward** [comment]
Updated the code to use the new location.

**Comment by slluis** [comment]
I don't think the version number in the `xs-v7` should be tied to the VSMac version. I would just use `xs`. If we ever have to break the format, we can add the version number.

**Comment by mrward** [comment]
Removed the version from the directory name now.

**Comment by mrward** [comment]
QA have now tested/verified this pull request.

**Comment by mhutch** [comment]
@mrward @Therzok we should probably have an API for this directory so the persistent storage can get it, right? :)

**Comment by Therzok** [comment]
Currently has its own https://github.com/mono/monodevelop/commit/2d36e086f4f79e1c7dd81f5b4ab7b04439ef00c0#diff-bc6326fe96c7b2ac6c3563e5b2fce924R51

**Pull request merged**
