### PR TITLE
[61102][Mac] Fix open project dialog on High Sierra

### PR DESCRIPTION
**Pull request by sevoku**
Changing the layout of the NSSavePanel AccessoryView does not work on High Sierra, which seems to always enforce initial constraints resulting in a wrong layout:

grafik

With this patch the accessory view layout remains always the same and it just enables/disables the "Close current workspace" checkbox:

grafik
grafik

(fixes bug #61102)

### CODE REVIEW

**Comment by hbons** [comment]
- [ ] "Show files" -> "Show Files"

**Comment by vancura** [comment]
Also, way too many spaces between _Encoding:_ and _Auto Detected_. Or is that column left-aligned? It should be right-aligned.

By any chance, have you checked what it does with more verbose languages like German? I am afraid what could happen if these labels are multiline.

**Comment by sevoku** [comment]
ok, I've fixed the alignments:

grafik

and it works fine with German:

grafik

@vancura the labels are always single-line.

**Comment by slluis** [comment]
Can this be merged?

**Pull request merged**
