### PR TITLE
Don't deploy Microsoft.Build.Tasks.Core.dll.

### PR DESCRIPTION
**Pull request by KirillOsenkov**
We don't deploy the 3 other MSBuild dlls, so let's not deploy this one.
MSBuild is taken from the toolset that's installed separately from MonoDevelop. Otherwise we might run into situations where our own copy is loaded instead of the official one and cause a mismatch.

### CODE REVIEW

**Comment by Therzok** [comment]
Does the IDE still work without this?

**Comment by Therzok** [comment]
Yep, this breaks the IDE

**Comment by KirillOsenkov** [comment]
Pushed a fix. cc @rodrmoya

**Comment by Therzok** [comment]
Let's see if VSTS is happy

**Comment by KirillOsenkov** [comment]
VSTS is happy! :)

**Pull request merged**
