### PR TITLE
[58836][Ide] Fix breadcrumb dropdown sizing

### PR DESCRIPTION
**Pull request by sevoku**
Layout must be configured during initialization for initial window sizing.

(fixes bug #58836)

### CODE REVIEW

**Comment by mkrueger** [comment]
Doesn't work for me for:

public class Foo1234567890123456789012345678901234567890123456
{ }

**Comment by sevoku** [comment]
@mkrueger how exactly? Can you make a screenshot?

This is how it should look like:
grafik

grafik
grafik

So no ellipsis/wrap if `width<400`, ellipsis if `text-length>400`.

**Comment by mkrueger** [comment]
Don't have another foo in the list - that's the only one.

**Comment by sevoku** [comment]
Ok, it seems to be good on Linux too,
before:
grafik
with this patch:
grafik
But still not perfect:
grafik

It's related to the missing HiDPI support on Linux, making the list exceed the 450px limit, but still better than before.

**Pull request merged**
