### PR TITLE
Add MonoDevelop.MonoDroid InternalsVisibleTo in MonoDevelop.Ide

### PR DESCRIPTION
**Pull request by bratsche**
This will be needed in order to use InfoBars by https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/646093

### CODE REVIEW

**Comment by bratsche** [comment]
@slluis I'm not sure what you mean. I want to use `Workbench.ShowInfoBar()` but it's marked as `internal`. I didn't see a public way of doing this.

**Comment by bratsche** [comment]
@slluis The API I want to use is marked `internal`. I asked @Therzok about it and he suggested I add `InternalsVisibleTo`. Should we make it public instead?

**Comment by slluis** [comment]
If we need to use it in an add-in it should be public, unless there is a very good reason not to.

**Comment by Therzok** [comment]
I didn't want to open up the API when I first wrote it.

I guess the API can look like this, if we want to make it public:
```
	public interface IInfoBarHost
	{
		Control AddInfoBar (InfoBarOptions options);
	}

 	public class InfoBarOptions
    	{
		public InfoBarItem[] Items { get; set; }

		public InfoBarOptions(string description)
                 {
                 }
	}
```

And we add `IInfoBarHost` to `Workbench` which would route into `DefaultWorkbench`’s `IInfoBarHost` implementation.

**Comment by bratsche** [comment]
Closing in favor of https://github.com/mono/monodevelop/pull/5877

**Comment by Therzok** [comment]
See https://github.com/mono/monodevelop/pull/5878

**Pull request closed without merging**
