### PR TITLE
Fixed 'Bug 57866 - [VSFeedback Ticket] #443161 - quick actions new

### PR DESCRIPTION
**Pull request by mkrueger**
type tooltip preview obscures the context menu'

Was a complex fix because os x doesn't let me get the submenu position
- so the solution was a work around: position the tooltip around the
context menu but not at the right side.

### CODE REVIEW

**Comment by slluis** [comment]
What are all those changes in ContextMenuExtensionsMac.cs required for?

**Comment by mkrueger** [comment]
Basically a code cleanup. I hoped to get the submenu location somehow and removed my old work around - but it seems not to be a way to get it :/.

**Comment by slluis** [comment]
@mkrueger @Therzok we were having a discussion here. What doesn't work about getting the location of a menu?

**Comment by Therzok** [comment]
Oh, I missed the comments.

**Pull request merged**
