### PR TITLE
Properly add stacktraces to exceptions

### PR DESCRIPTION
**Pull request by Therzok**
cc @mrward 

Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/897159

### CODE REVIEW

**Comment by Therzok** [comment]
@monojenkins backport release-8.1

**Review by jstedfast — APPROVED** [review]

**Review by mrward — APPROVED** [review]

**Comment by Therzok** [comment]
@monojenkins backport release-8.1

**Comment by Therzok** [comment]
cc @leculver

**Review by slluis — APPROVED** [review]

**Comment by Therzok** [comment]
@monojenkins backport release-8.2

**Pull request merged**
