### PR TITLE
Consolidate VS Editor NuGet references in a single file.

### PR DESCRIPTION
**Pull request by KirillOsenkov**
Import that file in projects that want VS Editor references.

### CODE REVIEW

**Comment by KirillOsenkov** [comment]
If this looks good, I can do the same for Roslyn references, so we can update the version in one place (well, two places!)

**Comment by KirillOsenkov** [comment]
We need this because we're going to be incrementing VS Editor and Roslyn versions much more often soon.

**Comment by KirillOsenkov** [comment]
Hmm, weird test case failure:
```          <test-case name="Xamarin.Forms.Addin.Tests.XamlCodeCompletion.BraceInsideAttribute" executed="True" result="Failure" success="False" time="1.418" asserts="1">
            <failure>
              <message><![CDATA[  Expected string length 258 but was 257. Strings differ at index 238.
  Expected: "...les.HelloXamlPage">\n\t\t\t\t<Grid IsEnabled="}" />\n</ContentPage>"
  But was:  "...les.HelloXamlPage">\n\t\t\t\t<Grid IsEnabled="" />\n</ContentPage>"
  ------------------------------------------------------------^
]]></message>
              <stack-trace><![CDATA[  at Xamarin.Forms.Addin.Tests.XamlCodeCompletion+<BraceInsideAttribute>d__16.MoveNext () [0x000c0] in <2bfaca2cfbf4431dad1be05a26824d5c>:0 
]]></stack-trace>
            </failure>
          </test-case>```

**Comment by slluis** [comment]
Looks good, once the issue is fixed.

**Comment by KirillOsenkov** [comment]
The failure is an unrelated issue and @DavidKarlas is going to look into it.

**Pull request merged**
