### PR TITLE
Bug 34569 - [Regression] Project references don't handle Condition attributes

### PR DESCRIPTION
**Pull request by DavidKarlas**
I'm pretty sure this is OK fix, but would prefer quick review by you @slluis 

Thank you

### CODE REVIEW

**Comment by slluis** [comment]
Can you please add unit tests?

**Comment by DavidKarlas** [comment]
Ok

**Comment by DavidKarlas** [comment]
Updated with unit tests

**Comment by slluis** [comment]
Thanks!

**Pull request merged**
