### PR TITLE
[build] Don't use the API which has been obsoleted

### PR DESCRIPTION
**Pull request by alanmcgovern**
WarnAsError is on so we should make this change to avoid
breaking the build.

### CODE REVIEW

**Comment by mrward** [comment]
@rodrmoya opened a similar pull request - #6229

**Comment by mrward** [comment]
I don't think this will build since md-addins still uses Xamarin.Mac 4.4.1. Rodrigo's pull request had an md-addins change to use a more recent Xamarin.Mac.

**Comment by rodrmoya** [comment]
Right, it needs the bump to the newest XM in md-addins, but haven't been able to make my 2 PRs build correctly on VSTS, they always fail in forms tests :/

**Comment by Therzok** [comment]
@rodrmoya have you rebased them!

**Comment by rodrmoya** [comment]
yes, several times, just did, and the other that was failing (not related to XM bump) seems to work, but not this one and the related md-addins one, so I guess those tests are affected by Xcode10 upgrade now.

Will investigate further

**Comment by alanmcgovern** [comment]
We're still blocked from easily compiling VSM :(

**Comment by alanmcgovern** [comment]
I'll just close this in favour of the other one.

**Comment by rodrmoya** [comment]
I just bumped the other one to latest master, let's see if tests run ok on VSTS now

**Pull request closed without merging**
