### PR TITLE
Fixed 'Bug 58488 - Breakpoint highlighting not visible'

### PR DESCRIPTION
**Pull request by mkrueger**
+ Turned on highlighting
+ The current line marker is now displayed in the empty space left of
the line numbers and not on top of the icon marker.

### CODE REVIEW

**Comment by slluis** [comment]
The invocation marker should be shown in that area too:
captura de pantalla 2017-08-16 a les 18 56 56

**Comment by mkrueger** [comment]
This makes it in fact easier to implement :).

**Comment by DavidKarlas** [comment]
image
Looks like this is not handling files with 100+ lines nicely, this looks like it's overlapping.

**Comment by vancura** [comment]
Please ping me or add @hbons and/or me as reviewers next time you create a design-related PR. We need to know about changes like this one. Thanks!

**Pull request merged**
