### PR TITLE
Bump roslyn to 15.8 in 7.6

### PR DESCRIPTION
**Pull request by Therzok**
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/657354

### CODE REVIEW

**Comment by Therzok** [comment]
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/657354

**Comment by slluis** [comment]
Editor unit tests are still failing after re-run. Something is not right.

**Comment by Therzok** [comment]
Didn't we say we don't want it in 15.8 because there's more patches to backport? (RE analyzer fixes, some fixes in master) If we want to bump this, I'll backport the fixes

**Comment by Therzok** [comment]
Let's see if they pass now.

**Comment by Therzok** [comment]
They pass locally, and there's nothing in the logs.

**Comment by slluis** [comment]
We are not bumping roslyn in 7.6 for now.

**Pull request closed without merging**
