### PR TITLE
[Editor] Add counter information and various data points

### PR DESCRIPTION
**Pull request by Therzok**
To help pin down possible slowdowns in the editor

Fixes VSTS 675548 - Research typing delays

### CODE REVIEW

**Comment by iainx** [comment]
In a future revision of this patch, would it be useful to have individual margin drawing times as well?

**Comment by Therzok** [comment]
It's on my list, might be added in this PR. Making it so TextEditorKeyPressTimings is accessible from the textarea, texteditorextensions and the margins so they can checkpoint on their own so we can further pin down what's taking up time.

**Comment by Therzok** [comment]
@slluis ping?

**Comment by Therzok** [comment]
@monojenkins backport release-7.6

**Comment by Therzok** [comment]
@monojenkins backport release-7.7

**Pull request merged**
