### PR TITLE
[Core] Remove custom framework definitions

### PR DESCRIPTION
**Pull request by mhutch**
We get all target framework definitions via MSBuild now.

Fixes old MD framework names overriding the system ones.

### CODE REVIEW

**Comment by mhutch** [comment]
@slluis is this okay or is it too invasive for 15.2?

**Comment by mhutch** [comment]
So we'll have these dead APIs stuck around for the whole 7.x series? :(

**Comment by mhutch** [comment]
Rebased to master anyways

**Comment by mhutch** [comment]
Okay, now it just removes the framework definitions. The removal of the underlying feature has moved to https://github.com/mono/monodevelop/pull/2204.

OK now?

**Comment by slluis** [comment]
What does this fix specifically? The branch is frozen, so unless there is a major bug fixed by this PR we can't merge it.

**Comment by mhutch** [comment]
It fixes inconsistencies in framework names in the target framework list in project options.

**Comment by slluis** [comment]
This can wait for 15.3 then.

**Comment by mhutch** [comment]
Since this approach won't be accepted for 15.2, even though it's clearly the correct fix, I'm moving it to my separate 15.3 PR.

Filed a bug for the underlying issue to be fixed for 15.2: https://bugzilla.xamarin.com/show_bug.cgi?id=55331

**Pull request closed without merging**
