### PR TITLE
[AspNetCore] Properly disables folder publishing

### LINKED ISSUE #6465: Publish menu available for all project types
VSMac: 7.7.0.1750
Git revision: 743007e584bcc371b4f8314c199cfce858ebc7da
Build date: 2018-10-24 17:03:24+00
Build branch: release-7.7
Xamarin extensions: 4eb7bc2cc6d74dadc5b397d8c5c13f334bc258b3

The Publish menu is available for all project types. If you try to publish in a non .NET Core project, such as a C# console project, it will fail.

```
dotnet publish
Microsoft (R) Build Engine version 15.7.179.6572 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Nothing to do. None of the projects specified contain packages to restore.
/usr/local/share/dotnet/sdk/2.1.302/Microsoft.Common.CurrentVersion.targets(1179,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.7" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [test.csproj]
The application was terminated by a signal: SIGHUP

dotnet publish returned: 1
```

The Publish menu should only be visible/enabled for .NET Core projects.

Also the Publish menu is available for every item in the Solution pad. Right clicking a file or a folder shows the Publish menu. Not sure if that is expected since you cannot publish an individual file or folder presumably.

> VS bug [#715107](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/715107)

### LINKED ISSUE #6468: Null reference when Publish to folder for solution selected
VS Mac: 7.7.0.1750
Git revision: 743007e584bcc371b4f8314c199cfce858ebc7da
Build date: 2018-10-24 17:03:24+00
Build branch: release-7.7
Xamarin extensions: 4eb7bc2cc6d74dadc5b397d8c5c13f334bc258b3

1. Create a new .NET Core console project.
2. Right click the solution and select Publish - Publish to Folder.
3. Dialog is not displayed. IDE log has error:

```
Failed to publish project
System.NullReferenceException: Object reference not set to an instance of an object
  at MonoDevelop.AspNetCore.Dialogs.PublishToFolderDialog.get_BinBaseUri () [0x00000] in /Users/vsts/agent/2.141.1/work/1/s/monodevelop/main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Dialogs/PublishToFolderDialog.cs:26 
  at MonoDevelop.AspNetCore.Dialogs.PublishToFolderDialog.Initialize () [0x00131] in /Users/vsts/agent/2.141.1/work/1/s/monodevelop/main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Dialogs/PublishToFolderDialog.cs:69 
  at MonoDevelop.AspNetCore.Dialogs.PublishToFolderDialog..ctor (MonoDevelop.AspNetCore.Commands.PublishCommandItem publishCommandItem) [0x0000d] in /Users/vsts/agent/2.141.1/work/1/s/monodevelop/main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Dialogs/PublishToFolderDialog.cs:35 
  at (wrapper remoting-invoke-with-check) MonoDevelop.AspNetCore.Dialogs.PublishToFolderDialog..ctor(MonoDevelop.AspNetCore.Commands.PublishCommandItem)
  at MonoDevelop.AspNetCore.Commands.PublishToFolderBaseCommandHandler.Run (System.Object dataItem) [0x00026] in /Users/vsts/agent/2.141.1/work/1/s/monodevelop/main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Commands/PublishToFolderBaseCommandHandler.cs:30 

```

Possibly this could be fixed by only enabling the Publish menu when the project node is selected.

> VS bug [#715111](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/715111)

### PR DESCRIPTION
**Pull request by jtorres**
- When does not support Folder Publishing then sets item to Visible = false

Fixes VSTS #715107
Fixes #6465  
Fixes #6468

### CODE REVIEW

**Comment by jtorres** [comment]
@mrward let me take a look, if it's easy I could add it here... will let you know

**Comment by mrward** [comment]
I opened another issue for the menu being available at the solution tree node - #6468

**Comment by slluis** [comment]
You can add the flag `disabledVisible="False"` to the command items in the publish menu, like this:
https://github.com/mono/monodevelop/blob/939880c2f7f09bb23b8c7eef4422a612e3ff747e/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/ProjectPadContextMenu.addin.xml#L124

When the command doesn't apply to an item it will be disabled, and by setting that attribute it will be hidden, and since the ItemSet has autohide=true, the whole menu should be hidden.

**Comment by jtorres** [comment]
@mrward the first commit also fixes this issue #6468 I told you to stand by,, 

The second one ensures that Publish is only available for Project type items.. 

Please let me know if there is anything I should add here,, thanks

**Comment by jtorres** [comment]
@monojenkins backport release-7.7

**Pull request merged**
