### PR TITLE
[Ide] Fix NRE when determining if the LogView should auto scroll.

### PR DESCRIPTION
**Pull request by sgmunn**

### CODE REVIEW

**Comment by slluis** [comment]
PR #1384 intends to fix the same issue.

**Comment by slluis** [comment]
BTW #1384 should be fixing the root of the problem. I prefer that solution if it really works.

**Comment by sgmunn** [comment]
Good to know, thanks

**Comment by Therzok** [comment]
The changes done that caused this issue to surface are not part of Cycle7. Closing this PR as the other one has been merged.

**Pull request closed without merging**
