### PR TITLE
Fixes issue #6649 Line height has changed in v8.0

### PR DESCRIPTION
**Pull request by mkrueger**
The calculation has changed to fix another bug but the spacing was too high. This should correct it

### CODE REVIEW

**Comment by mkrueger** [comment]
@monojenkins backport release-7.8

**Comment by slluis** [comment]
Height is now a bit shorter than current stable. Can you make it the same height?

**Comment by mkrueger** [comment]
Should match now other os x editors - can anyone verify that ?

**Comment by Therzok** [comment]
Looks good to me

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #3360 merged by: Dmytro Ovcharov
Author: mono
Commit: 078ca687c7ce42ed86ce47bd742f2dc61060816a (xamarin/monodevelop)

**Pull request merged**
