### PR TITLE
Fixes issue #5590 Alt-shift-left/right no longer extends selection

### PR DESCRIPTION
**Pull request by mkrueger**

### CODE REVIEW

**Comment by Therzok** [comment]
Can we add some tests?

**Comment by mhutch** [comment]
@KirillOsenkov any ideas? Looks like Roslyn's AbstractTextStructureNavigatorProvider.TextStructureNavigator.cs is getting used here

**Comment by KirillOsenkov** [comment]
Adding @grabalon who investigated this recently.

**Comment by KirillOsenkov** [comment]
@grabalon just stopped by and we discussed this. Basically if you're at the start of a comment, Roslyn reports the whole comment as a "word". Hence the behavior you're seeing. 

He has an internal PR (https://devdiv.visualstudio.com/DevDiv/Editor/_git/VS-Platform/pullrequest/135348?_a=overview) where he works around it by looking at the next character, and then asking for the word extent of that.

If you look into his PR, look in SelectionTransformer.cs change.

**Comment by mhutch** [comment]
@KirillOsenkov I can see from the code that's the intended behavior. However, right now it skips from _anywhere within the comment_ to the end, so something is broken.

**Comment by mkrueger** [comment]
The behavior on linux is different it works there - so it must be something in the os x implementation causing that. However I can't find any difference :/

**Pull request merged**
