### PR TITLE
Fix important translation mistakes in Japanese

### PR DESCRIPTION
**Pull request by matyapiro31**
This bug fix a misswritten translation in C# code.
If the translation used,the exception may be thrown.

### CODE REVIEW

**Comment by monoadmin** [comment]
Hello! I'm the build bot for the Mono project. I need approval from a Mono team member to build this pull request. A team member should reply with "approve" to approve a build of this pull request, "whitelist" to whitelist this and all future pull requests from this contributor, or "build" to explicitly request a build, even if one has already been done. Contributors can ignore this message.

**Comment by slluis** [comment]
whitelist

**Comment by matyapiro31** [comment]
@slluis
By the way ,I want Monodevelop to add Bazaar version control.
How do you think that?

**Comment by slluis** [comment]
Any contribution is welcome!

**Comment by matyapiro31** [comment]
Bazaar has mostly same commands as subversion (though they use diffrent term each other),
probably use same widgets and source file of git and subversion.
Can I do this in this Google Summer of Code?

**Comment by mhutch** [comment]
Yes, it seems like a reasonable Summer of Code project, assuming a mentor is available.

**Comment by atsushieno** [comment]
Both of the changes don't look important at all. Actually very cosmetic. No need to merge.

**Comment by Therzok** [comment]
Closing as per lack of activity and merge conflicts.

**Pull request closed without merging**
