### PR TITLE
[Debugger] Handle case when the text snapshot has less lines than the breakpoint location

### PR DESCRIPTION
**Pull request by sgmunn**
Fixes VSTS 958245
System.ArgumentOutOfRangeException exception in Microsoft.VisualStudio.Text.Implementation.BinaryStringRebuilder.GetLineFromLineNumber()
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/958245

---

I think the location end line is '1' based from where we subtract 1 from it to GetLineFromLineNumber but I might be wrong there.

### CODE REVIEW

**Comment by jstedfast** [comment]
Seems reasonable

**Comment by sgmunn** [comment]
working on a test for it

**Comment by sgmunn** [comment]
@DavidKarlas does this look correct to you?

**Comment by sgmunn** [comment]
@monojenkins backport release-8.4

**Comment by sgmunn** [comment]
@monojenkins backport release-8.3

**Pull request merged**
