### PR TITLE
[Debugger] Implement Set Next Statement for the VsCode debugger backend

### PR DESCRIPTION
**Pull request by jstedfast**
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/698194/

### CODE REVIEW

**Comment by slluis** [comment]
Can we have unit tests for this?

**Comment by jstedfast** [comment]
@slluis that's one of the next storyboards in my list of tasks (add unit tests for the vscode backend).

Right now there aren't any unit tests for the vscode backend so adding unit tests for this right now is impossible.

**Comment by slluis** [comment]
@monojenkins backport release-8.1

**Comment by jstedfast** [comment]
The failed unit test is Xamarin.Forms and is unrelated to this change.

**Pull request merged**
