### PR TITLE
[Ide] Add user installed addins into the about dialog

### PR DESCRIPTION
**Pull request by Therzok**

### CODE REVIEW

**Comment by Therzok** [comment]
cc @DavidKarlas you'll love me.

**Comment by DavidKarlas** [comment]
Maybe just add
```csharp
if(AddinManager.Registry.GetModules (AddinSearchFlags.IncludeAddins | AddinSearchFlags.LatestVersionsOnly)
.Any (addin => addin.IsUserAddin && addin.Enabled)){

}
```

**Comment by Therzok** [comment]
What do you mean? Only print that line if any exists?

**Comment by DavidKarlas** [comment]
Ye, why spam if none exists?

**Comment by Therzok** [comment]
@DavidKarlas happy now?

**Pull request merged**
