### PR TITLE
[F#] Update to FSharp.CompilerService 31.0

### PR DESCRIPTION
**Pull request by mrward**
- Update to FSharp.CompilerService 31.0
- Update Fantomas to 3.0.0-beta-002

F# interactive problems:

- One of the F# Interactive tests is failing. The output is different.
- The F# Interactive pad window also does not display its version (e.g. `Microsoft (R) F# Interactive version 10.2.3 for F# 4.5)` so I suspect something is wrong here. I am assuming that we need to update Mono's fsharpi.

Fixes VSTS #971169 - Update to latest FSharp.CompilerService

### CODE REVIEW

**Comment by nosami** [comment]
The interactive output is fine. I would just change the test to match the output.

Never noticed this error before though... don't know if it's important or if it's related to your change

```
2019-08-22T23:15:10.9875510Z ERROR: System.Threading.ThreadAbortException: Thread was being aborted.
2019-08-22T23:15:10.9877500Z   at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_threads_state_poll()
2019-08-22T23:15:10.9877890Z   at MonoDevelop.Projects.MSBuild.ProjectBuilder.Dispose () <0x10cd2f250 + 0x0002a> in <d3584f0397614eb39dbf3df4425bdc1e>:0 
2019-08-22T23:15:10.9878280Z   at MonoDevelop.Projects.MSBuild.BuildEngine.UnloadProject (MonoDevelop.Projects.MSBuild.ProjectBuilder pb) [0x00001] in /Users/vsts/agent/2.155.1/work/1/s/monodevelop/main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.MSBuild/BuildEngine.cs:65 
2019-08-22T23:15:10.9878720Z   at MonoDevelop.Projects.MSBuild.BuildEngine.UnloadProject (MonoDevelop.Projects.MSBuild.UnloadProjectRequest msg) [0x00057] in /Users/vsts/agent/2.155.1/work/1/s/monodevelop/main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.MSBuild/BuildEngine.Shared.cs:148 
2019-08-22T23:15:10.9879870Z   at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
2019-08-22T23:15:10.9881500Z   at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00079] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-06/external/bockbuild/builds/mono-x64/mcs/class/corlib/System.Reflection/RuntimeMethodInfo.cs:397 
2019-08-22T23:15:10.9884430Z   at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-06/external/bockbuild/builds/mono-x64/external/corefx/src/Common/src/CoreLib/System/Reflection/MethodBase.cs:53 
2019-08-22T23:15:10.9884910Z   at MonoDevelop.Core.Execution.MessageListener.ProcessMessage (MonoDevelop.Core.Execution.BinaryMessage msg) [0x00019] in /Users/vsts/agent/2.155.1/work/1/s/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Core.Execution/BinaryMessage.cs:858 
2019-08-22T23:15:10.9885340Z   at MonoDevelop.Core.Execution.RemoteProcessServer+MessageListenerHandler.ExecuteMessage (MonoDevelop.Core.Execution.BinaryMessage msg) [0x00029] in /Users/vsts/agent/2.155.1/work/1/s/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Core.Execution/RemoteProcessServer.cs:311 
```

**Comment by nosami** [comment]
Mono's fsharpc and fsharpi should ideally match the FCS that we use in VSMac.

It can be changed here https://github.com/mono/mono/blob/master/packaging/MacSDK/fsharp.py

**Comment by mrward** [comment]
The ThreadAbortException happens for other tests. You can see it when running MonoDevelop.Core or MonoDevelop.Ide tests locally. Can happen when a project is disposed and the msbuild host is forcefully shutdown.

I looked at the commit associated with that mono change. Seemed to be more complicated than changing a commit hash and so I stopped looking at it 😄

**Comment by nosami** [comment]
It should just be a commit hash change in fsharp.py. The last bump was unusually complicated but it should be easy this time :) If it fails, give me a shout and I can take a look at it.

**Comment by nosami** [comment]
The OSS F# repo got moved to here https://github.com/dotnet/fsharp/

**Comment by nosami** [comment]
@monojenkins backport release-8.3

**Comment by nosami** [comment]
re: https://github.com/dotnet/fsharp/issues/7367

**Comment by mrward** [comment]
Is this OK to include without any Mono changes?

I was wondering about the F# interactive output since it does not indicate the version when I was testing this branch. It was displaying something like this:

`Microsoft (R) F# Interactive version   for F# 4.5`

Compared to:

`Microsoft (R) F# Interactive version 10.2.3 for F# 4.5`

**Comment by nosami** [comment]
@mrward We don't have an easy path to update the compiler in Mono right now. We need the fix regardless for F# / .Net Core which has a newer command line compiler than Mono.

After talking to @dsyme about the roadmap, the plan is to ship a newer compiler in the IDE than the command line compiler that we ship with Mono.

The header in the F# interactive pad output is slightly different to fsharpi - it always has been.

**Comment by mrward** [comment]
The difference in F# interactive output was between VS Mac 8.3 and this branch in the interactive pad in VS Mac. I was not checking fsharpi from the command line. I was wondering why this would have changed.

**Comment by mrward** [comment]
Going to redo the release-8.3 backport since it had some errors which have been fixed in that branch.

@monojenkins backport release-8.3

**Comment by nosami** [comment]
> The difference in F# interactive output was between VS Mac 8.3 and this branch in the interactive pad in VS Mac. I was not checking fsharpi from the command line. I was wondering why this would have changed.

I understand your previous comment now about fsharpi... the F# Interactive pad isn't powered by fsharpi at all. It is powered by FCS - something must have changed in there but it's nothing to worry about.

**Pull request merged**
