### PR TITLE
Bump Roslyn to 3.5.0-beta2-19603-01

### PR DESCRIPTION
**Pull request by sandyarmstrong**
Updating Roslyn to 20191203.1 (https://github.com/dotnet/roslyn/commit/2906b5)

[Changes](https://github.com/dotnet/roslyn/compare/ff930de...2906b5?w=1)  since [ff930de](https://www.github.com/dotnet/roslyn/commit/ff930de):
- [Update dependencies from https://github.com/dotnet/arcade build 20191201.1 (#40084)](https://www.github.com/dotnet/roslyn/pull/40084)
- [Update list of C# Next features and reviewers (#39987)](https://www.github.com/dotnet/roslyn/pull/39987)
- [Update dependencies from https://github.com/dotnet/arcade build 20191130.1 (#40075)](https://www.github.com/dotnet/roslyn/pull/40075)
- [[master] Update dependencies from dotnet/arcade (#40065)](https://www.github.com/dotnet/roslyn/pull/40065)
- [Update dependencies from https://github.com/dotnet/arcade build 20191127.4 (#40057)](https://www.github.com/dotnet/roslyn/pull/40057)
- [Merge pull request #39745 from allisonchou/ExtractLocalFunction](https://www.github.com/dotnet/roslyn/pull/39745)
- [Merge pull request #40017 from allisonchou/InferredTupleNamesBug](https://www.github.com/dotnet/roslyn/pull/40017)
- [Update dependencies from https://github.com/dotnet/arcade build 20191126.2 (#40036)](https://www.github.com/dotnet/roslyn/pull/40036)
- [Always restore when running a bootstrap build (#40025)](https://www.github.com/dotnet/roslyn/pull/40025)
- [DiagnosticIncrementalAnalyzer refactoring (#39956)](https://www.github.com/dotnet/roslyn/pull/39956)
- [Merge pull request #39655 from CyrusNajmabadi/storageLocation](https://www.github.com/dotnet/roslyn/pull/39655)
- [Merge pull request #39938 from jasonmalinowski/delete-some-liveshare-language-service-code](https://www.github.com/dotnet/roslyn/pull/39938)
- [Move reporting of iterator diagnostics to avoid race condition (#39990)](https://www.github.com/dotnet/roslyn/pull/39990)
- [Update dependencies from https://github.com/dotnet/arcade build 20191125.7 (#40020)](https://www.github.com/dotnet/roslyn/pull/40020)
- [Fix NGEN priority of csc.exe, vbc.exe, csi.exe (#40016)](https://www.github.com/dotnet/roslyn/pull/40016)
- [Extra check for EnumeratorCancellation parameter type (#39978)](https://www.github.com/dotnet/roslyn/pull/39978)
- [Extend profiling inputs drop time to 90 days (#40009)](https://www.github.com/dotnet/roslyn/pull/40009)
- [Update dependencies from https://github.com/dotnet/arcade build 20191124.1 (#40005)](https://www.github.com/dotnet/roslyn/pull/40005)
- [Merge pull request #39982 from genlu/BucketTelemetry](https://www.github.com/dotnet/roslyn/pull/39982)
- [Emit CS8370 instead of CS1674 for ref struct disposable (#39949)](https://www.github.com/dotnet/roslyn/pull/39949)
- [Update dependencies from https://github.com/dotnet/arcade build 20191123.1 (#39997)](https://www.github.com/dotnet/roslyn/pull/39997)
- [[master] Update dependencies from dotnet/arcade (#39965)](https://www.github.com/dotnet/roslyn/pull/39965)
- [Merge pull request #39980 from mavasani/MoveType](https://www.github.com/dotnet/roslyn/pull/39980)
- [Do not convert PDBs when building bootstrap compiler (#39972)](https://www.github.com/dotnet/roslyn/pull/39972)
- [Merge pull request #39973 from mavasani/WorkCoordinatorShouldRespectRunAnalyzers](https://www.github.com/dotnet/roslyn/pull/39973)
- [Avoid warning assigning to readonly property marked [AllowNull] (#39939)](https://www.github.com/dotnet/roslyn/pull/39939)
- [Merge pull request #39958 from CyrusNajmabadi/genHashCodeVar](https://www.github.com/dotnet/roslyn/pull/39958)
- [Merge pull request #39957 from DavidKarlas/patch-3](https://www.github.com/dotnet/roslyn/pull/39957)
- [Merge pull request #39955 from mavasani/FixIVTBreak](https://www.github.com/dotnet/roslyn/pull/39955)
- [Merge pull request #39945 from dotnet/dev/jorobich/skip-analyzers4](https://www.github.com/dotnet/roslyn/pull/39945)
- [Merge pull request #39944 from dotnet/dev/jorobich/skip-analyzers3](https://www.github.com/dotnet/roslyn/pull/39944)
- [Merge pull request #39942 from dotnet/dev/jorobich/skip-analyzers](https://www.github.com/dotnet/roslyn/pull/39942)
- [Merge pull request #39813 from genlu/TypeImportPerf](https://www.github.com/dotnet/roslyn/pull/39813)
- [Merge pull request #39910 from jasonmalinowski/decouple-command-filters-and-contained-documents-from-language-service](https://www.github.com/dotnet/roslyn/pull/39910)
- [Track additional state for "maybe null even if not nullable" (#39778)](https://www.github.com/dotnet/roslyn/pull/39778)
- [Update Arcade yml files (#39919)](https://www.github.com/dotnet/roslyn/pull/39919)
- [[master] Update dependencies from dotnet/arcade (#39884)](https://www.github.com/dotnet/roslyn/pull/39884)
- [Address a number of variance safety issues with code in interfaces. (#39839)](https://www.github.com/dotnet/roslyn/pull/39839)
- [Merge pull request #39735 from nbalakin/issue/34239](https://www.github.com/dotnet/roslyn/pull/39735)
- [Merge pull request #39699 from mavasani/ActiveFileAnalysisScope](https://www.github.com/dotnet/roslyn/pull/39699)
- [Merge pull request #39885 from JoeRobich/revert-arcade-changes](https://www.github.com/dotnet/roslyn/pull/39885)
- [Merge pull request #39756 from CyrusNajmabadi/implementImplicitly](https://www.github.com/dotnet/roslyn/pull/39756)
- [Fix crash in LocalRewriter.GetDefaultParameterValue (#39870)](https://www.github.com/dotnet/roslyn/pull/39870)
- [Fix assertion failure in CFG-builder (#39866)](https://www.github.com/dotnet/roslyn/pull/39866)
- [EnC: Fix document out-of-sync checks when module is not loaded when d… (#39836)](https://www.github.com/dotnet/roslyn/pull/39836)
- [Update dependencies from https://github.com/dotnet/arcade build 20191117.2 (#39863)](https://www.github.com/dotnet/roslyn/pull/39863)
- [Filter optprof to specific tests (#35700)](https://www.github.com/dotnet/roslyn/pull/35700)
- [Update dependencies from https://github.com/dotnet/arcade build 20191116.1 (#39859)](https://www.github.com/dotnet/roslyn/pull/39859)
- [[master] Update dependencies from dotnet/arcade (#39816)](https://www.github.com/dotnet/roslyn/pull/39816)
- [Fix so move to namespace also works for enums when selected (#39798)](https://www.github.com/dotnet/roslyn/pull/39798)
- [Remove capturing lambdas from the language parser. (#39829)](https://www.github.com/dotnet/roslyn/pull/39829)
- [Merge pull request #39819 from mavasani/FxCopAnalyzersCallback](https://www.github.com/dotnet/roslyn/pull/39819)
- [In var foreach, use return type of the Current enumerator prop… (#39769)](https://www.github.com/dotnet/roslyn/pull/39769)
- [Update dependencies from https://github.com/dotnet/arcade build 20191112.5 (#39801)](https://www.github.com/dotnet/roslyn/pull/39801)
- [Implement lambda discard parameters (#38786)](https://www.github.com/dotnet/roslyn/pull/38786)
- [Merge pull request #38582 from YairHalberstadt/ExtractMethodWithConfigureAwait](https://www.github.com/dotnet/roslyn/pull/38582)
- [Add external access shims for TypeScript editor features layer. (#39456)](https://www.github.com/dotnet/roslyn/pull/39456)
- [Merge pull request #39457 from dibarbet/refactor_task_center](https://www.github.com/dotnet/roslyn/pull/39457)
- [Merge pull request #39252 from 06needhamt/update-win-build-instructions](https://www.github.com/dotnet/roslyn/pull/39252)
- [Update dependencies from https://github.com/dotnet/arcade build 20191111.8 (#39776)](https://www.github.com/dotnet/roslyn/pull/39776)
- [Add notes from the last two meetings (#39747)](https://www.github.com/dotnet/roslyn/pull/39747)
- [MonoGlobalAssemblyCache: faster resolves + resolve facade assemblies (#39369)](https://www.github.com/dotnet/roslyn/pull/39369)
- [Merge pull request #39748 from ltrzesniewski/fix-39724](https://www.github.com/dotnet/roslyn/pull/39748)
- [Merge pull request #39673 from KirillOsenkov/dev/kirillo/ivt-razor-mac](https://www.github.com/dotnet/roslyn/pull/39673)
- [Unskip and fix test for local function parsing with `await` (#39714)](https://www.github.com/dotnet/roslyn/pull/39714)
- [Update dependencies from https://github.com/dotnet/arcade build 20191108.11 (#39746)](https://www.github.com/dotnet/roslyn/pull/39746)
- [Cleanup hoisted locals at async state machine end (#34239)](https://www.github.com/dotnet/roslyn/pull/34239)
- [Temporarily publish to only one channel, with Shipping packages only (#39742)](https://www.github.com/dotnet/roslyn/pull/39742)
- [Merge pull request #39407 from NextTurn/new](https://www.github.com/dotnet/roslyn/pull/39407)
- [Analyze argument conversion for this argument of Deconstruct extension method (#39694)](https://www.github.com/dotnet/roslyn/pull/39694)
- [Remove WRN_ExpressionMayIntroduceNullT (#39716)](https://www.github.com/dotnet/roslyn/pull/39716)
- [Merge pull request #39086 from svick/nbsp-formatting](https://www.github.com/dotnet/roslyn/pull/39086)
- [Merge pull request #39249 from jnm2/annotate_generated_equals_parameter](https://www.github.com/dotnet/roslyn/pull/39249)
- [[master] Update dependencies from dotnet/arcade (#39722)](https://www.github.com/dotnet/roslyn/pull/39722)
- [Merge pull request #39695 from dpoeschl/ConvertToLinqExtraSelect](https://www.github.com/dotnet/roslyn/pull/39695)
- [Merge pull request #39708 from dpoeschl/QuickInfoOnIndexerBrackets](https://www.github.com/dotnet/roslyn/pull/39708)
- [Merge pull request #39126 from genlu/extCompletion](https://www.github.com/dotnet/roslyn/pull/39126)
- [Merge pull request #35698 from jasonmalinowski/fix-change-signature-nullability](https://www.github.com/dotnet/roslyn/pull/35698)
- [Merge pull request #39544 from mavasani/RunCodeAnalysisDuringLiveAnalysis](https://www.github.com/dotnet/roslyn/pull/39544)
- [Merge pull request #39698 from ivanbasov/vsmac](https://www.github.com/dotnet/roslyn/pull/39698)
- [Merge pull request #39678 from dpoeschl/SuppressOrConfigure](https://www.github.com/dotnet/roslyn/pull/39678)
- [Merge pull request #39660 from siegfriedpammer/dev/siegfriedpammer/decompiler5](https://www.github.com/dotnet/roslyn/pull/39660)
- [Update dependencies from https://github.com/dotnet/arcade build 20191105.7 (#39705)](https://www.github.com/dotnet/roslyn/pull/39705)
- [[master] Update dependencies from dotnet/arcade (#39084)](https://www.github.com/dotnet/roslyn/pull/39084)
- [Document `-nullable:annotations` option (#39444)](https://www.github.com/dotnet/roslyn/pull/39444)
- [Evaluate tuple elements in a switch control expression in the order written (#39595)](https://www.github.com/dotnet/roslyn/pull/39595)
- [Document compiler package usage (#39272)](https://www.github.com/dotnet/roslyn/pull/39272)
- [Follow-up on adding NullableAnnotation/WithNullableAnnotation APIs to ITypeSymbol. (#39644)](https://www.github.com/dotnet/roslyn/pull/39644)
- [Merge pull request #39634 from jasonmalinowski/fix-null-textsnapshot-crashes](https://www.github.com/dotnet/roslyn/pull/39634)
- [Merge pull request #39596 from mavasani/RunCodeAnalysis](https://www.github.com/dotnet/roslyn/pull/39596)
- [Add NullableAnnotation/WithNullableAnnotation APIs to ITypeSymbol. (#39498)](https://www.github.com/dotnet/roslyn/pull/39498)
- [Fix Host Object Access in Interactive (#39584)](https://www.github.com/dotnet/roslyn/pull/39584)
- [Support non-monotonic transfer for local functions (#39570)](https://www.github.com/dotnet/roslyn/pull/39570)
- [Clean up help link (#39397)](https://www.github.com/dotnet/roslyn/pull/39397)
- [Completion: provide all candidate symbols for overloads in lambda expressions (#39479)](https://www.github.com/dotnet/roslyn/pull/39479)
- [Implement small optimization to avoid creating a diagnostic that we are not planning to look at. (#39527)](https://www.github.com/dotnet/roslyn/pull/39527)
- [Merge pull request #39574 from genlu/EnableSortByMatching](https://www.github.com/dotnet/roslyn/pull/39574)
- [Merge pull request #39554 from allisonchou/MultiCaretBug](https://www.github.com/dotnet/roslyn/pull/39554)
- [Respect filterTree and filterSpanWithinTree while collecting diagnostics for misplaced doc comments. (#39525)](https://www.github.com/dotnet/roslyn/pull/39525)
- [Merge pull request #39545 from sungam3r/typo](https://www.github.com/dotnet/roslyn/pull/39545)
- [Merge pull request #38689 from jasonmalinowski/delete-nullable-analysis-checkbox](https://www.github.com/dotnet/roslyn/pull/38689)
- [Merge pull request #39448 from daytonellwanger/dev/dayton/NoRoot](https://www.github.com/dotnet/roslyn/pull/39448)
- [Merge pull request #38323 from daytonellwanger/dev/dayton/HandlePrefixAndSuffix](https://www.github.com/dotnet/roslyn/pull/38323)
- [Move optimization around use of Nullable type in Boolean Expressions into LocalRewriter and eliminate invalid optimization. (#38802)](https://www.github.com/dotnet/roslyn/pull/38802)
- [Merge pull request #39465 from alrz/fix-if-to-switch](https://www.github.com/dotnet/roslyn/pull/39465)
- [Merge pull request #39307 from agocke/nullable-localfunc](https://www.github.com/dotnet/roslyn/pull/39307)
- [Merge pull request #39261 from huoyaoyuan/fix-class-diagram](https://www.github.com/dotnet/roslyn/pull/39261)
- [Merge pull request #39523 from mavasani/MoveToAnalyzerUtilities](https://www.github.com/dotnet/roslyn/pull/39523)
- [Merge pull request #39528 from jasonmalinowski/fix-flaky-tests-with-ui-thread-assert](https://www.github.com/dotnet/roslyn/pull/39528)
- [Nullable annotate TypeCompilationState and MessageID (#39449)](https://www.github.com/dotnet/roslyn/pull/39449)
- [Fix for control flow graph when combining using declarations with labels (#39451)](https://www.github.com/dotnet/roslyn/pull/39451)
- [Merge pull request #39526 from mavasani/GetValueUsageInfoAssert](https://www.github.com/dotnet/roslyn/pull/39526)
- [Attempt to normalize Location paths before creating URIs (#39274)](https://www.github.com/dotnet/roslyn/pull/39274)
- [Merge pull request #39257 from castholm/modifier-order-severity](https://www.github.com/dotnet/roslyn/pull/39257)
- [Merge pull request #39488 from dibarbet/merge_16_5](https://www.github.com/dotnet/roslyn/pull/39488)
- [Merge pull request #39474 from dibarbet/16_5_snap](https://www.github.com/dotnet/roslyn/pull/39474)
- [Merge pull request #39189 from allisonchou/DPLBug](https://www.github.com/dotnet/roslyn/pull/39189)
- [Merge pull request #38973 from CyrusNajmabadi/useHashCode](https://www.github.com/dotnet/roslyn/pull/38973)
- [Merge pull request #38238 from alrz/unify-if-to-switch](https://www.github.com/dotnet/roslyn/pull/38238)
- [Merge pull request #37618 from jnm2/or_null](https://www.github.com/dotnet/roslyn/pull/37618)
- [Merge pull request #38886 from mavasani/BulkConfigureAnalyzerDiagnostics](https://www.github.com/dotnet/roslyn/pull/38886)
- [Merge pull request #39112 from dibarbet/16_5_version](https://www.github.com/dotnet/roslyn/pull/39112)

### CODE REVIEW

**Comment by Therzok** [comment]
@sandyarmstrong we will need to update our persistent storage caching mechanism following up the discussion here: https://github.com/dotnet/roslyn/pull/39655

If you want, I can take a look at this.

**Comment by sandyarmstrong** [comment]
@Therzok if you have time, I'd appreciate it since you are more familiar. There's no immediate rush on this, but let me know if you need me to take it over. Thanks!

**Comment by sandyarmstrong** [comment]
Some things we should specifically verify in this build:

* Completion
  - [New sorting behavior](https://github.com/dotnet/roslyn/pull/39574)
  - Unimported type changes
    * [Should include extension methods now](https://github.com/dotnet/roslyn/pull/39126)
    * [Performance improvements](https://github.com/dotnet/roslyn/pull/39813)
  - [TypeScript completion on enter](https://github.com/dotnet/roslyn/pull/39698)
* Refactorings
  - [Switch interface implementations between implicit/explicit](https://github.com/dotnet/roslyn/pull/39756)

**Comment by Therzok** [comment]
Opened https://github.com/dotnet/roslyn/pull/40143

Once that is in, we can redirect to `~/Library/Caches`

**Review by Therzok — APPROVED** [review]

**Review by Therzok — APPROVED** [review]

**Comment by sandyarmstrong** [comment]
@Therzok could you possibly look into this test failure when you get a chance?

```
2019-12-05T22:48:19.3240390Z 1) TestStorageDataIsNotRecomputed (MonoDevelop.Ide.TypeSystemServiceTests.TestStorageDataIsNotRecomputed)
2019-12-05T22:48:19.3242320Z      Expected: 12
2019-12-05T22:48:19.3242820Z   But was:  0
2019-12-05T22:48:19.3242950Z 
2019-12-05T22:48:19.3245050Z   at MonoDevelop.Ide.TypeSystemServiceTests+<>c__DisplayClass7_0.<TestStorageDataIsNotRecomputed>g__RunTest|0 (System.Boolean usedCache) [0x00337] in /Users/runner/runners/2.161.1/work/1/s/monodevelop/main/tests/Ide.Tests/MonoDevelop.Ide/TypeSystemServiceTests.cs:301 
2019-12-05T22:48:19.3245850Z   at MonoDevelop.Ide.TypeSystemServiceTests.TestStorageDataIsNotRecomputed () [0x000be] in /Users/runner/runners/2.161.1/work/1/s/monodevelop/main/tests/Ide.Tests/MonoDevelop.Ide/TypeSystemServiceTests.cs:261 
2019-12-05T22:48:19.3246030Z 
```

**Comment by Therzok** [comment]
Hrmmm, it seems like the storage cache was not used. Something went haywire, will take a look, thanks!

**Review by Therzok — APPROVED** [review]

**Pull request closed without merging**
