### PR TITLE
Fixed mono build on windows

### PR DESCRIPTION
**Pull request by simonegli8**
Finally seems to work, but needs some more testing...

### CODE REVIEW

**Comment by simonegli8** [comment]
Fixed so it merges.

**Comment by slluis** [comment]
What does this fix? MD is building fine in our CI system.

**Comment by Therzok** [comment]
@slluis we don't build XS on Mono on Windows.

**Comment by slluis** [comment]
Why should we support building MD on Mono on Windows?

**Comment by simonegli8** [comment]
It's not about building MD. Building with Mono xbuild is broken on Windows for EVERYTHING, not just MD.

**Comment by simonegli8** [comment]
It does fix building with xbuild under Windows for EVERYTHING.

**Comment by simonegli8** [comment]
But I did not test yet too much. I think it's not working yet. So plz waith with merging.

**Comment by simonegli8** [comment]
It's working, did test with MonoDevelop 6.2.0.1718. Finally one can develop Mono on Windows with MD again...

**Comment by simonegli8** [comment]
I made another pull request for 6.2.0

**Comment by simonegli8** [comment]
Did also a pull request to cycle9:
#1962

**Comment by simonegli8** [comment]
There is still some issues with mcs not releasing files and therefore getting build errors on subsequent builds. Don't know how to solve that.

**Comment by simonegli8** [comment]
Did merge Main.sln, but only took my version, might be wrong.

**Pull request closed without merging**
