### PR TITLE
[DotNetCore] Don't allow selection of 3.1 when creating new projects

### PR DESCRIPTION
**Pull request by rodrmoya**
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1008333

### CODE REVIEW

**Comment by rodrmoya** [comment]
> Should we also remove .NET Standard 2.1? Not sure if .NET Standard 2.1 works in 8.3.

2.1 is supported in 3.0 AFAICS, right?

**Comment by mrward** [comment]
@rodrmoya Good point 😄

**Comment by rodrmoya** [comment]
But this is not working with just 3.0 and 3.1 SDKs installed, so DON'T MERGE

**Comment by rodrmoya** [comment]
Closing this, as we won't be doing this for 8.3, and will send a PR to master with a future-proof solution, as this will keep happening

**Pull request closed without merging**
