### PR TITLE
[IDE] Save layouts when they're changed

### PR DESCRIPTION
**Pull request by iainx**
Save layouts after a short delay after they've been changed, rather than waiting until the workspace window is closed

Fixes BXC #25609
Fixes BXC #33009

### CODE REVIEW

**Comment by Therzok** [comment]
LGTM.

But: 25609 is talking about open files, and those are saved to userprefs. So 25609 isn't fixed by this.

**Comment by decriptor** [comment]
:+1:  This'll be nice to have!

**Comment by iainx** [comment]
Changed the commit message to not reference 25609.

**Comment by slluis** [comment]
I think this implementation is abusing events a bit. DockGroup could be more simple: in DockObject.OnAllocationChanged you can just call parentGroup?.OnAllocationChanged(), no need to subscribe child events.

DockNotebook events can also be simplified. We don't really need to know when something is added/removed, a global event that is raised when something changes is enough (no need to chain notebook or page events).

**Comment by iainx** [comment]
Ok, I've rebased and removed the majority of the event stuff

**Pull request merged**
