### PR TITLE
[Proppy] Bump proppy

### PR DESCRIPTION
**Pull request by decriptor**
This brings in a handful of fixes including some a11y improvements.

It also fixes a crash when trying to set a custom expression.
Screenshot 2019-10-16 16 10 26

### CODE REVIEW

**Comment by CartBlanche** [comment]
@decriptor XWT  submodule seems to be breaking in the UnitTest requirement.

**Comment by decriptor** [comment]
@CartBlanche I just rebased on master. Hopefully that'll clear things up

**Comment by Therzok** [comment]
Rebasing this PR would most likely make it go green.

**Comment by garuma** [comment]
Bumped by @sevoku in https://github.com/mono/monodevelop/commit/8b0c98e7bf64be92c68a2ba661907a426ab1b689

**Pull request closed without merging**
