### PR TITLE
[StructuredOutput] Fixes TextColor in unfocused selected row

### PR DESCRIPTION
**Pull request by netonjm**
This PR needs a fix in Xwt, for some reason treeView?.HasFocus is not giving me a right value (is allways in false).

@sevoku could you open a issue related to this? I was investigating but no idea why it's failing.

Fixes Bug #620734

### CODE REVIEW

**Comment by mohakbarokar** [comment]
Build from PR is is failed. https://devdiv.visualstudio.com/DevDiv/Default/_build/results?buildId=1811368&view=logs
Can you please provide new build so that this can be validated.

**Comment by netonjm** [comment]
@mohakbarokar this PR it's not finished yet, not need validation

**Comment by mohakbarokar** [comment]
Verified on Visual Studio Enterprise 2017 for Mac (Preview) Version 7.7 Preview (7.7 build 315).
It is working fine. Hence Approved for merging. 
Build Gist: https://gist.github.com/mohakbarokar/161b78e36a0e1cf64f56c3b4be91bb25

**Comment by sgmunn** [comment]
@netonjm I'm confused, is this done or not? QA is indicating it fixes the issue but the PR says not finished yet.

**Comment by netonjm** [comment]
Hey Greg! the PR it's not finished it's marked as do-not-merge, I need validate the code and ensure all it's working as expected.

**Comment by netonjm** [comment]
@sgmunn ready to review

**Comment by netonjm** [comment]
thanks!

**Pull request merged**
