### PR TITLE
Add Russian translation to desktop file

### PR DESCRIPTION
**Pull request by darktemplarbasealt**

### CODE REVIEW

**Comment by KirillOsenkov** [comment]
The Russian translation is good.

**Comment by darktemplarbasealt** [comment]
Is something else needed to merge this change? If not, could you merge it please?

**Comment by Therzok** [comment]
@darktemplarbasealt Need CI to be green, retriggered some steps so we get required status checks to pass and I'll merge.

**Comment by Therzok** [comment]
@darktemplarbasealt Thanks for the PR!

**Comment by darktemplarbasealt** [comment]
Thank you!

**Pull request merged**
