### PR TITLE
[AutoTest] Use Button.Label for GtkWidgetResult's MarkedOperation

### PR DESCRIPTION
**Pull request by manish**
It would be useful to have Gtk.Button's label for filtering in MarkedOperation.

### CODE REVIEW

**Comment by Therzok** [comment]
build

**Comment by Therzok** [comment]
Git tests are failing on Linux again, I'll look at it on Monday.

**Comment by iainx** [comment]
It doesn't handle the markup case at the moment. We could probably add something that just dropped the markup tags as they're just <></> tags

**Comment by manish** [comment]
I have not tried but maybe using `Contains ()` should handle such a situation

**Comment by iainx** [comment]
Contains will handle the simple markup cases like <bold>Cancel</bold> but not if there's something like <span>Cancel</span> Operation

**Comment by Therzok** [comment]
build

**Pull request closed without merging**
