### PR TITLE
[Debugger] Make sure tooltip request wasn't cancelled before showing

### PR DESCRIPTION
**Pull request by jstedfast**
After the context switch to the main thread in order to show the tooltip,
check that the request hasn't been cancelled due to the editor window
being closed in the meantime (for example).

Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1002160/

### CODE REVIEW

**Comment by jstedfast** [comment]
@monojenkins backport release-8.4

**Comment by sgmunn** [comment]
@jstedfast I cannot get tooltips to work at all on this build

**Comment by sgmunn** [comment]
oh, wait. that's right. I'm on catalina. will try mojave, but this is interesting because on Catalina with other builds I get tooltips but they are the wrong size.

**Comment by jstedfast** [comment]
@sgmunn are you getting any log messages about the editor window being closed?

**Pull request merged**
