### PR TITLE
Bump to md-addins:mono-2018-02

### PR DESCRIPTION
**Pull request by luhenry**

### CODE REVIEW

**Comment by marek-safar** [comment]
@kg could you update the bump?

**Comment by kg** [comment]
@marek-safar Do I need to rebase it or just update it to the latest revision?

**Comment by marek-safar** [comment]
you could also rebase (or merge) but bumping mono dependnecy is more important

**Comment by luhenry** [comment]
Supersed by https://github.com/mono/monodevelop/commit/31784b27df664d2f038306749e5c3bc8b834aa4f

**Pull request closed without merging**
