### PR TITLE
New project default version bump

### PR DESCRIPTION
**Pull request by Therzok**

### CODE REVIEW

**Comment by slluis** [comment]
Tests are failing

**Comment by Therzok** [comment]
Created an equivalent PR in md-addins that fixes the tests. Should I bump this branch to point to that or should we merge them individually? @slluis

**Comment by slluis** [comment]
Do the bump. Once we have a green build, 1) merge the md-addins PR 2) bump this PR to point to the merged commit, 3) merge

**Comment by Therzok** [comment]
@slluis green!

**Pull request merged**
