### PR TITLE
[FSW] Improve WatchDirectories handling

### PR DESCRIPTION
**Pull request by Therzok**
This allows for every user of the WatchDirectories addin to keep track
of the files they watch.

That way, nothing can unset the WatchDirectories a workbench subscribes
except the workbench.

Also fix Assert.DoesNotThrow usage, the assertion does not handle Task
returning delegates, so they're not awaited.

### CODE REVIEW

**Comment by slluis** [comment]
The build is failing...

**Comment by Therzok** [comment]
Yeah, it needs changes in md-addins, I only tested monodevelop locally. Will fix.

**Comment by Therzok** [comment]
@slluis rebased with md-addins changes.

**Comment by Therzok** [comment]
@slluis PTAL

**Comment by Therzok** [comment]
@monojenkins backport release-7.6

**Pull request merged**
