### PR TITLE
Update roslyn version to 3.3.0-beta3-19415-01

### PR DESCRIPTION
**Pull request by agocke**

### CODE REVIEW

**Comment by sandyarmstrong** [comment]
@agocke looks like I need to update editor APIs now that completion expansion (https://github.com/dotnet/roslyn/pull/36146) merged.

BTW, is it easy for you to generate a list of changes since our last bump? See https://github.com/mono/monodevelop/pull/8332 for an example.

**Comment by agocke** [comment]
Once you're on Arcade the updates will include the SHA of the new compiler, so you'll just be able to diff them on Github. No idea how @ryzngard generated that list.

**Comment by sandyarmstrong** [comment]
For my own reference: https://github.com/dotnet/roslyn/compare/8ed56b826700926009731ca4d3de0a4e4e652969...f5ba9f2c61a2fe853dc4913888d40df221539147

**Comment by Therzok** [comment]
Most likely will need to bump binding redirects

**Comment by ryzngard** [comment]
A small script from @JoeRobich  that helped crawl the history and find PR numbers based on two commit SHAs.

**Comment by Therzok** [comment]
```
In assembly 'Microsoft.CodeAnalysis.EditorFeatures, Version=3.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35': Unable to resolve member reference 'Microsoft.VisualStudio.Text.SnapshotPoint Microsoft.VisualStudio.Language.Intellisense.AsyncCompletion.IAsyncCompletionSessionOperations::get_InitialTriggerLocation()' from assembly 'Microsoft.VisualStudio.Language, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
In assembly 'Microsoft.CodeAnalysis.EditorFeatures, Version=3.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35': Unable to resolve member reference 'System.Void Microsoft.VisualStudio.Language.Intellisense.AsyncCompletion.Data.CompletionContext::.ctor(System.Collections.Immutable.ImmutableArray`1<Microsoft.VisualStudio.Language.Intellisense.AsyncCompletion.Data.CompletionItem>,Microsoft.VisualStudio.Language.Intellisense.AsyncCompletion.Data.SuggestionItemOptions,Microsoft.VisualStudio.Language.Intellisense.AsyncCompletion.Data.InitialSelectionHint,System.Collections.Immutable.ImmutableArray`1<Microsoft.VisualStudio.Language.Intellisense.AsyncCompletion.Data.CompletionFilterWithState>)' from assembly 'Microsoft.VisualStudio.Language, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
In assembly 'Microsoft.CodeAnalysis.EditorFeatures, Version=3.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35': Unable to resolve member reference 'System.Void Microsoft.VisualStudio.Language.Intellisense.AsyncCompletion.Data.CompletionExpander::.ctor(System.String,System.String,Microsoft.VisualStudio.Text.Adornments.ImageElement)' from assembly 'Microsoft.VisualStudio.Language, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
In assembly 'Microsoft.CodeAnalysis.EditorFeatures, Version=3.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35': Unable to resolve type reference 'Microsoft.VisualStudio.Language.Intellisense.AsyncCompletion.Data.CompletionExpander' in 'Microsoft.VisualStudio.Language, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
In assembly 'Microsoft.CodeAnalysis.EditorFeatures, Version=3.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35': Unable to resolve type reference 'Microsoft.VisualStudio.Language.Intellisense.AsyncCompletion.IAsyncExpandingCompletionSource' in 'Microsoft.VisualStudio.Language, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```

BinaryCompat failure looks real

**Comment by agocke** [comment]
What's the next step here? I'm not an IDE dev, so not the right person to talk to for code changes. Do we need to loop in someone else?

**Comment by sandyarmstrong** [comment]
@agocke the next step is for me to bring in completion API changes to the editor. I'm currently traveling and it may take a few days.

**Comment by Therzok** [comment]
Yesssssssssss :heart:

**Pull request merged**
