### PR TITLE
[DotNetCore] Update to correct .NET Core download URLs

### PR DESCRIPTION
**Pull request by rodrmoya**
aka.ms versions seem to not work anymore

### CODE REVIEW

**Comment by rodrmoya** [comment]
@monojenkins backport release-7.7

**Comment by mrward** [comment]
Can we not fix the aka.ms links? aka.ms links allow us to change the values if the destination urls change without having to do a new release.

**Comment by mrward** [comment]
Also fixing the aka.ms links will fix the url for the current stable release.

**Comment by rodrmoya** [comment]
ok, this is not needed then, closing

**Pull request closed without merging**
