### PR TITLE
[Mac] Moved mac progress bar 2px up on El Capitan

### PR DESCRIPTION
**Pull request by Therzok**
Bug 33966 - XS: Toolbar progress bar is misaligned on El Capitan

### CODE REVIEW

**Comment by vancura** [comment]
Please don't merge this PR yet, I'll have two cherrypicks ASAP, as soon as @Therzok approves.

**Comment by vancura** [comment]
Done.

**Comment by alanmcgovern** [comment]
Is this ready to merge? Also should it be brought into cycle6 too as it is going to need full el capitan support.

**Comment by vancura** [comment]
I think it's done.

**Pull request merged**
