### PR TITLE
[C#] Improve the way organize and import usings behaves

### PR DESCRIPTION
**Pull request by Therzok**
VSWindows currently shows a Sort and Remove Usings command on the right
click menu, not as a context refactoring.

Thus, mirror the logic by:
* Deleting the 2 refactoring handlers for these actions
* Added a top level command on the editor context menu

UX changes:
* 2 refactorings are removed - we no longer show a screwdriver
for these options once usings are sorted and removed via lightbulb action
* A new item comes below the Rename command in the main menu

Fixes VSTS #720770 - Screwdriver never goes away in using statements

### CODE REVIEW

**Comment by Therzok** [comment]
VSWindows:
vsnoscrewdriver
vswincommands

**Comment by Therzok** [comment]
Our behaviour now:
screenshot 2018-11-01 at 22 41 07
screenshot 2018-11-01 at 22 41 18

**Comment by Therzok** [comment]
Also, it seems to be always shown in VS Windows (wherever you request the context menu on the document), which I've mirrored here.

**Comment by Therzok** [comment]
cc @slluis @sayedihashimi @vancura on UX change

**Comment by mhutch** [comment]
Presumably we'll still see a "remove and sort" fix for the 'unused usings' diagnostic?

**Comment by Therzok** [comment]
Yes. There's `Removed unnecessary usings`, but that does not _also_ sort.

**Comment by slluis** [comment]
@monojenkins backport release-7.7

**Pull request merged**
