### PR TITLE
Master vsts612435

### PR DESCRIPTION
**Pull request by mkrueger**

### CODE REVIEW

**Comment by mkrueger** [comment]
@monojenkins backport d15-7

**Comment by Therzok** [comment]
Compat check is unrelated to this PR.

**Comment by GLjackyvaswani** [comment]
Hello,

The assembly browser is still not working.I created a blank forms application and tried searching for ContentPage in assembly browser, the search was not successful. 
The bug https://devdiv.visualstudio.com/DevDiv/_workitems/edit/612435 is reproducible.
Hence this cannot be merged.

Build info:
Version 7.6 Preview (7.6 build 739)

Build gist:
https://gist.github.com/p-lad/052808fa09f7fc222c7b61216c6233db

Build taken from:
https://github.com/mono/monodevelop/pull/4757

Screencast link:
http://www.screencast.com/t/JhkFLnPFD

Logs: 
[Master logs.zip](https://github.com/mono/monodevelop/files/1995367/Master.logs.zip)

Note: On closing the solution and then when I tried to create a new blank forms application, it was not created. Only after relaunching VSfM I was able to create a new blank forms application. 
Screencast link: https://www.screencast.com/t/YDxK1uB4hdy

Thanks

**Comment by mkrueger** [comment]
Failing compatibility check is not related to my commit.

**Comment by Therzok** [comment]
Looks good to me.

**Comment by mohakbarokar** [comment]
Hello,

As discussed with @mrward  on slack, assembly browser is now working fine. Created a blank forms application and searched for content page in the assembly browser. Related results were observed. Tried it for android and iOS application.
I can confirm that the bug: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/612435 is not reproducible when tested on:

Build info:
Visual Studio Enterprise 2017 for Mac (Preview)
Version 7.6 Preview (7.6 build 839)

Build gist:
https://gist.github.com/mohakbarokar/3fed60da5b411eddba192edf068ea46f

Screencast link:
https://www.screencast.com/t/BuG1ImZ9a4

As the bug is not reproduced, it can be merged.
Thanks

**Pull request merged**
