### PR TITLE
Stub launcher

### PR DESCRIPTION
**Pull request by Therzok**
cc @alanmcgovern

### CODE REVIEW

**Comment by slluis** [comment]
What does this fix?

**Comment by alanmcgovern** [comment]
It's so a normal 'make run' will use the same launcher as our app bundle. This should let local devs trigger the same bugs that previously we could only trigger with an app bundle. I'll test that theory in a few minutes and see if yesterday's crashed shows up when we use this pr

**Comment by alanmcgovern** [comment]
I sent an email asking for this yesterday :)

**Comment by alanmcgovern** [comment]
This this result in `make run` triggering the same issues that the app bundle triggers. :+1: for reproducibility of bugs!

**Comment by Therzok** [comment]
Merged manually.

**Pull request closed without merging**
