### PR TITLE
Master fix57255

### PR DESCRIPTION
**Pull request by mkrueger**

### CODE REVIEW

**Comment by slluis** [comment]
I created a build lane to verify this PR.

**Comment by mkrueger** [comment]
Any news on that one ? Why it's blocked for so long ?

**Comment by DavidKarlas** [comment]
Mostly because it's so huge change, and I mostly have no idea what I'm looking at... Changes in C# look reasonable to me, going to test build from build lane Lluis created and if everything looks fine I will approve today

**Comment by mkrueger** [comment]
It's just an update of the vs code textmate grammars mostly. Important is the textmate folding change - that's a huge issue if you want to edit textmate controlled files. Other than that it's just adding .md highlighting.

**Pull request merged**
