### PR TITLE
[VersionControl] Error creating branches 

### PR DESCRIPTION
**Pull request by jsuarezruiz**
The first thing I considered is to add validations in the name of branches. Libgit2 has a method for it: https://libgit2.org/libgit2/#HEAD/group/reference/git_reference_is_valid_name
But we are using it: http://source.monodevelop.com/#MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/EditBranchDialog.cs,126

With this changes, show an error message to notify the user that there has been a problem creating the branch.

Fixes gh #7106

### CODE REVIEW

**Comment by slluis** [comment]
Is there any information we can extract from the exception that we can use to give more information to the user?

**Comment by Therzok** [comment]
```
int | 1 if the reference name is acceptable; 0 if it isn't
-- | --
```

This is all that libgit2 supplies, no error message.

**Comment by Therzok** [comment]
git_reference__normalize_name does set an error that has some message, might be better than is_valid_name

**Comment by jsuarezruiz** [comment]
@sevoku I added the branch name max length.
screenshot 2019-02-21 at 10 36 30

Libgit2sharp return some information about the problems, like this one:
screenshot 2019-02-21 at 10 54 50

BTW, with large names, the size of the dialog grows to adapt. Playing with the limits, we can have a dialog that does not fit on the screen.
screenshot 2019-02-21 at 10 37 00

Added in this PR the dialog width size:
screenshot 2019-02-21 at 10 44 17

**Pull request merged**
