### PR TITLE
Fixes VSTS Bug 938343: [Feedback] Diff Option in Version Control not

### PR DESCRIPTION
**Pull request by mkrueger**
working as expected.

https://devdiv.visualstudio.com/DevDiv/_workitems/edit/938343

### CODE REVIEW

**Comment by mkrueger** [comment]
@monojenkins backport release-8.2

**Comment by mkrueger** [comment]
I couldn't reproduce the issue - tried master & 8.2 branches as well as the released version.

Fixed the crash from the log. But if anyone has seen this issue I would like to know about it. Maybe I did the wrong reproduction steps.

**Comment by sevoku** [comment]
@monojenkins backport release-8.2

**Comment by sevoku** [comment]
@monojenkins backport release-8.1

**Comment by sevoku** [comment]
@monojenkins backport release-8.1

**Comment by sevoku** [comment]
@monojenkins backport release-8.2

**Pull request merged**
