### PR TITLE
Remove old CSS/HTML/JSON mappings. To be replaced by WebTooling Addin

### PR DESCRIPTION
**Pull request by ToddGrun**
I wanted to change my file extensions from .css2, .html2, .json2 to the real things, so I needed to update MD so that we wouldn't collide.

### CODE REVIEW

**Comment by ToddGrun** [comment]
@mkrueger @mhutch 

Thoughts?

**Comment by mhutch** [comment]
Technically you can just insert yours before the old ones using the insertBefore attribute and they will be picked up instead when your addin is loaded.

See e.g. https://github.com/mhutch/MonoDevelop.MSBuildEditor/blob/master/Properties/Manifest.addin.xml which overrides the built in MSBuild editor.

**Comment by mhutch** [comment]
That said, it only works if the thing you're inserting before has an ID...

**Comment by ToddGrun** [comment]
Interesting. For the MimeType, can I specify that I want my to be insertedbefore both text/html and application/x-spark?

Also, would this work for FileFilters? I haven't tried it, but would my file filter replace theirs, or just precede it?

**Comment by mkrueger** [comment]
We need to discuss it if we should remove html/json support for monodevelop. If we do it we've to remove more than just some bindings. Like the HtmlEditorExtension it would be unused in that patch.

Futuremore if we do it we should remove ASP.NET support as well.

**Comment by mhutch** [comment]
@ToddGrun if you insert before html, it'll be before spark, since html is before spark.

As for ordering, it depends on how the extension point consumes the extension.

Some "list" extension points will just use all the extensions at the extension point - pretty sure file filters do this.

Other scan the extensions and find the first match - for example the DesktopService, when determining mimetype for a file, takes the first with a glob that that matches the file's extension.

Yet others will build a dictionary for perf reasons, and in this case it would effectively be the _last_ match (but there's also an `insertAfter`...).

**Pull request closed without merging**
