### PR TITLE
[Debugger] Fixed VSCodeDebuggerSession.OnNextInstruction

### PR DESCRIPTION
**Pull request by jstedfast**
I previously "fixed" this to do StepInRequest but I was wrong.

### CODE REVIEW

**Comment by slluis** [comment]
Do we need this in 8.2? is it a regression?

**Comment by jstedfast** [comment]
Yea, this also affects 8.2 (just verified).

**Comment by slluis** [comment]
@monojenkins backport release-8.2

**Comment by slluis** [comment]
Some debugger tests are failing.

**Comment by jstedfast** [comment]
@slluis working on it...

**Comment by jstedfast** [comment]
The remaining unit test failure seems to be unrelated (CSharpBinding failure)

**Pull request merged**
