### PR TITLE
Switch some projects to use PackageReference instead of packages.config.

### PR DESCRIPTION
**Pull request by KirillOsenkov**
To make it easier to update VS Editor and Roslyn references in the future I'm switching to use <PackageReference> in the projects that use Roslyn and/or Editor.

One thing to know about PackageReference is that it works in non-SDK-style projects. A project can opt-in to supporting this either by having at least one PackageReference or setting <RestoreProjectStyle>PackageReference</RestoreProjectStyle>.

If ProjectB references ProjectA and both have opted in to use PackageReference, all PackageReferences from ProjectA will be available in ProjectB transitively.

In some projects you'll notice that I'm just adding a System.ValueTuple. This opts in and inherits the PackageReferences from MD.Core.

To make it easier to update versions I'm extracting the Editor and Roslyn versions into an MSBuild property and using that. This way we can bump the version by changing a single line.

### CODE REVIEW

**Comment by mrward** [comment]
Wrench build is failing. Assemblies are being copied to various addin directories causing the duplicate file check to fail.

**Comment by KirillOsenkov** [comment]
Yup, looking.

**Comment by KirillOsenkov** [comment]
I'm afraid this approach isn't going to work. We don't have enough control over `<PackageReference>` items to prohibit copying all those to output everywhere except the original reference.

I've filed https://github.com/NuGet/Home/issues/5986 to track this, but it looks like we can't use PackageReference at this moment because of the duplicate files.

**Comment by KirillOsenkov** [comment]
Actually I think I found a way to salvage it.

Let's try `<CopyNuGetImplementations>false</CopyNuGetImplementations>` to turn off copying dependencies from NuGet packages that come transitively from referenced projects.

**Comment by KirillOsenkov** [comment]
Rebased on top of master to resolve conflicts, create a new wrench lane to test.

**Comment by KirillOsenkov** [comment]
I'm abandoning this approach because of the bug above and I've already found a different workaround.

**Comment by alanmcgovern** [comment]
Let me take a quick look...

**Comment by alanmcgovern** [comment]
@KirillOsenkov We should swap over to the 'standard' mechanism to avoid local copying :) It now builds for me though!

**Comment by Therzok** [comment]
Can this be closed?

**Pull request closed without merging**
