### PR TITLE
[15.3] Bug 57511 - Quick Fix -> Generate Type refactoring operation is a no-op

### PR DESCRIPTION
**Pull request by DavidKarlas**

### CODE REVIEW

**Comment by DavidKarlas** [comment]
Before:
image

After:
image

**Comment by mkrueger** [comment]
It's already fixed in another PR that's open.

**Comment by mkrueger** [comment]
That one:

https://github.com/mono/monodevelop/pull/2537

**Comment by DavidKarlas** [comment]
That is open to mater, will open new PR to 15.3?

**Pull request closed without merging**
