### PR TITLE
Azure functions

### PR DESCRIPTION
**Pull request by mhutch**
This should be good to go.

### CODE REVIEW

**Comment by mhutch** [comment]
This should be good to go.

Given that the compressed size of the Functions runtime is about 18MB, I wonder whether it would be worth switching over to downloading it on first use instead of bundling it. Not a blocker, though.

**Comment by slluis** [comment]
This breaks the build due to duplicates: https://wrench.internalx.com/Wrench/WebServices/Download.aspx?workfile_id=18854691

**Comment by sgmunn** [comment]
packaging step fixed with https://github.com/xamarin/md-addins/pull/1913

I create another lane and branch with _only_ the bump to that branch so that, if green, this PR could be merged without dealing with md-addins bumps.

https://wrench.internalx.com/Wrench/index.aspx?lane=monodevelop-lion-monodevelop-pr-2365-build

Currently, a few tests in 'tests-unittests' step are failing.

**Comment by sgmunn** [comment]
Ugh. 

so, this PR branch is against d15-3-preview, but when the tool creates the PR lane and build it used

> DEP_NEEDED_VERSION[0]=6280eab56ea7326233e1ae8af921d2e9d6d9c5b1
> DEP_BRANCH_AND_REMOTE[0]="master origin/master"

My first commit to the "-build" branch bumped md-addins to a "d15-3-preview" based branch, which I believe to be the more correct branch and resulted in the unit test failures I observed. When I tried to used a branch based of master I got weird build / provisioning errors. Just trying again to see what's up.

**Comment by sgmunn** [comment]
so far with https://github.com/mono/monodevelop/pull/2365/commits/7894caff0d7813cb59c115c7267d9e3b0eec21a6 the unit test failures in "unittests" and "fsharpbinding" have been resolved.

https://wrench.internalx.com/Wrench/ViewLane.aspx?lane_id=4880&host_id=430&revision_id=887200

Will check up on the rest once they've run.

**Comment by mhutch** [comment]
@sgmunn looks all green to me :)

**Pull request merged**
