### PR TITLE
Attempt to fix tests

### PR DESCRIPTION
**Pull request by nosami**

### CODE REVIEW

**Comment by slluis** [comment]
@monojenkins backport release-8.2

**Comment by Therzok** [comment]
Should we close this? It isn't the right fix.

**Comment by sevoku** [comment]
Although this is not the right fix for the build failures, this makes the Fsharp projects use Xamarin.Mac.dll from the right place `main/external/Xamarin.Mac.dll` like other projects do.

@nosami could you rabese to get green checks?

**Comment by nosami** [comment]
Rebased.

**Comment by nosami** [comment]
@monojenkins backport release-8.2

**Pull request merged**
