### PR TITLE
Static registrar support

### PR DESCRIPTION
**Pull request by Therzok**

### CODE REVIEW

**Comment by Therzok** [comment]
Needs cleanup in version-checks before merging.

**Comment by Therzok** [comment]
Seems like there are some test failures, will look.

**Comment by Therzok** [comment]
Started a new build, md-addins tests were not using the stub launcher.

**Comment by Therzok** [comment]
Failure unrelated. Can we merge these both in tandem?

**Comment by slluis** [comment]
Rebuilding

**Comment by Therzok** [comment]
This breaks non-stub launcher runs (i.e. debugging). Need to fix it somehow so libxammac.dylib is used for dev builds, not embedded libxammac.

**Comment by Therzok** [comment]
Fixed debugging.

**Comment by Therzok** [comment]
@slluis I updated the VSTS timeout to 20 mins, it seems to still be taking 12mins.

**Pull request merged**
