### PR TITLE
Fixes VSTS Bug 674268: Search broken, results returned do not match s…

### PR DESCRIPTION
**Pull request by mkrueger**
…earch terms

https://devdiv.visualstudio.com/DevDiv/_workitems/edit/674268

### CODE REVIEW

**Comment by slluis** [comment]
@monojenkins backport release-7.6

**Comment by slluis** [comment]
Can we have unit tests on this? it was a very severe regression.

**Comment by mkrueger** [comment]
Difficult it's an UI thing - here it was a race condition.

**Comment by slluis** [comment]
I created an action item for creating the test suite (https://devdiv.visualstudio.com/DevDiv/_workitems/edit/676784). Let's merge this for now.

**Pull request merged**
