### PR TITLE
[Editor] Add a SelectUntilMatchingBrace command.

### PR DESCRIPTION
**Pull request by Therzok**

### CODE REVIEW

**Comment by mkrueger** [comment]
Add that to the roslyn branch. Doesn't make sense to add features to master.

**Comment by Therzok** [comment]
It doesn't conflict with master. And it's the same code for both. Why not just merge to master then merge to roslyn?

**Comment by mkrueger** [comment]
It's on the wrong layer. All text editor commands should be done on the IDE layer. Commands written against the mono.texteditor will not work IF we replace the editor.

**Comment by Therzok** [comment]
Closing PR as I filed a bug for this.

**Pull request closed without merging**
