### PR TITLE
TextEditor: Update name of new editor display binding

### PR DESCRIPTION
**Pull request by sandyarmstrong**
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/889423

### CODE REVIEW

**Comment by abock** [comment]
@monojenkins backport release-8.1

**Comment by slluis** [comment]
Maybe we should change the new editor to "Source Code Editor", and the old one to "Legacy Source Code Editor"?

**Comment by sandyarmstrong** [comment]
@slluis see discussion on the bug. We opted to do it this way because old editor is only legacy for C# at this time.

**Comment by sandyarmstrong** [comment]
@monojenkins backport release-8.1

**Pull request merged**
