### PR TITLE
Fixes VSTS Bug 958249: System.InvalidOperationException exception in

### PR DESCRIPTION
**Pull request by mkrueger**
MonoDevelop.Ide.Gui.Components.LogViewProgressMonitor.OnWriteLog()

https://devdiv.visualstudio.com/DevDiv/_workitems/edit/958249

Found some event handlers that were not unregistered on dispose which
may explain that issue.

### CODE REVIEW

**Comment by mkrueger** [comment]
@monojenkins backport release-8.3
@monojenkins backport release-8.4

**Review by Therzok — APPROVED** [review]

**Review by netonjm — APPROVED** [review]

**Review by sevoku — APPROVED** [review]

**Comment by sevoku** [comment]
@monojenkins rebase

**Comment by sevoku** [comment]
@monojenkins backport release-8.4

**Comment by sevoku** [comment]
@monojenkins rebase

**Comment by sevoku** [comment]
@monojenkins backport release-8.3
@monojenkins backport release-8.4

**Review by sevoku — CHANGES_REQUESTED** [review]
Now the tests fail with:

```2019-11-06T23:28:28.5678310Z    System.NullReferenceException : Object reference not set to an instance of an object
2019-11-06T23:28:28.5678740Z   at MonoDevelop.Core.ProgressMonitoring.AggregatedProgressMonitor.OnWriteLog (System.String message) [0x00020] in /Users/runner/runners/2.160.0/work/1/s/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Core.ProgressMonitoring/AggregatedProgressMonitor.cs:150 
2019-11-06T23:28:28.5679580Z   at MonoDevelop.Core.ProgressMonitor.DoWriteLog (System.String message) [0x00018] in /Users/runner/runners/2.160.0/work/1/s/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Core/ProgressMonitor.cs:743 
2019-11-06T23:28:28.5680010Z   at MonoDevelop.Core.ProgressMonitoring.LogTextWriter.OnWrite (System.Char[] buffer, System.Int32 index, System.Int32 count) [0x00000] in /Users/runner/runners/2.160.0/work/1/s/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Core.ProgressMonitoring/LogTextWriter.cs:107 
2019-11-06T23:28:28.5680490Z   at MonoDevelop.Core.ProgressMonitoring.LogTextWriter.Write (System.Char[] buffer, System.Int32 index, System.Int32 count) [0x0003c] in /Users/runner/runners/2.160.0/work/1/s/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Core.ProgressMonitoring/LogTextWriter.cs:102 
```

**Comment by mkrueger** [comment]
@monojenkins backport release-8.3
@monojenkins backport release-8.4

**Review by Therzok — APPROVED** [review]

**Review by sevoku — APPROVED** [review]

**Pull request merged**
