### PR TITLE
Adding an Edit Project File item to the root project context menu.

### PR DESCRIPTION
**Pull request by jmatthiesen**
Fixes VSTS #617837

This work adds an Edit Project File command to the context menu shown in the Solution Pad when right-clicking on a project file.

image

Based on a discussion with @hbons, I placed this menu in the same section as "Options" since they're conceptually used for the same purposes.

### CODE REVIEW

**Comment by mrward** [comment]
Where does the menu appear for Solutions? It seems like it would not be next to Options like it is with projects.

**Comment by jmatthiesen** [comment]
Currently I left it in the Tools submenu for solutions. We hear requests for "Edit Project File" a lot and haven't heard any requests for Solutions.

**Comment by mrward** [comment]
Is it in the Tools submenu? It looks like it is outside the Tools menu for a solution.

**Comment by mrward** [comment]
The context menu for a solution now looks like this: 

EditFile-Solution

Edit File has moved out of the Tools submenu here.

**Comment by jmatthiesen** [comment]
Good catch, thanks @mrward. I just pushed a fix to keep the Edit File menu under the Tools submenu like it was before. So now only the Edit Project File command is outside the submenu.

**Comment by Therzok** [comment]
Anything else needed to merge this?

**Pull request closed without merging**
