### PR TITLE
Fixes issue #4470 3rd party addins can't create TextSegmentMarkers

### PR DESCRIPTION
**Pull request by mkrueger**

### CODE REVIEW

**Comment by mkrueger** [comment]
@monojenkins backport d15-7

**Comment by nosami** [comment]
@mkrueger : wow - thanks for this! :+1:

**Comment by nosami** [comment]
Hmm- looking at the code again, there is just changing the background. I need a way to be able to write text over the top of the source code.

**Comment by Therzok** [comment]
@monojenkins backport d15-7

**Pull request merged**
