### PR TITLE
Add binding redirects for SQLite binaries to match the latest version.

### PR DESCRIPTION
**Pull request by KirillOsenkov**

### CODE REVIEW

**Comment by KirillOsenkov** [comment]
Hmm, I wonder why BinaryCompatChecker didn't complain about this.

**Comment by Therzok** [comment]
Because SQLitePCLRaw started using assembly versioning in 0.11

**Comment by KirillOsenkov** [comment]
Yeah, but I'd expect BinaryCompatChecker to fail as soon as you updated to 1.1.10. Maybe I don't check for this case?? I'll investigate separately.

**Comment by KirillOsenkov** [comment]
Argh!! Found a problem in BinaryCompatChecker!! It should have caught this, but has a bug!

**Pull request merged**
