### PR TITLE
Remove deadlock from .net core package restore

### PR DESCRIPTION
**Pull request by nosami**

### CODE REVIEW

**Comment by slluis** [comment]
Can you please create a build lane for this PR?

**Comment by nosami** [comment]
Build lane added - https://code.internalx.com/Wrench/BuildDetails?buildId=3d93db71d172a8827782634ee55286be

**Comment by mrward** [comment]
[Bugzilla bug 57759](https://bugzilla.xamarin.com/show_bug.cgi?id=57759)

**Comment by nosami** [comment]
Looks like we need [this fix](https://github.com/xamarin/md-addins/commit/1fe3fbf4d443aa9ed237b975f7800968c1b94cc3) applying to md-addins to make the build work again.

**Comment by nosami** [comment]
Created md-addins PR https://github.com/xamarin/md-addins/pull/2180

**Comment by mrward** [comment]
@Aguilex - This fix has been verified by QA. There is a " F# .NET Core package restore never finishes (bug 57759)" card on the 15.3 release board. So this is ready for you to merge into the d15-3 branch if you are happy with it. Thanks.

**Pull request merged**
