### PR TITLE
[Projects] Portable Class Libraries should not be runnable by default.

### PR DESCRIPTION
**Pull request by Therzok**

### CODE REVIEW

**Comment by Therzok** [comment]
All things considered, we _should_ probably do a check for custom commands and add another type check here, instead of overriding. https://github.com/mono/monodevelop/blob/pclExecutable/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProject.cs#L970

**Comment by slluis** [comment]
Why is this necessary at all? Libraries are not executable by default.

**Comment by Therzok** [comment]
No, this one ends up as 'true'. Because only `DotNetAssemblyProject` is counted as a library project.

https://github.com/mono/monodevelop/blob/master/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProject.cs#L970-L971

**Comment by slluis** [comment]
Let's add the additional type check. All this is not necessary in the roslyn branch.

**Comment by Therzok** [comment]
Closed in favor of https://github.com/mono/monodevelop/commit/a3ebe7380cbdfc4656d984c0ce0ed8428f80a83e

**Pull request closed without merging**
