### PR TITLE
Map ShrinkSelection for new editor

### PR DESCRIPTION
**Pull request by mhutch**
And map ExpandSelection properly

Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/949285

### CODE REVIEW

**Comment by abock** [comment]
The commands are in VS Platform. We will need to port them.

**Comment by abock** [comment]
Need a bug for this in ADO.

**Comment by sandyarmstrong** [comment]
It's ADO 949285.

**Comment by abock** [comment]
These commands are now supported in the new editor. Merging.

**Pull request merged**
