### PR TITLE
Add TimeToCode timer with intellisense data 

### PR DESCRIPTION
**Pull request by Therzok**
Fixes VSTS #767147 - Add telemetry to measure time to intellisense available

### CODE REVIEW

**Comment by Therzok** [comment]
@rodrmoya @iainx I've tried this locally, and telemetry monitor isn't picking up TTC events.

That is because the open timer expired:
http://source.monodevelop.com/#MonoDevelop.Ide/MonoDevelop.Ide/Ide.cs,6b6434186b540a0e,references

What do you suggest doing here?

**Comment by rodrmoya** [comment]
hmm, not sure, but I guess the 1st thing that comes to mind is to start the timeToCode timer only if we're opening a file?

**Comment by iainx** [comment]
TimeToCode is only supposed to be for opening Solutions/Files from Finder. Not opening files from inside the IDE itself, that's why there's the timer, because when we start the IDE, we don't know if it was started by the user from Launchpad, or if it was started by Finder, so we wait 2.5seconds to see if we get the "Load a file" Apple Event.

If we want to have Intellisense timings available for all solutions it should be added to the `Ide.Shell.SolutionOpened` event maybe?

**Comment by Therzok** [comment]
@iainx I think Lluis actually wants 2 timers for this, one like timetocode, one just to measure the actual monodevelopworkspace load

**Comment by Therzok** [comment]
But regardless, TTC is completely busted.

**Comment by Therzok** [comment]
@monojenkins backport release-8.0-integration

**Pull request merged**
