### PR TITLE
[Mac] Use the main DispatchQueue when processing memory pressure events

### PR DESCRIPTION
**Pull request by Therzok**
Processing this on a background thread will cause an AppKit NSEventThread to spin up on a background thread, which would never finish running
This thread would also be running at 100% CPU, causing a specific thread to loop and burn until the process ends

Fixes VSTS #894581 - VS Mac processes still running after quitting the app?
Fixes VSTS #802626 - [Feedback] VS usually consumes an entire CPU core when idle, killing battery life (and making my lap hot)

### CODE REVIEW

**Comment by Therzok** [comment]
@monojenkins backport release-8.1

**Comment by slluis** [comment]
@monojenkins backport release-8.1

**Comment by leculver** [comment]
@slluis @Therzok I suspect (but am not certain) that this causes our Unhealthy Session rate to go up.  The background process that monitors VS for Mac likely would get confused by the fact that VS for Mac is still running, and would appear hanging.  If we decide to ship another 8.0.*, I would suggest including this change as well.  (I wouldn't ship a new 8.0 just for this change, but opportunistically fixing this problem would be a good idea, IMO.)

**Comment by migueldeicaza** [comment]
The debugging that lead to this patch must have been epic!

**Pull request merged**
