### PR TITLE
The Assembly version for FSharp.Core 4.3.3 is 4.4.3.0

### PR DESCRIPTION
**Pull request by nosami**

### CODE REVIEW

**Comment by Therzok** [comment]
Thanks!

**Comment by nosami** [comment]
Build failed trying to install external addins

```
/bin/sh: ../../monodevelop/local-config/xamarin-addins_External_Addins.addins: No such file or directory
```

**Comment by dsyme** [comment]
Closed/reopened to trigger build - or is there another way to trigger?

**Comment by nosami** [comment]
@dsyme: The build can be re-triggered from VSTS ("Queue new build")

**Comment by nosami** [comment]
rebased

**Pull request merged**
