### PR TITLE
Fixes issue CopyCommentsFromBaseCodeRefactoringProvider.ComputeRefactoringsAsync XML parse exception #5161

### PR DESCRIPTION
**Pull request by mkrueger**
Fixes issue #5161 CopyCommentsFromBaseCodeRefactoringProvider.ComputeRefactoringsAsync XML parse exception

### CODE REVIEW

**Comment by Therzok** [comment]
Prefer `string.Join(string, string[])` overload by using a different XML reader.

**Comment by mkrueger** [comment]
Best thing would've been indexOf('>') .... lastIndexOf ('<') - y I also found it a bit weird what they did - for stripping the root node I woudn't have used any xml reader or join operations.

**Comment by KirillOsenkov** [comment]
I wish there was a way to avoid a first-chance exception for malformed XML. It happens pretty often unfortunately. I wonder if RefactoringEssentials has access to the MonoDevelop's Xml Parser? I'd guess not? And it's probably not worth introducing a new dependency just to fix this (such as https://github.com/KirillOsenkov/XmlParser).

**Comment by mkrueger** [comment]
Refactoring essentials has an own very capable xml parser.

**Pull request merged**
