### PR TITLE
[Ide] Unset some environment variables after they're no longer needed

### PR DESCRIPTION
**Pull request by Therzok**
Should prevent polluting child processes with these values

Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1000552

### CODE REVIEW

**Review by sgmunn — APPROVED** [review]

**Comment by sgmunn** [comment]
This fixes the issue I saw with https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1000552

**Review by rodrmoya — APPROVED** [review]

**Comment by sgmunn** [comment]
although, this doesn't seem to help .net core test projects, only mono

**Comment by Therzok** [comment]
@sgmunn we have this bug in .netcore projects? how can that be related to the monostub commit?

**Comment by mrward** [comment]
Did .NET Core tests work before? Checking older VS Mac versions (e.g. 8.3.1 and 8.3.0), which are OK when debugging NUnit tests with Mono, do not show the exception caught dialog with .NET Core xUnit and .NET Core NUnit test projects.

Also running a .NET Core console project that throws an exception in its Main does not show the exception caught tooltip, unlike a classic console project.

Possibly we are missing some support in our VS Debug Protocol implementation?

**Review by mrward — APPROVED** [review]

**Comment by Therzok** [comment]
@monojenkins backport release-8?4

**Comment by Therzok** [comment]
@monojenkins backport release-8.4

**Review by slluis — APPROVED** [review]

**Pull request merged**
