### PR TITLE
[Scaffolding] Set ComboBoxEntries to autocomplete 

### PR DESCRIPTION
**Pull request by nosami**
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1036175

### CODE REVIEW

**Comment by Therzok** [comment]
Looks like it needs a rebase.

**Comment by rodrmoya** [comment]
hmm, seems to be failing still on the same bit, does this need a new rebase @nosami @Therzok ?

**Comment by nosami** [comment]
It was rebased yesterday. I can rebase it again and will keep rebasing it over and over and over again until it goes green ;)

**Comment by Therzok** [comment]
Yeah, I was requesting a rebase not because of the failure, but because the xwt submodule was bumped and it was causing conflicts. LGTM 👍

**Pull request merged**
