### PR TITLE
[Core] Add FileCopied and FileMoved events to FileService

### PR DESCRIPTION
**Pull request by sandyarmstrong**
These make it a lot easier to perform some action when (for example)
solution nodes are dragged or copied around.

### CODE REVIEW

**Comment by abock** [comment]
:+1: from me. We'll need this for resource management in Sketches.

**Comment by alanmcgovern** [comment]
This does appear to break the build:

MonoDevelop.Core/FileService.cs(222,40): error CS0103: The name `srcFile' does not exist in the current context
MonoDevelop.Core/FileService.cs(222,49): error CS0103: The name `dstFile' does not exist in the current context

I think you meant srcPath and dstPath in the patch

**Comment by alanmcgovern** [comment]
I'll close it so we don't merge it accidentally, feel free to re-open it when it compiles!

**Comment by sandyarmstrong** [comment]
Ugh, my bad.

**Comment by sandyarmstrong** [comment]
Github doesn't let you reopen a PR if you force push to the branch while it's closed. So, here's the new PR: https://github.com/mono/monodevelop/pull/748.

Sorry for the bad patch. Every time I edit this file I get line ending issues and have to be careful what I stage, so I missed that one line.

**Comment by alanmcgovern** [comment]
No worries! It's nice that the bot caught it!

**Pull request closed without merging**
