### PR TITLE
Preserve the app bundle directory instead of moving it into .dmg

### PR DESCRIPTION
**Pull request by KirillOsenkov**
We need to do more checks on the bundle directory after the .dmg is created (such as compatibility-check).

### CODE REVIEW

**Comment by KirillOsenkov** [comment]
Any idea why the verify-codesign fails for this change in Wrench?

**Comment by KirillOsenkov** [comment]
`Visual Studio.app\Contents\MacOS\MonoDoc.app\Contents\MonoBundle\libintl.dylib` used to be just the text `libintl.8.dylib`, now it's an entire binary file. Not sure if it's my fault? Or is it related?

**Comment by alanmcgovern** [comment]
We need to preserve symlinks when copying. I’ll check it later!

**Comment by alanmcgovern** [comment]
LGTM! merging this like a boss as CI is happy!

**Comment by KirillOsenkov** [comment]
👍

**Pull request closed without merging**
