### PR TITLE
Fix 1023494: Unsaved new documents have `/` added to begining of file name

### PR DESCRIPTION
**Pull request by DavidKarlas**
I think that anything that needs Canonical comparison should make conversion itself.
I'm also not aware of any regressions this might cause... @slluis any ideas?

### CODE REVIEW

**Comment by Therzok** [comment]
@davidkarlas maybe we could have a unit test with a file controller pointing to a symlinked file, and assert that the symlink is unchanged and we wrote to the real file.

**Comment by DavidKarlas** [comment]
@Therzok what is bug# of bug you are referring to?

**Comment by Therzok** [comment]
Can't find it, seems to be new code in the new document model. In any case, can we add that test? :D

**Comment by DavidKarlas** [comment]
Test for something this PR doesn't fix?

**Comment by Therzok** [comment]
Okay, for some reason, I thought CanonicalPath resolves symlinks, but it doesn't. LGTM

**Comment by DavidKarlas** [comment]
Added unit test for new behavior.

**Comment by slluis** [comment]
A better solution would be to only get the canonical path when the path is absolute.

**Comment by DavidKarlas** [comment]
@slluis updated code as suggested to do Canonical only for AbsolutePath.

**Pull request merged**
