### PR TITLE
[FindInFiles] Use relative paths in the Path column, when possible

### PR DESCRIPTION
**Pull request by knocte**
Relative paths to the solution base directory are easier to read
without horizontal scrolling.

### CODE REVIEW

**Comment by monoadmin** [comment]
Hello! I'm the build bot for the Mono project. I need approval from a Mono team member to build this pull request. A team member should reply with "approve" to approve a build of this pull request, "whitelist" to whitelist this and all future pull requests from this contributor, or "build" to explicitly request a build, even if one has already been done. Contributors can ignore this message.

**Comment by slluis** [comment]
whitelist

**Comment by slluis** [comment]
This doesn't look right to me. I often use Find in File to search in directories outside the currently open solution, and it doesn't make sense to show relative paths in this case. Maybe we could show relative paths when using the "Whole Solution" option, but even in this case, it will look wrong if there is more than one solution open.

**Comment by Therzok** [comment]
This also won't work properly for Shared Projects.

**Comment by knocte** [comment]
> I often use Find in File to search in directories outside the currently open solution, and it doesn't make sense to show relative paths in this case.

Good point! I'll make sure to not pervert this case.

> Maybe we could show relative paths when using the "Whole Solution" option, but even in this case, it will look wrong if there is more than one solution open.

I'll create a new PR that changes "Whole Solution" to "All Solutions" when there are more than one solution open. And then after that is merged, I could make this relative paths change only work when there's only one solution open.

> This also won't work properly for Shared Projects.

Why not?

**Comment by Therzok** [comment]
> This also won't work properly for Shared Projects.
> Why not?

Solution A
- Shared Project C

Solution B
- Shared Project C

You're always taking the first defined project, so that means you'll only display the item relatively to Solution A, never to B.

**Comment by Therzok** [comment]
@knocte @slluis SearchResult.Projects isn't set when not using an in-IDE search.

**Comment by knocte** [comment]
> You're always taking the first defined project, so that means you'll only display the item relatively to Solution A, never to B.

But your case falls in the case already commented above: multiple solutions, in which case I plan to not use relative paths (in a 2nd iteration of this PR).

**Comment by Therzok** [comment]
Yeah, Late edit marked that I didn't read above, thought I had read them. Sorry once again for being misleading.

**Comment by knocte** [comment]
Updated PR so it only shows relative paths now, when solutions.Count == 1

**Comment by Therzok** [comment]
This no longer cleanly applies. Can you rebase?

**Comment by knocte** [comment]
Sure, will do later this week.

**Comment by knocte** [comment]
Rebased.

**Comment by Therzok** [comment]
LGTM, will merge when it's green.

**Comment by knocte** [comment]
Green :)

**Pull request merged**
