### PR TITLE
[Translation] Modify Japanese Translation,etc.

### PR DESCRIPTION
**Pull request by matyapiro31**
extras/BooBinding/po/ja.po
main/po/ja.po
	modified some mistaken words.
main/AUTHORS
	Add my name.
main/monodevelop.desktop
	Add Japanese Generic Name and Comment.

### CODE REVIEW

**Comment by monoadmin** [comment]
Hello! I'm the build bot for the Mono project. I need approval from a Mono team member to build this pull request. A team member should reply with "approve" to approve a build of this pull request, "whitelist" to whitelist this and all future pull requests from this contributor, or "build" to explicitly request a build, even if one has already been done. Contributors can ignore this message.

**Comment by mhutch** [comment]
@atsushieno could you please review this?

**Comment by atsushieno** [comment]
@matyapiro31 Thanks for the PR.

It is practically one line fix and very few lines of translation additions, so I'm not sure if you really want to have your name listed in "translators". This mostly means anyone will request questions, bugfix reports (just like I received right now), further translation requests etc. with related to the corresponding translated language your name indicates.

If you are okay with that, yeah I'd welcome this :-)

**Comment by atsushieno** [comment]
Oh and the changes LGTM.

**Comment by matyapiro31** [comment]
The change I did include #706 , so I did whole translation changing.
It is worth for me being listed.

**Comment by atsushieno** [comment]
Cool! Let me rather actually check that translation.

@mhutch I'm okay to merge this. But I found several issues in the translations in #706, which I will be commenting soon-ish.

**Comment by matyapiro31** [comment]
Then I close this request and send the fix again.

**Pull request closed without merging**
