### PR TITLE
Fixes squiggles in Razor/Blazor files after project reload

### PR DESCRIPTION
**Pull request by KirillOsenkov**
Make sure dynamic files are added to the project info every time the project is reloaded.

Also double-check that the document we're about to reload still exists in the current solution.

Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1012526

### CODE REVIEW

**Comment by KirillOsenkov** [comment]
I've downloaded the .dmg and it seems to be fixing the issue.

**Comment by KirillOsenkov** [comment]
@monojenkins backport release-8.4

**Comment by slluis** [comment]
@KirillOsenkov next time set a PR title that actually describes what the PR fixes, and add the bug link in the PR body. Thanks.

**Comment by KirillOsenkov** [comment]
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1012526

**Comment by slluis** [comment]
@KirillOsenkov thanks, although the fix message has to be in the PR body, not in the description

**Comment by KirillOsenkov** [comment]
Sorry, fixed now.

**Comment by slluis** [comment]
Thanks!

**Pull request merged**
