### PR TITLE
[Unit Test] Fix the nesting for unit tests

### PR DESCRIPTION
**Pull request by ketttY**
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/901156/

### CODE REVIEW

**Comment by ketttY** [comment]
@monojenkins rebase

**Comment by ketttY** [comment]
Current nesting:
**Solution -> Project -> Namespace -> Test class -> Test case**
Screen Shot 2019-11-26 at 10 51 44 AM

VS win doesn't have the solution layer displayed, wondering should we keep it or not?

**Comment by mrward** [comment]
VS Win does not support multiple solutions so they can avoid showing the solution. The Run All Tests is fine in VS Win for a single solution. If you have multiple solutions open in VS Mac there is no easy way to run all tests for a single solution if there is no root solution tree node. Which probably means we need to keep the solution node at the top.

**Comment by mrward** [comment]
Can we add some screenshots before and after the change?

Also might be worth adding some tests for this new logic. There are tests for the VS Test tree but since everything is green here it seems I did not add enough tests to cover the original namespace logic otherwise some would have failed.

https://github.com/mono/monodevelop/tree/master/main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.Tests/MonoDevelop.UnitTesting.Tests

**Comment by ketttY** [comment]
Screen Shot 2019-12-03 at 4 56 55 PM

- **Project**: mstest

- **Namespaces**: 

   1. mstest (with **childNamespace**: childNamespace)
   2. mstest2

**Comment by mrward** [comment]
Was hoping for some unit tests to be added before this was merged 😞

**Pull request merged**
