### PR TITLE
[FileSystemWatcher] Remove source copy now that mono has fixed thread starvation on macOS

### PR DESCRIPTION
**Pull request by Therzok**
Minimum mono version has all the corefx fixes we want, so we don't need to source copy.

Keep old FileWatcherService logic for Linux, as corefx watcher still uses one thread per watcher.

Move to a refcounted filewatcher cache on macOS and Windows.

Fixes VSTS #765539 - Remove the source copy of FileSystemWatcher code

### CODE REVIEW

**Comment by Therzok** [comment]
@mrward are we missing an event to wait for in the watcher for the renaming outside the directory?

There's another version of this in a different branch here: https://github.com/mono/monodevelop/commits/fsw-source-copy-removal-backup

And it has the same reason. Before pinging mono, would like to confirm if we're missing anything on our side.

**Comment by mrward** [comment]
Not sure I understand the question. Are we talking about the failing MoveDirectoryOutsideProjectDirectory test? There was no change made to the file watcher service for that test that is failing. The [logic](https://github.com/mono/monodevelop/commit/9c5fa2a5f8a3c1b910d364d77f98a793702d202a) just used the file watcher service's rename event.

**Comment by mrward** [comment]
Maybe the MoveDirectoryOutsideProjectDirectory test needs to be changed. Would need to see the events being fired. In the test it triggers a new event after the event that is being tested for and then waits for this new event to be fired so the event being tested should have been handled by then.

The test seems OK. After the Directory.Move it adds a new file to the project and waits for that - which does not fail the assert.

Probably need to add some logging to the file watcher and see what events are being generated.

**Comment by Therzok** [comment]
Added logging and created https://github.com/mono/monodevelop/commits/no-merge-file-watcher-logging to compare with.

**Comment by mrward** [comment]
Is that output from a different test? Seems like it is missing the NewCSharpFile2.cs file for the failing MoveDirectoryOutsideProjectDirectory test. Looks like logging was enabled for the MoveDirectoryUpToProjectRootDirectory_FileServiceEventsFired test which is passing.

**Comment by Therzok** [comment]
New logs.

Old (source copy):
```
2019-01-20T18:50:58.0273410Z New watchers list:
2019-01-20T18:50:58.0276230Z /Users/vsts/agent/2.144.2/work/r1/a/VS for Mac/drop/tests/tmp/DotNetCoreFileWatcherTests.sln-34
2019-01-20T18:50:58.0278090Z Adding new watcher /Users/vsts/agent/2.144.2/work/r1/a/VS for Mac/drop/tests/tmp/DotNetCoreFileWatcherTests.sln-34
2019-01-20T18:50:58.1113370Z File created /Users/vsts/agent/2.144.2/work/r1/a/VS for Mac/drop/tests/tmp/DotNetCoreFileWatcherTests.sln-34/NetStandard/Src
2019-01-20T18:50:58.1114460Z File created /Users/vsts/agent/2.144.2/work/r1/a/VS for Mac/drop/tests/tmp/DotNetCoreFileWatcherTests.sln-34/NetStandard/Src/NewCSharpFile.cs
2019-01-20T18:50:58.1259860Z File created /Users/vsts/agent/2.144.2/work/r1/a/VS for Mac/drop/tests/tmp/DotNetCoreFileWatcherTests.sln-34/NetStandard/Src
2019-01-20T18:50:58.1260920Z File renamed /Users/vsts/agent/2.144.2/work/r1/a/VS for Mac/drop/tests/tmp/DotNetCoreFileWatcherTests.sln-34/NetStandard/Src -> /Users/vsts/agent/2.144.2/work/r1/a/VS for Mac/drop/tests/tmp/DotNetCoreFileWatcherTests.sln-34/RenamedSrc
2019-01-20T18:50:58.1262180Z File created /Users/vsts/agent/2.144.2/work/r1/a/VS for Mac/drop/tests/tmp/DotNetCoreFileWatcherTests.sln-34/NetStandard/NewCSharpFile2.cs
```

New (mono updated):
```
2019-01-20T18:51:01.3641800Z New watchers list:
2019-01-20T18:51:01.3643300Z /Users/vsts/agent/2.144.2/work/r1/a/VS for Mac/drop/tests/tmp/DotNetCoreFileWatcherTests.sln-34
2019-01-20T18:51:01.3644110Z Adding new watcher /Users/vsts/agent/2.144.2/work/r1/a/VS for Mac/drop/tests/tmp/DotNetCoreFileWatcherTests.sln-34
2019-01-20T18:51:01.4448920Z File created /Users/vsts/agent/2.144.2/work/r1/a/VS for Mac/drop/tests/tmp/DotNetCoreFileWatcherTests.sln-34/NetStandard/Src
2019-01-20T18:51:01.4449880Z File created /Users/vsts/agent/2.144.2/work/r1/a/VS for Mac/drop/tests/tmp/DotNetCoreFileWatcherTests.sln-34/NetStandard/Src/NewCSharpFile.cs
2019-01-20T18:51:01.4587850Z File created /Users/vsts/agent/2.144.2/work/r1/a/VS for Mac/drop/tests/tmp/DotNetCoreFileWatcherTests.sln-34/NetStandard/Src
2019-01-20T18:51:01.4600220Z File renamed /Users/vsts/agent/2.144.2/work/r1/a/VS for Mac/drop/tests/tmp/DotNetCoreFileWatcherTests.sln-34/NetStandard/Src -> /Users/vsts/agent/2.144.2/work/r1/a/VS for Mac/drop/tests/tmp/DotNetCoreFileWatcherTests.sln-34/RenamedSrc
2019-01-20T18:51:01.4613520Z File created /Users/vsts/agent/2.144.2/work/r1/a/VS for Mac/drop/tests/tmp/DotNetCoreFileWatcherTests.sln-34/NetStandard/NewCSharpFile2.cs
```

**Comment by mrward** [comment]
The file watcher events are the same. Something else must be happening in the Project causing the file not be moved. Not sure what without debugging that.

**Review by mrward — APPROVED** [review]

**Comment by Therzok** [comment]
Different one failed this time. Will take a look. We possibly need to wait for all events to come in.

**Pull request merged**
