### PR TITLE
Add packages restore for mono-addins in winbuild.bat

### PR DESCRIPTION
**Pull request by mfilippov**
Without it build on broken with error reference to SharpZipLib.

### CODE REVIEW

**Comment by mrward** [comment]
Currently on Windows the [MonoLibraries.msi](https://files.xamarin.com/~jeremie/MonoLibraries.msi) is used to install SharpZipLib into the GAC. This is the assembly that Mono.Addins.Setup builds against when compiling MonoDevelop on Windows, which is a different version to that used in the packages.config file. If you install the MonoLibraries.msi then the build will work without the change you have made.

So I think restoring SharpZipLib from NuGet will cause different versions of this .dll to be used by different parts of MonoDevelop, unless we publish the version currently being used by MonoDevelop to NuGet and use that in Mono.Addins.Setup.

**Comment by mfilippov** [comment]
@mrward I thought in external dependencies we should use version from dependency package.config same as RefactoringEssentials.

**Comment by mrward** [comment]
@mfilippov - Yes, most of the time :) SharpZipLib is currently a special case.

**Comment by mfilippov** [comment]
@mrward ok

**Pull request closed without merging**
