### PR TITLE
[MonoTODO] Implement the analyzer via IOperation

### PR DESCRIPTION
**Pull request by Therzok**
This optimizes performance by not force binding every identifier name in the code, but rather on specific usage:
It will highlight on usage of a type/member of a type that is marked with the attribute, similarly to how the old code
did.

### CODE REVIEW

**Comment by slluis** [comment]
@Therzok this PR is old. Is it still valid?

**Comment by Therzok** [comment]
Yes, I want to get around to reviving this and making it report squiggles locations better.

**Comment by Therzok** [comment]
Possibly 15.9 tentative?

**Comment by Therzok** [comment]
Closing in favor of a future PR.

**Pull request closed without merging**
