### PR TITLE
Make framework check more robust. Fixes #49518

### PR DESCRIPTION
**Pull request by nosami**
https://bugzilla.xamarin.com/show_bug.cgi?id=49518

### CODE REVIEW

**Comment by Therzok** [comment]
Why is `framework.Assemblies` empty though?

**Comment by slluis** [comment]
Good question, why is this happening?

**Comment by nosami** [comment]
Not sure. Will investigate

**Comment by nosami** [comment]
Took me a ridiculously long time to work out the cause of this error.. but this was it https://github.com/mono/monodevelop/commit/dc6a7646e17aea9378a4fc44c8b668f6de7de8a4

**Pull request closed without merging**
