### PR TITLE
[Ide] Fix concurrency on defaultmonitorpad accessing.

### PR DESCRIPTION
**Pull request by Therzok**
Bug 40373 - Null reference exception in ScrollView

cc @alanmcgovern

### CODE REVIEW

**Comment by Therzok** [comment]
I assume the NRE was coming from a monitor pad being reused after it was being disposed, as a side-effect of properly disposing of pads in https://github.com/mono/monodevelop/commit/abf8bcaa7046978c7eb65e9f423665d314decdcf

**Comment by slluis** [comment]
GetPadForMonitor should only be called from the UI thread, in which case the lock should not be necessary.

**Comment by Therzok** [comment]
Fixed review comment and added safeguard against addins manually destroying pads. The progress monitor completion was happening after its underlying pad was destroyed.

**Comment by Therzok** [comment]
After further investigation, the problem is that the pad outlives the monitor in the case of the resgen pad, because the pad is manually destroyed before the monitor is disposed. That causes the monitor to try and queue the completed message. 65ba2fd safeguards against this case now, that the pad is no longer getting leaked.

**Comment by Therzok** [comment]
Bump.

**Pull request merged**
