### PR TITLE
Editor: Support for ShowQuickInfo command

### PR DESCRIPTION
**Pull request by sandyarmstrong**
Depends on an upcoming editor update to actually handle this command.

Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1001949

### CODE REVIEW

**Comment by sandyarmstrong** [comment]
@monojenkins backport release-8.4

**Comment by nosami** [comment]
> Depends on an upcoming editor update to actually handle this command.

Shouldn't the upcoming editor update be the ticket to "Fix" 1001949 then? I don't want the ticket to get lost.

**Comment by sandyarmstrong** [comment]
@nosami when I pushed this I thought there was a decent chance the editor update would actually merge _first_. Whichever change merges last should, in theory, be the one with the fix comment. But honestly at this point both are reviewed and I'll just make sure they merge roughly together. :)

**Comment by sandyarmstrong** [comment]
@nosami editor-side changes merged yesterday, so this should now work. I don't expect perfect behavior yet, so please feel free to file bugs for any issues with it.

**Comment by nosami** [comment]
@sandyarmstrong Thanks! I'll try it out

**Pull request merged**
