### PR TITLE
Metadata reference cache 7.6

### PR DESCRIPTION
**Pull request by Therzok**
cc @mrward 

https://github.com/mono/monodevelop/pull/5555

Fixes VSTS 593840

### CODE REVIEW

**Comment by GLjackyvaswani** [comment]
Build Taken from: https://dl.internalx.com/artifacts/devdiv-1910342/VisualStudioForMac-Preview-7.6.0.2125.dmg

Build Gist: https://gist.github.com/mohakbarokar/05d4f4c2c1897fd877791bb64b6113d9

Verification steps: Open attached Solution from zip file

1. Open `Program.cs`, see that `testlib.MyClass()` has red squiggle
2. Build just `testlib`, see that squiggles are gone
3. Open `MyClass.cs`, comment out `Do()` and `Do1()`
4. Go to `Program.cs`, see that `testlib.MyClass` has no squiggle
5. Build just `testlib`, see that `Do()` and `Do1()` in `Program.cs` has red squiggle
6. Uncomment `Do()` and `Do1()`
7. See that they still have squiggle in Program.cs
8. Build just `testlib`
9. See that no squiggles are in Program.cs 

This implementation is working as expected. Marking the User Story as QA-Approved

**Comment by Therzok** [comment]
Not merging until I also fix this: https://github.com/mono/monodevelop/issues/5569

**Comment by Therzok** [comment]
Bug fixed, rebased, will merge

**Comment by sgmunn** [comment]
Tested, reviewed and approved in master. taking this.

**Pull request merged**
