### PR TITLE
[8.1][Ide] GLib logging now uses loginternalerror so we can track glib exceptions

### PR DESCRIPTION
**Pull request by Therzok**
Fixes VSTS #890423 - [Telemetry] VS for Mac should log GTK fatal errors to telemetry
Fixes VSTS #867387 - [Telemetry] Objective-C based crashes should log exception information to telemetry

cc @leculver

### CODE REVIEW

**Comment by Therzok** [comment]
Hmmm, the PR is still messed up. I'll fix.

@slluis Lee said we might want this in for 8.1 P2.

**Comment by leculver** [comment]
@Therzok If possible, yes.  p2 would be the best route so we can try to fix some of these problems before 8.1 RTM.  If it's not feasible in that timeframe or would otherwise risk getting preview 2 out the door, then we can live without it.  Whichever is best for the product.

**Comment by Therzok** [comment]
@slluis can you merge?

**Comment by Therzok** [comment]
Cherry-picked the other commits from https://github.com/mono/monodevelop/pull/7598

**Review by slluis — APPROVED** [review]

**Pull request merged**
