### PR TITLE
Fixes VSTS Bug 665407: TypeScript/JavaScript TextMate syntax

### PR DESCRIPTION
**Pull request by mkrueger**
highlighting errors

https://devdiv.visualstudio.com/DevDiv/_workitems/edit/665407

Was caused by an isanity check to prevent infinite loops.
Unfortunately it's not so easy to determine state changes that way in
complex grammars. However there is another one implemented : timeouts.

That's enough to prevent infinite loops so this is not really needed
anymore.

### CODE REVIEW

**Comment by KirillOsenkov** [comment]
@mkrueger could this bug explain what @praeclarum is seeing here: 
https://developercommunity.visualstudio.com/content/problem/317246/c-code-coloring-is-inconsistent-isnt-applied-to-la.html

If so, we probably want this in 7.6.1. /cc @slluis

**Comment by KirillOsenkov** [comment]
@minestarks could you please try the Dmg from Mike's fix and see if it fixes your issue:
https://dl.internalx.com/artifacts/devdiv-1966126/VisualStudioForMac-Preview-7.8.0.156.dmg

**Comment by minestarks** [comment]
Tried it out, looks a lot better, thank you!

**Comment by KirillOsenkov** [comment]
@monojenkins backport release-7.6

**Comment by KirillOsenkov** [comment]
We will take it for 7.6.1.

**Comment by slluis** [comment]
@KirillOsenkov several tests are failing in this PR and in the 7.6 backport.

**Comment by KirillOsenkov** [comment]
@mkrueger the test that is being added is failing - although @minestarks reports that this fix is good, any idea why the test still fails?

**Comment by Therzok** [comment]
I suppose mike is using a different theme locally.

**Comment by KirillOsenkov** [comment]
Fixed the test.

**Comment by mkrueger** [comment]
text/x-typescript fails for me locally. I suppose something is wrong with the mime type definitions in monodevelop.

**Comment by mkrueger** [comment]
Added the typescript mime type.

**Comment by KirillOsenkov** [comment]
@mkrueger  Oh, the typescript mime type is defined in WebTools addin. Is a duplicate declaration OK?

**Comment by mkrueger** [comment]
@KirillOsenkov: Shouldn't harm but can be removed there - for the unit tests it's required to have it inside the core.

**Comment by KirillOsenkov** [comment]
@slluis shall we merge this? We'd need this in release-7.6 as well to fix the classification problems.

**Comment by slluis** [comment]
@monojenkins backport release-7.6

**Pull request merged**
